### ISSUE TITLE
TowerSE: The optimization section looks like as same in oldTower.py

### ISSUE THREAD

**Issue by SamAct** [WISDEM/WISDEM#106]
The optimization section looks like as same in [oldTower.py ](https://github.com/WISDEM/TowerSE/blob/master/src/towerse/oldTower.py) And obviously it doesn't work even after updating as per the new openmdao guidelines. 

Is an update available on this? Has anyone looked into this and got it to work, if possible please share a commit.
Also is https://github.com/WISDEM/TowerSE/issues/9 expected to be implemented here?

**Comment by gbarter** [comment]
Thank you for pointing this out.  It has been fixed in the [development branch](https://github.com/WISDEM/WISDEM/blob/c747d8c062faae87693311b2455530932c5cac3d/wisdem/towerse/tower.py#L934)
