### ISSUE TITLE
pyoptsparse

### ISSUE THREAD

**Issue by peter-greaves** [WISDEM/WISDEM#114]
I'm having trouble installing pyoptsparse on Windows - is there any guidance for doing this as it doesn't seem to be able to be installed with conda, and when I install with pip it doesn't show in the conda list of installed packages. I've tried everything on the mdolab website but I'm still not having any luck (it's heavily aimed at Linux users) - am I right in saying I won't be able to use multiple processors for gradient evaluations without pyoptsparse?

I managed to get an optimisation running with the SciPy wrapper so apart from this the install is working well.

**Comment by gbarter** [comment]
Not sure exactly what error you have been getting.  From prior experience, I had trouble with one of the optimizers in particular, FSQP.  To get the compile past the trouble spot, I just commented out that one optimizer and used the other ones.  Edit `pyoptsparse\pyoptsparse\setup.py` and comment out the line:
`#    config.add_subpackage('pyFSQP')`

If you grab pyoptsparse from this fork: https://github.com/evan-gaertner/pyoptsparse
Then, that should already be commented out for you.

**Comment by peter-greaves** [comment]
Thanks for that - I found when installing this on Windows that petsc and petsc4py were very challenging to install (I never actually managed to get it working). I've now set up a Ubuntu virtual machine using Hyper-V and everything installs very nicely using the method described - is it worth mentioning that this might be a route for people wanting to do parallel stuff on the install page?

**Comment by rdamiani** [comment]
Hello, 

I have used Evan's fork to install pyoptsparse, but

when I issue prob.driver =om.pyOptSparseDriver()
I get this error:
AttributeError: module 'signal' has no attribute 'SIGUSR1'

This is on Windows, and I read that SIGUSR1 should be changed to SIGTERM for Windows,  

Can you point me to where I would find the offending attribute or how would I bypass this issue?
Thanks in advance.

**Comment by peter-greaves** [comment]
Hi,

I didn’t have any luck with this I’m afraid – what I’d recommend is installing a Ubuntu 18.04 virtual machine using Hyper-V in Windows 10 and then installing Anaconda on it and running WISDEM using that. It’s super easy if you just follow the instructions for installing if you do it this way. I had no luck with Windows – PETSC was the problem from memory.

Hope that helps!

Pete

**Comment by rdamiani** [comment]
Yes the official MPI does not get installed on windows, but in previous versions of OMDAO/WISDEM I had the pyopt driver working on windows as well, and I was hoping it could still work here, I may ask Justin if he has a workaround, else I might have to give it up.
Thanks for the input.

**Comment by gbarter** [comment]
You can try the UMichigan MDO-Lab version of pyoptsparse: https://github.com/mdolab/pyoptsparse
This is kept more up-to-date.  We use a slightly older version because we have an older version of SNOPT with a slightly different API and we would like to keep using it without paying for a new license.

**Comment by rdamiani** [comment]
I may try that also, but I have the same license problem...
I wonder whether it is on the OMDAO side however, I found  that attribute in the driver under MDAO's install folder.
I will let you know if I get anywhere with this.

**Comment by gbarter** [comment]
Hi Rick,

I just tried all of the tests in both the evan-gaertner fork and the MDO-Lab version on my windows VM and couldn't recreate the error.  If you have a simple script that produces the problem, let me know.

**Comment by rdamiani** [comment]
HI Garrett,

I just set up a 
```
prob= om.Problem()
prob.model=OptPolars(nws=nws,airfs_in=myblade.airfs,CCairfs_in=myblade.CCairfs,\
                         afids=myblade.afids,nppts=nppts, rotgeom=rotgeom,atmos=atmos,numerics=numerics, refdata=refdata) 
prob.driver =om.pyOptSparseDriver()
```

and then I get that error. Ken@NASA says it is a bug in pyoptsparse_driver.py, which I have fixed by changing it to either None or SIGTERM.
Hope this helps others too.
Best,

**Comment by gbarter** [comment]
This is really helpful, Rick- thank you!  To aid in this helping others, the offending line is:
https://github.com/OpenMDAO/OpenMDAO/blob/master/openmdao/drivers/pyoptsparse_driver.py#L191
This needs to be signal.SIGTERM and not signal.SIGUSR1

**Comment by MYMahfouz** [comment]
I am trying to setup pyoptsparse for Windows. I have tried the evan-gaertner fork but I am getting an encoding error.
Is there an updated version for for this fork?

Thanks..

**Comment by gbarter** [comment]
pyOptSparse on Windows continues to be a significant challenge, no matter which fork is used.  I am no longer able to get it to compile myself.  There is now a `pyoptsparse` package available for `conda` on Linux & Mac, but not Windows (recent WISDEM installation instructions on the `develop` branch now rely on this).  The MDO Lab team has identified a difficult workaround documented [here](https://github.com/mdolab/pyoptsparse/issues/273).  We would recommend either sticking with the ScipyDriver on Windows or using the Windows Ubuntu Subsystem for Linux-like experience.

**Comment by gbarter** [comment]
An update here: Looks like `pyoptsparse` via conda is not working for all platforms, including Windows.  Exciting!
