### ISSUE TITLE
Analysis level : running FAST instead of CC blade

### ISSUE THREAD

**Issue by benoitpaillard** [WISDEM/WISDEM#117]
Hi all,
I'm trying to change the analysis level from CCblade to OpenFAST by changing this line in tutorial 4:

`Analysis_Level        = 2 # 0: Run CCBlade; 1: Update FAST model at each iteration but do not run; 2: Run FAST w/ ElastoDyn; 3: (Not implemented) Run FAST w/ BeamDyn`

It crashes with an issue on `fst_vt` variable, because this is set to an empty dict in the tutorial. I digged in the source code and realized there are heaps of very thorough python scripts that take care of OpenFAST, but unfortunately I could not make it to run.

My understanding is that I need to provide a .yaml file that fst_vt will read and be used as a setup of OpenFAST environment, is that correct ? If so, I tried to find an example of such a file somewhere but without luck.

Any hint on how to make OpenFAST run in Wisdem would be great !

Thanks a lot.

**Comment by evan-gaertner** [comment]
Hello,
Apologies that these features are not better documented.  We have begun working on an updated documentation [here](https://wisdem.readthedocs.io/en/latest/), but it will be some time before it is complete.

The variable causing the issue, 'fst_vt', is a nested dictionary containing all of the input variables for OpenFAST, across all of the OpenFAST input files for an existing model.  To use the OpenFAST features, you need to point WISDEM to an existing OpenFAST model, which will be read in, modified, and new output files written to a run directory where they will be executed.

How the OpenFAST inputs to WISDEM are specified depends on the branch:
- master: OpenFAST is only used in the RotorSE module, see https://github.com/WISDEM/WISDEM/blob/master/wisdem/rotorse/rotor.py for an example of its use
- IEAOntology4All (currently our most actively developed branch, which will soon be merged into 'develop'): See https://github.com/WISDEM/WISDEM/blob/IEAontology4all/wisdem/assemblies/main.py In this branch, an additional yaml file has the analysis settings, including whether to run OpenFAST and the paths to OpenFAST model and executable

A couple of additional things to point out.  The OpenFAST implementation is currently fairly limited in what DLC will be run.  The user can specify a number of predefined load cases which replace some of the normally steady state load analysis.  Please use these features with caution and be sure you understand the OpenFAST settings being used.  You will also need working OpenFAST and Turbsim executable.

Best Regards,
Evan
