### ISSUE TITLE
Fatigue on Tower

### ISSUE THREAD

**Issue by SamAct** [WISDEM/WISDEM#119]
Is there is commit where Fatigue calculation is enabled on a Tower?

**Comment by gbarter** [comment]
Sorry, WISDEM currently uses a steady-state assumption with static loading scenarios, so no fatigue calculations are performed.  This is something we are looking at including in the future- either by moving to simple time-domain analyses or by using empirical fatigue models.

**Comment by SamAct** [comment]
No I mean we have the fatigue inputs as DEL's over the tower span in the tower file but aren't unable Is it working in any commit?

**Comment by gbarter** [comment]
Not sure which branch you are using, but this capability has been commented out for a while.  I think it may still be functional though.  Are you using WISDEM from source or conda?  If from source, do a search for "_DEL" in [tower.py](https://github.com/WISDEM/WISDEM/blob/master/wisdem/towerse/tower.py) and uncomment.

**Comment by SamAct** [comment]
I tried commenting all the lines that relate to this in c747d8c as suggested above it works. I had tried this previously but made the mistake of commenting line https://github.com/WISDEM/WISDEM/blob/c747d8c062faae87693311b2455530932c5cac3d/wisdem/towerse/tower.py#L595 and https://github.com/WISDEM/WISDEM/blob/c747d8c062faae87693311b2455530932c5cac3d/wisdem/towerse/tower.py#L586 . Not sure why are this for, but your suggestion works.  thanks.
