### ISSUE TITLE
Installation issue: "cannot import name 'Polar' from 'airfoilprep' " 

### ISSUE THREAD

**Issue by CallumG-Ed** [WISDEM/WISDEM#120]
Hi there is a few issues outstanding on the AirfoilPreppy [page](https://github.com/WISDEM/AirfoilPreppy/issues/19)  that I wonder whether might get better attention here. Running the test after installing is returning error:

`Traceback (most recent call last): File "test/test_airfoilprep.py", line 5, in <module> from airfoilprep import Polar, Airfoil ImportError: cannot import name 'Polar' from 'airfoilprep' (C:\Users\Usr\Anaconda3\envs\wisdem-env\lib\site-packages\airfoilprep-0.1.0-py3.7.egg\airfoilprep\__init__.py)`

Any help appreciated!

Cheers
Callum

**Comment by gbarter** [comment]
I don't know why I wasn't notified of those Issues.  My apologies.  I have addressed them in that repo and they are also reflected within WISDEM now too.
