### ISSUE TITLE
Correct Input file format for AirfoilPreppy?

### ISSUE THREAD

**Issue by CallumG-Ed** [WISDEM/WISDEM#121]
Hi,

I'm trying to use AirfoilPreppy form the command line as described [here](http://wisdem.github.io/AirfoilPreppy/tutorial.html) to do some extrapolation of high AoA. I downloaded the AeroDyn example input file to test it on from [here](https://openfast.readthedocs.io/en/master/source/user/aerodyn/appendix.html#ad-appendix) and removed a few lines from the Cl/Cd table at the bottom.

When I envoke command: 
`python airfoilprep.py airfoil_3D.dat --extrap 1.3`

An error is returned:
`Traceback (most recent call last):
  File "airfoilprep.py", line 1061, in <module>
    af = Airfoil.initFromAerodynFile(args.src_file)
  File "airfoilprep.py", line 555, in initFromAerodynFile
    numTables = int(f.readline().split()[0])
ValueError: invalid literal for int() with base 10: '!'`

I'd appreciate if someone could provide a correctly formatted input file for the script maybe?

Cheers
Callum

**Comment by gbarter** [comment]
I don't know why I wasn't notified of those Issues. My apologies. I have addressed them in that repo and they are also reflected within WISDEM now too.
