### ISSUE TITLE
 No module named 'wisdem.lcoe'

### ISSUE THREAD

**Issue by mftatfcyclone** [WISDEM/WISDEM#122]
I have a problem with installing WISDEM on windows 10 x64. I am a beginner user of WISDEM and I can not follow the tutorial provided with it. When I type the following  import comand in Python, an error is arising: 
```
> import wisdem.lcoe.lcoe_csm_assembly
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'wisdem.lcoe'
```

Also, I failed in the following tests because  No such file or directory are exist.
python src/test/test_WISDEM.py
python src/test/test_turbine_gradients.py

Note: I installed WISDEM as user, not developer

**Comment by gbarter** [comment]
I think you were led astray by some very old and stale documentation, sorry about that.  We have recently embarked on a major documentation improvement effort that is aimed at a future branch, which will hopefully be ready for the public in a few more months.

In the meantime, I have removed the old documentation.  It sounds like you were interested in the Cost and Scaling Model features of WISDEM.  I suggest you scroll through this [tutorial](https://github.com/WISDEM/WISDEM/blob/master/tutorial-notebooks/01_cost_and_scaling.ipynb) to see if that is what you are indeed looking for.  Let me know if you had other functionality in mind.

**Comment by mftatfcyclone** [comment]
Thank you for your clarification.
However, I am interested more in Rotor and drivetrain design.  So, I would appreciate it if you provide me some more detailed tutorials for any module specially DrivetrainSE, RotorSE, FloatingSE , and TowerSE.

**Comment by gbarter** [comment]
We are working on a major overhaul of the documentation with examples and tutorials for each module.  A sneak peak is [here](https://wisdem.readthedocs.io/en/latest/index.html).  You can find some examples for RotorSE and TowerSE at the bottom of wisdem/rotor/rotor.py and wisdem/tower/tower.py.  FloatingSE is documented at that new link, but is about to undergo a major overhaul in the next 6-12 months.  DrivetrainSE will be overhauled in the next few months, but is best described in this [paper](https://www.nrel.gov/docs/fy15osti/63008.pdf).
