### ISSUE TITLE
update jacket and reference jacket files with new JacketSE content

### ISSUE THREAD

**Issue by dykesk** [WISDEM/WISDEM#13]
JacketSE has had significant updates; ensure that the assemblies for the jacket in wisdem are updated to include a working version of the code with the jacket in the mix

**Comment by dykesk** [comment]
Note - we removed the jacket assemblies from the master version and through some merges they were also lost from the develop branch; they can be found in this wisdem commit:  https://github.com/WISDEM/WISDEM/tree/18dd8e2c3738d107da5d9c74de1f122cfb89e54a

**Comment by kilojoules** [comment]
It runs! See commit 789de59fbd08ccce7dc7427ef92ce4fd63596e23
