### ISSUE TITLE
Impacts of Nacelle mass moment of inertia

### ISSUE THREAD

**Issue by SamAct** [WISDEM/WISDEM#131]
I did a quick study that looked at changes in Nacelle mass moments of inertia `mIxx`, `mIyy`, `mIzz`, `mIxy`, `mIxz `and `mIyz `on a tower.
It is clearly been used in the `CylinderFrame3DD `class in `vertical_cylinder.py` as `changeExtraNodeMass`. The impacts all resulted in none, i.e no change was seen. Can you clarify this. Why is it? What is `changeExtraNodeMass` for?

I am using https://github.com/WISDEM/WISDEM/issues/106

Edit:  I am looking at frequencies, top_deflection, stress, gl_buckling and shell_buckling for variations. Am i missing anything here.

**Comment by gbarter** [comment]
When adding extra mass to a node in Frame3DD, you also have to specify the added moments of inertia.  Depending on the geometry of the problem and the analysis outputs, this may or may not have an impact on the final results.  I have not run this investigation myself, but I will take your word for it that changing the MoI at the top of the tower does not really impact the other outputs from TowerSE.  Certainly changing the nacelle mass has a significant impact on the axial loading though.
