### ISSUE TITLE
Fatigue M_DEL along Tower Section

### ISSUE THREAD

**Issue by SamAct** [WISDEM/WISDEM#145]
How is M_DEL defined for the tower? Which sensor is it from, i suppose this is resultant moment from an aero-elastic tool. Does it include just the wind forces or tower-top as well. Or is it in the direction of wind? Can you elaborate taking in the example available https://github.com/WISDEM/WISDEM/commit/c747d8c062faae87693311b2455530932c5cac3d here. If you can specify the sensor you would use for this, that be helpful. Thank you

**Comment by gbarter** [comment]
I think we discussed a similar question previous: https://github.com/WISDEM/WISDEM/issues/119

The idea with the DEL entries was to do a simplified fatigue analysis after running in OpenFAST.  The locations of the moments are given with z_DEL and the damage equivalent moments with M_DEL. The choice of which driving loads and degrees of freedom were activated in OpenFAST was up to the user.  You would also specify a safety factor, lifetime (in years), and slope of the S-N curve:
`z_DEL = np.array([0.000, 1.327, 3.982, 6.636, 9.291, 11.945, 14.600, 17.255, 19.909, 22.564, 25.218, 27.873, 30.527, 33.182, 35.836, 38.491, 41.145, 43.800, 46.455, 49.109, 51.764, 54.418, 57.073, 59.727, 62.382, 65.036, 67.691, 70.345, 73.000, 75.655, 78.309, 80.964, 83.618, 86.273, 87.600])`
`M_DEL = 1e3*np.array([8.2940E+003, 8.1518E+003, 7.8831E+003, 7.6099E+003, 7.3359E+003, 7.0577E+003, 6.7821E+003, 6.5119E+003, 6.2391E+003, 5.9707E+003, 5.7070E+003, 5.4500E+003, 5.2015E+003, 4.9588E+003, 4.7202E+003, 4.4884E+003, 4.2577E+003, 4.0246E+003, 3.7942E+003, 3.5664E+003, 3.3406E+003, 3.1184E+003, 2.8977E+003, 2.6811E+003, 2.4719E+003, 2.2663E+003, 2.0673E+003, 1.8769E+003, 1.7017E+003, 1.5479E+003, 1.4207E+003, 1.3304E+003, 1.2780E+003, 1.2673E+003, 1.2761E+003])`
`nDEL = len(z_DEL)`
`gamma_fatigue = 1.35*1.3*1.0`
`life = 20.0`
`m_SN = 4`

We stopped supporting this type of analysis for a couple of reasons:
- It became too much overhead to run OpenFAST before WISDEM.  We would ideally like to do the reverse to limit the computational time.
- The DELs were assumed frozen in this approach, but as the tower optimization changed the design, the dynamic response would change and the DELs should ideally be updated.
- We will eventually move to supporting fatigue analysis in WISDEM, we are just not there yet

Hope this helps!

**Comment by SamAct** [comment]
Ok so what i understand the next plan is to design the tower based on extreme load cases and then calculate the DELs from OpenFAST? or are you planing to integrate the full fatigue loads/ DELs calculation method here?

**Comment by gbarter** [comment]
Yes, doing design under extreme loads in WISDEM and then seeing what the fatigue performance is within OpenFAST is our standard workflow.

WISDEM might get a low-fidelity version of fatigue estimation.  We are also debating moving to the time domain like OpenFAST.  Under the DOE ARPA-E program, WISDEM will marry with OpenFAST in a new repository and that is where the freq domain capabilities will reside.  Lots of moving pieces and changes coming in the next 6 months or so.
