### ISSUE TITLE
problems when installing in developer mode

### ISSUE THREAD

**Issue by Basvos91** [WISDEM/WISDEM#177]
Hi!

I am currently trying to get WISDEM running on my mac. 
I used the instructions from:
https://wisdem.readthedocs.io/en/latest/installation.html

however, once I get to the command 'python setup.py develop' I run into problems and get an error message.  
[error.txt](https://github.com/WISDEM/WISDEM/files/5598814/error.txt)

is there a way to fix this?

Kind regards,

Bas Vos

p.s.

**Comment by gbarter** [comment]
Did you recently upgrade your Mac's OS?  I have seen this error before in similar circumstances and there are other Google hits that are similar.  I would do the following:

`sudo rm -rf /Library/Developer/CommandLineTools`
`xcode-select --install`
`conda update -n base conda`
`conda update --all`

And then give the install another shot.  You might have to delete the aborted `build` directory in the WISDEM checkout too.

**Comment by Basvos91** [comment]
Thanks a lot! The installation completed. 

next problem is when running the 'python test_all.py'. seems like it can not find simp package?

[test_error.txt](https://github.com/WISDEM/WISDEM/files/5599022/test_error.txt)

**Comment by gbarter** [comment]
Likely just missed a line in the install instructions:
`pip install simpy marmot-agents`

**Comment by Basvos91** [comment]
Thanks again, it seems to be working now! 

The 'pip install simpy marmot-agents' line is not in the install instructions on https://wisdem.readthedocs.io/en/latest/installation.html

Thanks for the very quick help!
