### ISSUE TITLE
Problem importing lcoe_se_assembly due to LandBOS import error

### ISSUE THREAD

**Issue by taylor-parsons** [WISDEM/WISDEM#22]
Testing installation on Linux guest machine, all imports except for lcoe_se_assembly work. Error related to OpenMDAO not recognizing LandBOS:

(openmdao-0.12.0)tparsons@tparsons-VirtualBox:~/Documents/SE_Docs/WISDEM$ python
Python 2.7.6 (default, Mar 22 2014, 22:59:56) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.

> > > import wisdem.lcoe.lcoe_csm_assembly
> > > :0: FutureWarning: IPython widgets are experimental and may change in the future.
> > > 
> > > import wisdem.lcoe.lcoe_se_assembly
> > > /home/tparsons/Desktop/OpenMDAO/openmdao-0.12.0/local/lib/python2.7/site-packages/setuptools-0.9.5-py2.7.egg/pkg_resources.py:1054: UserWarning: /home/tparsons/.python-eggs is writable by group/others and vulnerable to attack when used with get_resource_filename. Consider a more secure location (set with .set_extraction_path or the PYTHON_EGG_CACHE environment variable).
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "/home/tparsons/Documents/SE_Docs/WISDEM/src/wisdem/lcoe/lcoe_se_assembly.py", line 26, in <module>
> > >     from landbos import LandBOS
> > > ImportError: No module named landbos
> > > import wisdem.turbinese.turbine
> > > exit()

**Comment by dykesk** [comment]
landbos is not part of the install yet since it needs updates; this needs to be fixed or can be commented out for now

**Comment by kilojoules** [comment]
@taylor-parsons I can't reproduce this problem. Is this still an issue? It looks like LandBOS has been replaced by NREL_Land_BOSSE in 0afec7a5839d835640e6fdb9896260d512a6f4bf

**Comment by dykesk** [comment]
Probably this is an old issue- close it out
