### ISSUE TITLE
Ex. 5 Tower and Monopile Example

### ISSUE THREAD

**Issue by pollinico** [WISDEM/WISDEM#225]
## Description
I have set up WISDEM following:  
https://wisdem.readthedocs.io/en/latest/installation.html  
I am trying the example n. 5 for tower optimization:  
https://wisdem.readthedocs.io/en/latest/examples/tower_mono/tutorial.html  
I get the following error:  
Exception has occurred: KeyError
'WISDEM'
  File "C:\Users\nipol\Documents\Work\Repos\WISDEM\wisdem\towerse\tower.py", line 1356, in setup
    mod_opt = self.options["modeling_options"]["WISDEM"]["TowerSE"]
  File "C:\Users\nipol\Documents\Work\Projects\Monopile optimization\Test_WISDEM_Ex5\ex5.py", line 78, in <module>
    prob.setup()

It seems that the problem is the keyword "WISDEM"

#### Two load cases
import numpy as np
import openmdao.api as om
from wisdem.towerse.tower import TowerSE
from wisdem.commonse.fileIO import save_data

#### Set analysis and optimization options and define geometry
plot_flag = False
opt_flag = False

n_control_points = 3
n_materials = 1
n_load_cases = 2

h_param = np.diff(np.linspace(0.0, 87.6, n_control_points))
d_param = np.linspace(6.0, 3.87, n_control_points)
t_param = 1.3 * np.linspace(0.025, 0.021, n_control_points - 1)
max_diam = 8.0

modeling_options = {}
modeling_options["flags"] = {}
modeling_options["materials"] = {}
modeling_options["TowerSE"] = {}
modeling_options["TowerSE"]["buckling_length"] = 30.0
modeling_options["flags"]["monopile"] = False

#### safety factors
modeling_options["TowerSE"]["gamma_f"] = 1.35
modeling_options["TowerSE"]["gamma_m"] = 1.3
modeling_options["TowerSE"]["gamma_n"] = 1.0
modeling_options["TowerSE"]["gamma_b"] = 1.1
modeling_options["TowerSE"]["gamma_fatigue"] = 1.35 * 1.3 * 1.0

#### Frame3DD options
modeling_options["TowerSE"]["frame3dd"] = {}
modeling_options["TowerSE"]["frame3dd"]["shear"] = True
modeling_options["TowerSE"]["frame3dd"]["geom"] = True
modeling_options["TowerSE"]["frame3dd"]["tol"] = 1e-9

modeling_options["TowerSE"]["n_height_tower"] = n_control_points
modeling_options["TowerSE"]["n_layers_tower"] = 1
modeling_options["TowerSE"]["n_height_monopile"] = 0
modeling_options["TowerSE"]["n_layers_monopile"] = 0
modeling_options["TowerSE"]["wind"] = "PowerWind"
modeling_options["TowerSE"]["nLC"] = n_load_cases
modeling_options["materials"]["n_mat"] = n_materials

prob = om.Problem()
prob.model = TowerSE(modeling_options=modeling_options)

if opt_flag:
#### Choose the optimizer to use
    prob.driver = om.ScipyOptimizeDriver()
    prob.driver.options["optimizer"] = "SLSQP"

#### Add objective
    prob.model.add_objective("tower_mass", scaler=1e-6)

#### Add design variables, in this case the tower diameter and wall thicknesses
    prob.model.add_design_var("tower_outer_diameter_in", lower=3.87, upper=max_diam)
    prob.model.add_design_var("tower_layer_thickness", lower=4e-3, upper=2e-1)

#### Add constraints on the tower design
    prob.model.add_constraint("post1.stress", upper=1.0)
    prob.model.add_constraint("post1.global_buckling", upper=1.0)
    prob.model.add_constraint("post1.shell_buckling", upper=1.0)
    prob.model.add_constraint("post2.stress", upper=1.0)
    prob.model.add_constraint("post2.global_buckling", upper=1.0)
    prob.model.add_constraint("post2.shell_buckling", upper=1.0)
    prob.model.add_constraint("constr_d_to_t", lower=120.0, upper=500.0)
    prob.model.add_constraint("constr_taper", lower=0.2)
    prob.model.add_constraint("slope", upper=1.0)
    prob.model.add_constraint("tower1.f1", lower=0.13, upper=0.40)
    prob.model.add_constraint("tower2.f1", lower=0.13, upper=0.40)

prob.setup()

prob["hub_height"] = prob["tower_height"] = h_param.sum()
prob["tower_foundation_height"] = 0.0
prob["tower_s"] = np.cumsum(np.r_[0.0, h_param]) / h_param.sum()
prob["tower_outer_diameter_in"] = d_param
prob["tower_layer_thickness"] = t_param.reshape((1, -1))
prob["tower_outfitting_factor"] = 1.07
prob["yaw"] = 0.0

#### offshore specific
prob["G_soil"] = 140e6
prob["nu_soil"] = 0.4

#### material properties
prob["E_mat"] = 210e9 * np.ones((n_materials, 3))
prob["G_mat"] = 80.8e9 * np.ones((n_materials, 3))
prob["rho_mat"] = [8500.0]
prob["sigma_y_mat"] = [450e6]

#### extra mass from RNA
prob["rna_mass"] = np.array([285598.8])
mIxx = 1.14930678e08
mIyy = 2.20354030e07
mIzz = 1.87597425e07
mIxy = 0.0
mIxz = 5.03710467e05
mIyz = 0.0
prob["rna_I"] = np.array([mIxx, mIyy, mIzz, mIxy, mIxz, mIyz])
prob["rna_cg"] = np.array([-1.13197635, 0.0, 0.50875268])

prob["unit_cost_mat"] = [2.0]  # USD/kg
prob["labor_cost_rate"] = 100.0 / 60.0  # USD/min
prob["painting_cost_rate"] = 30.0  # USD/m^2

#### wind & wave values
prob["wind_reference_height"] = 90.0
prob["wind_z0"] = 0.0
prob["cd_usr"] = -1.0
prob["rho_air"] = 1.225
prob["mu_air"] = 1.7934e-5
prob["beta_wind"] = 0.0
if modeling_options["TowerSE"]["wind"] == "PowerWind":
    prob["shearExp"] = 0.2

prob["wind1.Uref"] = 11.73732
Fx1 = 1284744.19620519
Fy1 = 0.0
Fz1 = -2914124.84400512
Mxx1 = 3963732.76208099
Myy1 = -2275104.79420872
Mzz1 = -346781.68192839
prob["pre1.rna_F"] = np.array([Fx1, Fy1, Fz1])
prob["pre1.rna_M"] = np.array([Mxx1, Myy1, Mzz1])

prob["wind2.Uref"] = 70.0
Fx2 = 930198.60063279
Fy2 = 0.0
Fz2 = -2883106.12368949
Mxx2 = -1683669.22411597
Myy2 = -2522475.34625363
Mzz2 = 147301.97023764
prob["pre2.rna_F"] = np.array([Fx2, Fy2, Fz2])
prob["pre2.rna_M"] = np.array([Mxx2, Myy2, Mzz2])

prob.model.approx_totals()
if opt_flag:
    prob.run_driver()
else:
    prob.run_model()
save_data("tower_example", prob)

z = 0.5 * (prob["z_full"][:-1] + prob["z_full"][1:])
print("zs =", prob["z_full"])
print("ds =", prob["d_full"])
print("ts =", prob["t_full"])
print("mass (kg) =", prob["tower_mass"])
print("cg (m) =", prob["tower_center_of_mass"])
print("d:t constraint =", prob["constr_d_to_t"])
print("taper ratio constraint =", prob["constr_taper"])
print("\nwind: ", prob["wind1.Uref"])
print("freq (Hz) =", prob["post1.structural_frequencies"])
print("Fore-aft mode shapes =", prob["post1.fore_aft_modes"])
print("Side-side mode shapes =", prob["post1.side_side_modes"])
print("top_deflection1 (m) =", prob["post1.top_deflection"])
print("Tower base forces1 (N) =", prob["tower1.base_F"])
print("Tower base moments1 (Nm) =", prob["tower1.base_M"])
print("stress1 =", prob["post1.stress"])
print("GL buckling =", prob["post1.global_buckling"])
print("Shell buckling =", prob["post1.shell_buckling"])
print("\nwind: ", prob["wind2.Uref"])
print("freq (Hz) =", prob["post2.structural_frequencies"])
print("Fore-aft mode shapes =", prob["post2.fore_aft_modes"])
print("Side-side mode shapes =", prob["post2.side_side_modes"])
print("top_deflection2 (m) =", prob["post2.top_deflection"])
print("Tower base forces2 (N) =", prob["tower2.base_F"])
print("Tower base moments2 (Nm) =", prob["tower2.base_M"])
print("stress2 =", prob["post2.stress"])
print("GL buckling =", prob["post2.global_buckling"])
print("Shell buckling =", prob["post2.shell_buckling"])

### Code versions
- Python 3.7.9
- Windows 10 with Anaconda

**Comment by pollinico** [comment]
Probably the example available online was outdated. I managed to move on from this issue in this way:  
`modeling_options = {}    `
`modeling_options["flags"] = {}     `
`modeling_options["materials"] = {}   `
`modeling_options["WISDEM"] = {}   `
`modeling_options["WISDEM"]["TowerSE"] = {}   `
`modeling_options["WISDEM"]["TowerSE"]["buckling_length"] = 30.0   `
`modeling_options["flags"]["monopile"] = False `

I.e. by adding the field ["WISDEM"].

**Comment by gbarter** [comment]
Thank you for pointing this out.

@johnjasa This looks like a docs building error.
The docs pointing to the [master](https://wisdem.readthedocs.io/en/master/examples/tower_mono/tutorial.html) branch are correct.  The docs pointing to the "[latest](https://wisdem.readthedocs.io/en/latest/examples/tower_mono/tutorial.html)" branch (develop?) are not.  The "latest" seems to be the default if you just go to http://wisdem.readthedocs.io/

The code in both the master and develop branches are both correct and consistent though:
https://github.com/WISDEM/WISDEM/blob/master/examples/05_tower_monopile/monopile_direct.py
https://github.com/WISDEM/WISDEM/blob/develop/examples/05_tower_monopile/monopile_direct.py

**Comment by johnjasa** [comment]
Thanks for this, Garrett. I've fixed the doc build on latest and it now shows the correct syntax.
