### ISSUE TITLE
Dialogue about ORBIT

### ISSUE THREAD

**Issue by skannerdarkly** [WISDEM/WISDEM#237]
## Description
Is anyone currently working on ORBIT? A few issues have popped up for me. Is this the right place to post them?

### Current behavior
foo

### Expected behavior
bar

**Comment by gbarter** [comment]
Hello,

Yes, ORBIT is under considerable active development.  Any issues you have with the ORBIT model are best directed at its own Github repo and Issues page: https://github.com/WISDEM/ORBIT
I am tagging the key developers (@JakeNunemaker @Matt-Shields) as a heads up.

If you have issues with the connection between WISDEM & ORBIT, those would be appropriate to raise here.

Best,
Garrett
