### ISSUE TITLE
WISDEM GUI not updating when new YAML file is selected

### ISSUE THREAD

**Issue by mayankchetan** [WISDEM/WISDEM#244]
## Description
_Describe the bug here_
Selecting the wrong YAML file type in the GUI and correcting it does not update the GUI.

### Steps to reproduce issue
_Please provide a minimum working example (MWE) if possible_

1. Run the WISDEM GUI
2. Select the wrong YAML file in any of the three options
3. Replace it with the correct YAML file type

### Current behavior
The GUI does not update when the input YAML file is changed.

### Expected behavior
The GUI updates when a new YAML file is selected or does not allow the user to select the wrong YAML file.

### Code versions
_List versions only if relevant_
- Python 3.7.9
- WISDEM 3.2.0 (master branch)

**Comment by gbarter** [comment]
Resolved with new GUI code
