### ISSUE TITLE
Cannot run example 03_Blade with analysis_options_struct.yaml analysis file via the GUI

### ISSUE THREAD

**Issue by abhartman** [WISDEM/WISDEM#245]
## Description
Using the example files packaged with the program, example 03_Blade cannot be run through the GUI using the analysis_options_struct.yaml file.

### Steps to reproduce issue

1. Open Anaconda Navigator
2. Use the button to open the WISDEM_v320_release terminal
3. Type WISDEM and press enter in the terminal
4. Browse to and select blade.yaml in the 03_Blade example directory.
5. Browse to and select modeling_options.yaml in the same directory.
6. Browse to and select analysis_options_struct.yaml in the same directory.
7. Click Run WISDEM button
8. Click OK to run WISDEM

### Current behavior
WISDEM terminal gives the message "Design variables are set to be optimized or studied, but no driver is selected. Please enable a driver.

### Expected behavior
WISDEM terminal should output results of the optimization.

### Code versions
WISDEM v320

**Comment by ptrbortolotti** [comment]
Hi, thanks for opening this issue. Are you sure to be on the master branch? How difficult would it be to move to develop? I've recently maintained that example and I know it works there. If this is not an easy pathway forward, I can debug master
Let me know.
Regards,
Pietro

**Comment by abhartman** [comment]
Pietro,

I'm not sure if I'm on the master or develop branch.  This is mostly my first time using github, and I'm not a developer (mechanical engineer by training).  I'm using WISDEM as part of a graduate class, so I'm stuck on the version that the professor is using in class.

I did notice that if I run the 02_reference_trubines example, I WAS able to then go back and run the 03_blade example with analysis_options_struct.yaml and get a result.

I'm not sure why that happened, though.

-Adam

**Comment by ptrbortolotti** [comment]
Hi Adam,
the error you see is generated when some design variables are set to true in the analysis options yaml, but neither optimization nor design of experiments flags are True.
The analysis option yaml that runs the blade structural optimization however should have the optimization flag set to true, see here
https://github.com/WISDEM/WISDEM/blob/5ff6f70e29e53179668d7441d8da2378ef7791f0/examples/03_blade/analysis_options_struct.yaml#L44
so I'm not sure why you get the error that you report. Please check your analysis options yaml and see what flags are on and what are off
Good luck!
Pietro

**Comment by abhartman** [comment]
Pietro,

My version of analysis_options_struct.yaml looks noticeably different from what is linked there.

This is what was in the file on my machine:
`constraints:
  blade:
    chord:
      flag: false
      max: 4.75
    frequency:
      edge_3P: false
      flap_3P: false
    match_L_D:
      filename: /path2file.txt
      flag_D: false
      flag_L: false
    match_cl_cd:
      filename: /path2file.txt
      flag_cd: false
      flag_cl: false
    moment_coefficient:
      flag: false
      max: 0.15
      min: 0.13
    rail_transport:
      4_axle: false
      8_axle: false
      flag: false
    stall:
      flag: false
      margin: 0.05233
    strains_spar_cap_ps:
      flag: false
      max: 0.0035
    strains_spar_cap_ss:
      flag: false
      max: 0.0035
    tip_deflection:
      flag: false
      margin: 1.134
  drivetrain:
    access:
      flag: false
      lower_bound: 2.0
    bedplate:
      flag: false
    ecc:
      flag: false
    height:
      flag: false
    hss:
      flag: false
    length:
      flag: false
    lss:
      flag: false
    mb1:
      flag: false
    mb2:
      flag: false
  hub:
    hub_diameter:
      flag: false
  tower:
    constr_d_to_t:
      flag: false
    constr_taper:
      flag: false
    frequency:
      flag: false
    frequency_1:
      flag: false
      lower_bound: 0.13
      upper_bound: 0.4
    global_buckling:
      flag: false
    height_constraint:
      flag: false
      lower_bound: 0.01
      upper_bound: 0.01
    shell_buckling:
      flag: false
    slope:
      flag: false
    stress:
      flag: false
design_variables:
  blade:
    aero_shape:
      af_positions:
        af_start: 4
        flag: false
      chord:
        flag: false
        max_gain: 1.3
        min_gain: 0.7
        n_opt: 8
      twist:
        flag: false
        inverse: false
        lower_bound:
        - 0.3490658503988659
        - 0.08726646259971647
        - 0.08726646259971647
        - 0.0
        - -0.08726646259971647
        - -0.08726646259971647
        - -0.08726646259971647
        - -0.08726646259971647
        n_opt: 8
        upper_bound:
        - 0.4363323129985824
        - 0.3490658503988659
        - 0.3490658503988659
        - 0.2617993877991494
        - 0.2617993877991494
        - 0.17453292519943295
        - 0.17453292519943295
        - 0.08726646259971647
    structure:
      spar_cap_ps:
        equal_to_suction: false
        flag: false
        max_gain: 1.3
        min_gain: 0.7
        n_opt: 8
      spar_cap_ss:
        flag: false
        max_gain: 1.3
        min_gain: 0.7
        n_opt: 8
      te_ps:
        flag: false
        max_gain: 2.0
        min_gain: 0.2
        n_opt: 8
      te_ss:
        flag: false
        max_gain: 2.0
        min_gain: 0.2
        n_opt: 8
  control:
    tsr:
      flag: false
      maximum: 13
      minimum: 9
  drivetrain:
    bedplate_wall_thickness:
      flag: false
      lower_bound: 0.004
      upper_bound: 0.5
    distance_hub_mb:
      flag: false
      lower_bound: 0.1
      upper_bound: 5.0
    distance_mb_mb:
      flag: false
      lower_bound: 0.1
      upper_bound: 5.0
    distance_tt_hub:
      flag: false
      lower_bound: 1.0
      upper_bound: 10.0
    gear_ratio:
      flag: false
      lower_bound: 50.0
      upper_bound: 150.0
    generator_length:
      flag: false
      lower_bound: 1.0
      upper_bound: 5.0
    hss_diameter:
      flag: false
      lower_bound: 1.0
      upper_bound: 6.0
    hss_wall_thickness:
      flag: false
      lower_bound: 0.004
      upper_bound: 0.5
    lss_diameter:
      flag: false
      lower_bound: 1.0
      upper_bound: 6.0
    lss_wall_thickness:
      flag: false
      lower_bound: 0.004
      upper_bound: 0.5
    nose_diameter:
      flag: false
      lower_bound: 1.0
      upper_bound: 6.0
    nose_wall_thickness:
      flag: false
      lower_bound: 0.004
      upper_bound: 0.5
    overhang:
      flag: false
      lower_bound: 5.0
      upper_bound: 20.0
    uptilt:
      flag: false
      lower_bound: 0.0
      upper_bound: 0.5235987756
  hub:
    cone:
      flag: false
      lower_bound: 0.0
      upper_bound: 0.5235987756
    hub_diameter:
      flag: false
      lower_bound: 3.0
      upper_bound: 15.0
  rotor_diameter:
    flag: false
    maximum: 240
    minimum: 190
  tower:
    layer_thickness:
      flag: false
      lower_bound: 4e-3
      upper_bound: 2e-1
    outer_diameter:
      flag: false
      lower_bound: 3.87
      upper_bound: 10.0
driver:
  form: forward
  max_iter: 5
  solver: SLSQP
  step_size: 0.001
  tol: 0.001
general:
  fname_output: blade_out
  folder_output: outputs_struct
merit_figure: blade_mass
recorder:
  file_name: log_opt.sql
  flag: false
`

**Comment by ptrbortolotti** [comment]
You might want to redownload/reclone wisdem and recompile your anaconda environment, it's probably your best shot

**Comment by gbarter** [comment]
I can confirm that on the master branch I can run this example from the GUI or command line.  It does sound as though maybe some file got edited.  From the Anaconda prompt somewhere in the WISDEM directory, you can type `git pull` and then `git status` and you should see if any files differ from the repository (it should also show you your branch).

**Comment by abhartman** [comment]
> I can confirm that on the master branch I can run this example from the GUI or command line. It does sound as though maybe some file got edited. From the Anaconda prompt somewhere in the WISDEM directory, you can type `git pull` and then `git status` and you should see if any files differ from the repository (it should also show you your branch).

@gbarter I appreciate this advice.  I've tried to follow your steps, but it doesn't seem to be working.  I haven't ever done things with github before, though I did get Anaconda and WISDEM installed through the instructions on the WISDEM project page.  Whenever I try "git pull" I get the error "'git' is not recognized as an internal or external command, operable program or batch file."

![image](https://user-images.githubusercontent.com/28583314/110581065-75849000-812f-11eb-8797-6754244d8131.png)

I apologize for my ignorance in how to conduct this obviously simple fix.  Can you give any further advice?

Thanks,
Adam

**Comment by gbarter** [comment]
We are quite interested in seeing WISDEM succeed in the academic setting, so I am happy to engage more with you, or the class as a whole, if necessary.

For now, you can use `conda env list` to see the names of the environments you have created.  You can also `conda install git` into any environment so that those git-commands are available to you.

If you need more help via screen sharing, you can reach out to us using the information on https://www.nrel.gov/wind/staff.html
