### ISSUE TITLE
tests for wisdem assemblies

### ISSUE THREAD

**Issue by dykesk** [WISDEM/WISDEM#27]
add tests for wisdem assemblies

**Comment by kilojoules** [comment]
I added a test for the lcoe assembly in 000cbd1c2304f63764594359f52b28fba784ef76 and 98fd93bde0d638c1801acca483586011c15d9f82 and added a test for the turbine assembly in b463d71b06a8940748a514d3414adf43074f0d32

**Comment by dykesk** [comment]
we should add tests for the lcoe_csm assemblies as well

**Comment by dykesk** [comment]
Wait on full test suite until 1.0 since substantial changes are coming
