### ISSUE TITLE
WISDEM  GUI example erro[nrel5mw.ymal]

### ISSUE THREAD

**Issue by SeongwooCheon** [WISDEM/WISDEM#271]
## Description
_Describe the bug here_

Anaconda prompt
: wisdem nrel5mw.yaml modeling_options.yaml analysis_options.yaml

error message :
UnicodeDecodeError: 'cp949' codec can't decode byte 0xe2 in position 5507: illegal multibyte sequence

### Steps to reproduce issue
_Please provide a minimum working example (MWE) if possible_

1. Run the WISDEM GUI or Anaconda prompt
2. command "wisdem nrel5mw.yaml modeling_options.yaml analysis_options.yaml"
3. error message "UnicodeDecodeError: 'cp949' codec can't decode byte 0xe2 in position 5507: illegal multibyte sequence"

### Code versions
_List versions only if relevant_
- Python 3.7.10
- WISDEM

**Comment by gbarter** [comment]
I cannot recreate this error, but with a Google search, I think I know how to fix it.  Can you tell me a little more about your environment?  Windows / Mac / Linux?  Are you using the WISDEM master or develop branches?

**Comment by SeongwooCheon** [comment]
Dear  Garrett Barter

Thank you for your response

environment : Window
WISDEM : develop branch

Best regards

Seongwoo Cheon

--------------------------------------------------------------------

Seongwoo Cheon

M.S. Student

Computational Aeroelasticity and Structure Lab. (CAeSL)

Department of Aerospace Engineering

College of Engineering, Jeonbuk National University

567 Baekje-daero, Jeonju-si, Jeollabuk-do 54896, Republic of Korea


Mail) ***@***.***

Web) https://sites.google.com/view/caesl/home

--------------------------------------------------------------------


2021년 4월 29일 (목) 오후 10:22, Garrett Barter ***@***.***>님이 작성:

**Comment by SeongwooCheon** [comment]
Thank you for your response.
for git pull, sync up with develop branch, what should I do? (for example,
git bash code)
If just typing code, can you tell me the code I need to type?

Best regards.
Seongwoo Cheon

--------------------------------------------------------------------

Seongwoo Cheon

M.S. Student

Computational Aeroelasticity and Structure Lab. (CAeSL)

Department of Aerospace Engineering

College of Engineering, Jeonbuk National University

567 Baekje-daero, Jeonju-si, Jeollabuk-do 54896, Republic of Korea


Mail) ***@***.***

Web) https://sites.google.com/view/caesl/home

--------------------------------------------------------------------


2021년 4월 30일 (금) 오후 11:02, Garrett Barter ***@***.***>님이 작성:

**Comment by gbarter** [comment]
If you are in the Anaconda prompt and in the environment and directory where you installed WISDEM, something like:
```
conda activate wisdem-env
cd WISDEM
```
Then all you should need to do is:
```
git checkout develop
git pull
python setup.py develop
```
