### ISSUE TITLE
analysis_options : add design variables and constraints

### ISSUE THREAD

**Issue by SeongwooCheon** [WISDEM/WISDEM#283]
Hi

According to example folder 03_blade analysis_options.yaml, the structural design variables are only spar caps thickness and trailing edge reinforcement thickness.

but, I want to add other design variables and constraints like spar location, web thickness[design variable], tip speed ratio[constraint] etc.

What should I do?

thank you

**Comment by ptrbortolotti** [comment]
Hello SeongwooCheon,
thank you for using WISDEM.
What you ask is possible, but somewhat tricky to achieve. It will certainly require you to become familiar with the source code of WISDEM. I list below where you would need to work on:
* The class ParametrizeBladeStruct (https://github.com/WISDEM/WISDEM/blob/f85ed959c0b888468e4ad2064c5962c30d189ebe/wisdem/rotorse/parametrize_rotor.py#L96) parametrizes the design variables of the blade structure. You can add here new logic for the thickness of the shear webs and locations of the various elements
* The class Blade (https://github.com/WISDEM/WISDEM/blob/f85ed959c0b888468e4ad2064c5962c30d189ebe/wisdem/glue_code/gc_WT_DataStruc.py#L539) defines the independent variable components (the inputs that can be optimized), you'd need to add your new DVs here
* the new DVs must then be passed to the openmdao driver here https://github.com/WISDEM/WISDEM/blob/f85ed959c0b888468e4ad2064c5962c30d189ebe/wisdem/glue_code/gc_PoseOptimization.py#L454, and if you run the code in parallel mode with MPI, here https://github.com/WISDEM/WISDEM/blob/f85ed959c0b888468e4ad2064c5962c30d189ebe/wisdem/glue_code/gc_PoseOptimization.py#L39
* tip speed ratio is an input of WISDEM, not an output, and therefore cannot be set as a constrain. The good news is that TSR is already a possible DV, so you can optimize it and define its bounds without changing anything but your input file analysis_options.yaml. You can see how to activate it in the analysis_schema.yaml https://github.com/WISDEM/WISDEM/blob/f85ed959c0b888468e4ad2064c5962c30d189ebe/wisdem/inputs/analysis_schema.yaml#L228
* Making TSR an output and not an input would require a different logic in this function https://github.com/WISDEM/WISDEM/blob/f85ed959c0b888468e4ad2064c5962c30d189ebe/wisdem/rotorse/rotor_power.py#L134

Good luck!
Best regards,
Pietro

**Comment by gbarter** [comment]
@SeongwooCheon Pietro gave you a comprehensive reply to implement the capability you requested.  Maybe it is worth stating that web thickness and spar location are not currently implemented as design variables and it will be some time before we can make that happen.  If you are feeling intrepid, you can follow Pietro's steps and try to make those changes yourself.

The TSR ratio is implemented as a variable and design variable.  Perhaps you will have to explain more what additional feature you are looking for there.

**Comment by SeongwooCheon** [comment]
> Hello SeongwooCheon,
> thank you for using WISDEM.
> What you ask is possible, but somewhat tricky to achieve. It will certainly require you to become familiar with the source code of WISDEM. I list below where you would need to work on:
> 
> * The class ParametrizeBladeStruct (https://github.com/WISDEM/WISDEM/blob/f85ed959c0b888468e4ad2064c5962c30d189ebe/wisdem/rotorse/parametrize_rotor.py#L96
>   ) parametrizes the design variables of the blade structure. You can add here new logic for the thickness of the shear webs and locations of the various elements
> * The class Blade (https://github.com/WISDEM/WISDEM/blob/f85ed959c0b888468e4ad2064c5962c30d189ebe/wisdem/glue_code/gc_WT_DataStruc.py#L539
>   ) defines the independent variable components (the inputs that can be optimized), you'd need to add your new DVs here
> * the new DVs must then be passed to the openmdao driver here https://github.com/WISDEM/WISDEM/blob/f85ed959c0b888468e4ad2064c5962c30d189ebe/wisdem/glue_code/gc_PoseOptimization.py#L454
>   , and if you run the code in parallel mode with MPI, here https://github.com/WISDEM/WISDEM/blob/f85ed959c0b888468e4ad2064c5962c30d189ebe/wisdem/glue_code/gc_PoseOptimization.py#L39
> * tip speed ratio is an input of WISDEM, not an output, and therefore cannot be set as a constrain. The good news is that TSR is already a possible DV, so you can optimize it and define its bounds without changing anything but your input file analysis_options.yaml. You can see how to activate it in the analysis_schema.yaml https://github.com/WISDEM/WISDEM/blob/f85ed959c0b888468e4ad2064c5962c30d189ebe/wisdem/inputs/analysis_schema.yaml#L228
> * Making TSR an output and not an input would require a different logic in this function https://github.com/WISDEM/WISDEM/blob/f85ed959c0b888468e4ad2064c5962c30d189ebe/wisdem/rotorse/rotor_power.py#L134
> 
> Good luck!
> Best regards,
> Pietro

**Comment by SeongwooCheon** [comment]
> Hello SeongwooCheon,
> thank you for using WISDEM.
> What you ask is possible, but somewhat tricky to achieve. It will certainly require you to become familiar with the source code of WISDEM. I list below where you would need to work on:
> 
> * The class ParametrizeBladeStruct (https://github.com/WISDEM/WISDEM/blob/f85ed959c0b888468e4ad2064c5962c30d189ebe/wisdem/rotorse/parametrize_rotor.py#L96
>   ) parametrizes the design variables of the blade structure. You can add here new logic for the thickness of the shear webs and locations of the various elements
> * The class Blade (https://github.com/WISDEM/WISDEM/blob/f85ed959c0b888468e4ad2064c5962c30d189ebe/wisdem/glue_code/gc_WT_DataStruc.py#L539
>   ) defines the independent variable components (the inputs that can be optimized), you'd need to add your new DVs here
> * the new DVs must then be passed to the openmdao driver here https://github.com/WISDEM/WISDEM/blob/f85ed959c0b888468e4ad2064c5962c30d189ebe/wisdem/glue_code/gc_PoseOptimization.py#L454
>   , and if you run the code in parallel mode with MPI, here https://github.com/WISDEM/WISDEM/blob/f85ed959c0b888468e4ad2064c5962c30d189ebe/wisdem/glue_code/gc_PoseOptimization.py#L39
> * tip speed ratio is an input of WISDEM, not an output, and therefore cannot be set as a constrain. The good news is that TSR is already a possible DV, so you can optimize it and define its bounds without changing anything but your input file analysis_options.yaml. You can see how to activate it in the analysis_schema.yaml https://github.com/WISDEM/WISDEM/blob/f85ed959c0b888468e4ad2064c5962c30d189ebe/wisdem/inputs/analysis_schema.yaml#L228
> * Making TSR an output and not an input would require a different logic in this function https://github.com/WISDEM/WISDEM/blob/f85ed959c0b888468e4ad2064c5962c30d189ebe/wisdem/rotorse/rotor_power.py#L134
> 
> Good luck!
> Best regards,
> Pietro
