### ISSUE TITLE
optimization example

### ISSUE THREAD

**Issue by SeongwooCheon** [WISDEM/WISDEM#295]
Hi,
I am studying the wind turbine blade optimization.
I want to solve the blade optimization problem using IEA-15-240-RWT.yaml.

I typed [wisdem IEA-15-240-RWT.yaml modeling_options.yaml analysis_options_struct.yaml] into anaconda prompt.
but, the error occurred like this:
  File "C:\ProgramData\Anaconda3\envs\wisdem-env\Scripts\wisdem-script.py", line 33, in <module>
    sys.exit(load_entry_point('WISDEM', 'console_scripts', 'wisdem')())
  File "c:\users\chsu\wisdem\wisdem\main.py", line 69, in wisdem_cmd
    wt_opt, modeling_options, opt_options = run_wisdem(sys.argv[1], sys.argv[2], sys.argv[3])
  File "c:\users\chsu\wisdem\wisdem\glue_code\runWISDEM.py", line 74, in run_wisdem
    wt_opt = myopt.set_design_variables(wt_opt, wt_init)
  File "c:\users\chsu\wisdem\wisdem\glue_code\gc_PoseOptimization.py", line 563, in set_design_variables
    lower=init_spar_cap_ss_opt[indices_spar_cap_ss] * spar_cap_ss_options["max_decrease"],
UnboundLocalError: local variable 'init_spar_cap_ss_opt' referenced before assignment

what should I do for solving this problem?

**Comment by gbarter** [comment]
The modeling_options file has two fields that label which layers in the geometry yaml file contain the spar caps.  For the IEA_15-240-RWT.yaml file, this is:
https://github.com/WISDEM/WISDEM/blob/master/examples/02_reference_turbines/modeling_options.yaml#L7

I think you are using the `modeling_options.yaml` file from the blade optimization example, which comes from another project and just has case-differences in those spar cap layer labels:
https://github.com/WISDEM/WISDEM/blob/master/examples/03_blade/modeling_options.yaml#L7

You just need to use the correct modeling_options file and what you are after should work.  From the `03_blade` example directory, you would enter:
```wisdem ../02_reference_turbines/IEA-15-240-RWT.yaml ../02_reference_turbines/modeling_options.yaml analysis_options_struct.yaml```
