### ISSUE TITLE
design variable

### ISSUE THREAD

**Issue by SeongwooCheon** [WISDEM/WISDEM#299]
there is a only design variable for spar cap in the Issue https://github.com/WISDEM/WISDEM/issues/283.
then, where is code for te_ss(ps)?

thank you

**Comment by gbarter** [comment]
Hi there.  My apologies that previous answers had assumed that TE reinforcement as a design variable was already coded up and working in WISDEM.  I just gave it a try and it is clearly not.  Let me do some work on my side and get back to you.

**Comment by gbarter** [comment]
Hi Seongwoo,

Thank you for your patience.  TE reinforcement thicknesses on the pressure/suction side are now available as design variables and strains in those layers are available as constraints.  Changes are detailed in #302 .  Let us know if you encounter any problems trying it out.

**Comment by SeongwooCheon** [comment]
in the Anaconda prompt, the command is:


git pull
git checkout develop

is that right?

**Comment by gbarter** [comment]
I would reverse the order of those two commands.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by SeongwooCheon** [comment]
then, Is there any change in adding design variables? : https://github.com/WISDEM/WISDEM/issues/283

**Comment by gbarter** [comment]
No, all should be implemented and ready to go.

**Comment by SeongwooCheon** [comment]
thank you

**Comment by SeongwooCheon** [comment]
> * Is it okay not to modify this part?https://github.com/WISDEM/WISDEM/blob/f85ed959c0b888468e4ad2064c5962c30d189ebe/wisdem/glue_code/gc_PoseOptimization.py#1271

**Comment by gbarter** [comment]
I did all of the code editing. You shouldn't need to change anything.  The examples-03_blade analysis_options files have been updated with TE parameters as design variables and constraints.
https://github.com/WISDEM/WISDEM/blob/develop/examples/03_blade/analysis_options_struct.yaml

**Comment by SeongwooCheon** [comment]
I want to add new design variables such as trailing edge suction(pressure) side filler, leading edge reinforcement etc.
So, I asked above questions.

**Comment by gbarter** [comment]
Sorry for misunderstanding your request.  I thought you were just looking for TE SS/PS reinforcement as a design variable and stress/strain constraint, which have been implemented.  I am not sure if that is what you mean by "TE filler" or not.  I have not implemented LE reinforcement as a design variable or stress/strain constraint.

**Comment by SeongwooCheon** [comment]
I'd like to add this as a design variable.

https://github.com/WISDEM/WISDEM/blob/44e7505f87c71d676599b2b4c4988a53c562b16a/examples/03_blade/BAR0.yaml#L199
https://github.com/WISDEM/WISDEM/blob/44e7505f87c71d676599b2b4c4988a53c562b16a/examples/03_blade/BAR0.yaml#L247

but, When I follow #283, there is an error like this :

C:\ProgramData\anaconda3\envs\wisdem-env\lib\site-packages\openmdao\core\total_jac.py:1559: DerivativesWarning:Design variables [('wt.wt_init.blade.opt_var.spar_cap_ss_opt', inds=[1, 2, 3]), ('wt.wt_init.blade.opt_var.te_ss_opt', inds=[1, 2, 3])] have no impact on the constraints or objective.

**Comment by gbarter** [comment]
Ah, the balsa filler is actually defined there as the region between the spar caps and the TE reinforcement.  By adjusting those two separately, the filler would naturally adjust too.  Given that the balsa filler layer is defined relative to others, it would not be appropriate to have it as an independent variable.

**Comment by SeongwooCheon** [comment]
Isn't it appropriate to set shell skin outer as a design variable as well? : 
https://github.com/WISDEM/WISDEM/blob/44e7505f87c71d676599b2b4c4988a53c562b16a/examples/03_blade/BAR0.yaml#L86

**Comment by gbarter** [comment]
Yes, that is possible.  In all likelihood, the design drivers for blade skin thickness are not captured by WISDEM, such as more complex buckling and fatigue.
