### ISSUE TITLE
WISDEM run error.

### ISSUE THREAD

**Issue by SeongwooCheon** [WISDEM/WISDEM#324]
I tried to optimize IEA-15-240-RWT by increasing the thickness of the layer by 20%. but, this error is occured:

>  File "c:\users\chsu\wisdem\wisdem\rotorse\rotor_elasticity.py", line 674, in compute + " %."
> ValueError: Error in the definition of material LE_reinf. It cannot fit in the section number 27 at span location 93.32977968319422 %.
>  ValueError: 'wt.rotorse.re.precomp' <class RunPreComp>: Error calling compute(), Error in the definition of material LE_reinf. It cannot fit in the section number 27 at span location 93.32977968319422 %.
> 

How can I solve the error?

thank you

**Comment by ptrbortolotti** [comment]
Hi,
the width of the layer is too large and the layer doesn't fit within the section. So try reducing the width in the input yaml file. Alternatively, you can taper the thickness of the reinforcement layer to 0., as blade usually don't need that reinforcement all the way to the tip.
Best regards,
Pietro Bortolotti
