### ISSUE TITLE
RuntimeError : chord distribution

### ISSUE THREAD

**Issue by SeongwooCheon** [WISDEM/WISDEM#328]
By increasing the chord length, we would like to optimize the distribution of wind turbine codes with two blades.

when I increase the chord length more than 1.4 times, the error is occurred like this:
RuntimeError: 'wt.drivese.lss' <class Hub_Rotor_LSS_Frame>: Error calling compute(), Frame3DD did not exit gracefully

How can I solve the problem?

**Comment by SeongwooCheon** [comment]
I turn off all modules except for RotorSE like this:

>     RotorSE:
>         flag: True
>     DriveSE:
>         flag: False
>     TowerSE:             # Options of TowerSE module
>         flag: False
>     BOS:
>         flag: False

but like this.
KeyError: '<model> <class WindPark>: Variable "tcons.max_allowable_td_ratio" not found.'

**Comment by gbarter** [comment]
Sounds like you have some constraints activated that depend on those modules you deactivated- specifically blade tip-tower clearance.

**Comment by SeongwooCheon** [comment]
I command like this:
widem BAR0.yaml modeling_options.yaml analysis_options_no_opt.yaml

then it is not related with constraints?

**Comment by gbarter** [comment]
You would have to paste here the full text of the error message and the `analysis_options_no_opt.yaml` file.
