### ISSUE TITLE
Error while installing WISDEM

### ISSUE THREAD

**Issue by badeshiben** [WISDEM/WISDEM#329]
## Description
Following the readme installation instructions on a mac. The process yields errors and I can't run the example cases.

### Steps to reproduce issue
Followed readme install instructions for mac.

### Current behavior
code output when I run _python setup.py develop_
```
running develop
running build_scripts
running egg_info
running build_src
build_src
building extension "wisdem.ccblade._bem" sources
f2py options: []
  adding 'build/src.macosx-10.9-x86_64-3.7/build/src.macosx-10.9-x86_64-3.7/wisdem/ccblade/fortranobject.c' to sources.
  adding 'build/src.macosx-10.9-x86_64-3.7/build/src.macosx-10.9-x86_64-3.7/wisdem/ccblade' to include_dirs.
building extension "wisdem.pyframe3dd._pyframe3dd" sources
building extension "wisdem.rotorse._precomp" sources
f2py options: []
  adding 'build/src.macosx-10.9-x86_64-3.7/build/src.macosx-10.9-x86_64-3.7/wisdem/rotorse/fortranobject.c' to sources.
  adding 'build/src.macosx-10.9-x86_64-3.7/build/src.macosx-10.9-x86_64-3.7/wisdem/rotorse' to include_dirs.
  adding 'build/src.macosx-10.9-x86_64-3.7/wisdem/rotorse/_precomp-f2pywrappers2.f90' to sources.
build_src: building npy-pkg config files
writing WISDEM.egg-info/PKG-INFO
writing dependency_links to WISDEM.egg-info/dependency_links.txt
writing entry points to WISDEM.egg-info/entry_points.txt
writing requirements to WISDEM.egg-info/requires.txt
writing top-level names to WISDEM.egg-info/top_level.txt
reading manifest file 'WISDEM.egg-info/SOURCES.txt'
writing manifest file 'WISDEM.egg-info/SOURCES.txt'
running build_ext
customize UnixCCompiler
customize UnixCCompiler using build_ext
get_default_fcompiler: matching types: '['gnu95', 'nag', 'absoft', 'ibm', 'intel', 'gnu', 'g95', 'pg']'
customize Gnu95FCompiler
Found executable /opt/anaconda3/envs/wisdem-env/bin/x86_64-apple-darwin13.4.0-gfortran
Found executable /opt/anaconda3/envs/wisdem-env/bin/x86_64-apple-darwin13.4.0-ld
Found executable /opt/anaconda3/envs/wisdem-env/bin/x86_64-apple-darwin13.4.0-ar
Found executable /opt/anaconda3/envs/wisdem-env/bin/x86_64-apple-darwin13.4.0-ranlib
customize Gnu95FCompiler
customize Gnu95FCompiler using build_ext
building 'wisdem.ccblade._bem' extension
compiling C sources
C compiler: x86_64-apple-darwin13.4.0-clang -fno-strict-aliasing -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O3 -Wall -Wstrict-prototypes -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O3 -pipe -fdebug-prefix-map=${SRC_DIR}=/usr/local/src/conda/${PKG_NAME}-${PKG_VERSION} -fdebug-prefix-map=/opt/anaconda3=/usr/local/src/conda-prefix -flto -Wl,-export_dynamic -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O3 -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -isystem /opt/anaconda3/envs/wisdem-env/include -D_FORTIFY_SOURCE=2 -isystem /opt/anaconda3/envs/wisdem-env/include

compile options: '-Ibuild/src.macosx-10.9-x86_64-3.7/build/src.macosx-10.9-x86_64-3.7/wisdem/ccblade -I/opt/anaconda3/lib/python3.7/site-packages/numpy/core/include -I/opt/anaconda3/include/python3.7m -I/opt/anaconda3/include/python3.7m -c'
extra options: '-O2 -fPIC'
compiling Fortran sources
Fortran f77 compiler: /opt/anaconda3/envs/wisdem-env/bin/x86_64-apple-darwin13.4.0-gfortran -Wall -g -ffixed-form -fno-second-underscore -fPIC -march=core2 -mtune=haswell -ftree-vectorize -fPIC -fstack-protector -O2 -pipe -isystem /opt/anaconda3/envs/wisdem-env/include -O3 -funroll-loops
Fortran f90 compiler: /opt/anaconda3/envs/wisdem-env/bin/x86_64-apple-darwin13.4.0-gfortran -Wall -g -fno-second-underscore -fPIC -march=core2 -mtune=haswell -ftree-vectorize -fPIC -fstack-protector -O2 -pipe -isystem /opt/anaconda3/envs/wisdem-env/include -O3 -funroll-loops
Fortran fix compiler: /opt/anaconda3/envs/wisdem-env/bin/x86_64-apple-darwin13.4.0-gfortran -Wall -g -ffixed-form -fno-second-underscore -Wall -g -fno-second-underscore -fPIC -march=core2 -mtune=haswell -ftree-vectorize -fPIC -fstack-protector -O2 -pipe -isystem /opt/anaconda3/envs/wisdem-env/include -O3 -funroll-loops
compile options: '-Ibuild/src.macosx-10.9-x86_64-3.7/build/src.macosx-10.9-x86_64-3.7/wisdem/ccblade -I/opt/anaconda3/lib/python3.7/site-packages/numpy/core/include -I/opt/anaconda3/include/python3.7m -I/opt/anaconda3/include/python3.7m -c'
x86_64-apple-darwin13.4.0-gfortran:f90: wisdem/ccblade/src/bem.f90
f951: Error: bad value (‘core2 -mtune=haswell -ftree-vectorize -fPIC -fstack-protector -O2 -pipe -isystem /opt/anaconda3/envs/wisdem-env/include’) for ‘-march=’ switch
f951: note: valid arguments to ‘-march=’ switch are: nocona core2 nehalem corei7 westmere sandybridge corei7-avx ivybridge core-avx-i haswell core-avx2 broadwell skylake skylake-avx512 cannonlake icelake-client icelake-server cascadelake bonnell atom silvermont slm goldmont goldmont-plus tremont knl knm x86-64 eden-x2 nano nano-1000 nano-2000 nano-3000 nano-x2 eden-x4 nano-x4 k8 k8-sse3 opteron opteron-sse3 athlon64 athlon64-sse3 athlon-fx amdfam10 barcelona bdver1 bdver2 bdver3 bdver4 znver1 znver2 btver1 btver2 native
error: Command "/opt/anaconda3/envs/wisdem-env/bin/x86_64-apple-darwin13.4.0-gfortran -Wall -g -fno-second-underscore -fPIC -march=core2 -mtune=haswell -ftree-vectorize -fPIC -fstack-protector -O2 -pipe -isystem /opt/anaconda3/envs/wisdem-env/include -O3 -funroll-loops -Ibuild/src.macosx-10.9-x86_64-3.7/build/src.macosx-10.9-x86_64-3.7/wisdem/ccblade -I/opt/anaconda3/lib/python3.7/site-packages/numpy/core/include -I/opt/anaconda3/include/python3.7m -I/opt/anaconda3/include/python3.7m -c -c wisdem/ccblade/src/bem.f90 -o build/temp.macosx-10.9-x86_64-3.7/wisdem/ccblade/src/bem.o" failed with exit status 1
(wisdem-env) banderso2-34567s:WISDEM banderso2$ conda install compilers
Collecting package metadata (current_repodata.json): failed

CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://conda.anaconda.org/conda-forge/osx-64/current_repodata.json>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
'https://conda.anaconda.org/conda-forge/osx-64'


(wisdem-env) banderso2-34567s:WISDEM banderso2$ conda install compilers
Collecting package metadata (current_repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.8.3
  latest version: 4.10.3

Please update conda by running

    $ conda update -n base conda



All requested packages already installed.

(wisdem-env) banderso2-34567s:WISDEM banderso2$ pip install simpy marmot-agents nlopt
Requirement already satisfied: simpy in /opt/anaconda3/lib/python3.7/site-packages (4.0.1)
Requirement already satisfied: marmot-agents in /opt/anaconda3/lib/python3.7/site-packages (0.2.5)
Requirement already satisfied: nlopt in /opt/anaconda3/lib/python3.7/site-packages (2.7.0)
Requirement already satisfied: numpy in /opt/anaconda3/lib/python3.7/site-packages (from marmot-agents) (1.16.2)
```

### Expected behavior
no errors

### Code versions
_List versions only if relevant_
- Python 3.7.6
- Conda 4.8.3

**Comment by johnjasa** [comment]
Hey Ben, thanks for the great issue info. I've seen this sometimes when running conda commands from the NREL VPN. Could you try disconnecting from the VPN and rerunning these commands?

**Comment by badeshiben** [comment]
Hi John,

I was actually having issues while connected to the vpn as well, so I did it disconnected. But, I’m wondering if I ran a couple commands before disconnecting, so I’m trying again…I also updated conda…not sure if that would have an effect…I’ll keep you posted.

Thanks,

-Ben


From: John Jasa ***@***.***>
Date: Tuesday, November 2, 2021 at 3:28 PM
To: WISDEM/WISDEM ***@***.***>
Cc: Anderson, Benjamin ***@***.***>, Author ***@***.***>
Subject: Re: [WISDEM/WISDEM] Error while installing WISDEM (Issue #329)

CAUTION: This email originated from outside of NREL. Do not click links or open attachments unless you recognize the sender and know the content is safe.

Hey Ben, thanks for the great issue info. I've seen this sometimes when running conda commands from the NREL VPN. Could you try disconnecting from the VPN and rerunning these commands?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FWISDEM%2FWISDEM%2Fissues%2F329%23issuecomment-958180695&data=04%7C01%7CBenjamin.Anderson%40nrel.gov%7Cc30590ab2651424add2f08d99e47a764%7Ca0f29d7e28cd4f5484427885aee7c080%7C0%7C0%7C637714852855915165%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=HomFzT1vNhpsIDRYUkrN0yaG6s%2B8UIeIsExUSTSqxF4%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAI465NUHTCM4VDJRYPBU7OLUKBQXHANCNFSM5HHOH6XA&data=04%7C01%7CBenjamin.Anderson%40nrel.gov%7Cc30590ab2651424add2f08d99e47a764%7Ca0f29d7e28cd4f5484427885aee7c080%7C0%7C0%7C637714852855925121%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=ln41iGnQKGV3qcorDI2HZ%2B0P7yGOBcu%2BCeZu%2B18HhyA%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7CBenjamin.Anderson%40nrel.gov%7Cc30590ab2651424add2f08d99e47a764%7Ca0f29d7e28cd4f5484427885aee7c080%7C0%7C0%7C637714852855925121%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=jbwp5IVy8sfBKHngjDa8w0SypwSS%2BvM7NfkdJdNkfn0%3D&reserved=0> or Android<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7CBenjamin.Anderson%40nrel.gov%7Cc30590ab2651424add2f08d99e47a764%7Ca0f29d7e28cd4f5484427885aee7c080%7C0%7C0%7C637714852855935077%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=pqDdUmS0EaAo4EKt2j8raDp4us4vZBi1oDkCDtHjnnY%3D&reserved=0>.

**Comment by gbarter** [comment]
Try:
`conda config --set ssl_verify no`

**Comment by badeshiben** [comment]
So, I reran the install instructions without the VPN connection, and with an updated conda. I didn’t notice any error messages during the install, but do get one error when running  python test_all.py:



======================================================= ERRORS =======================================================

____________________ ERROR collecting wisdem/test/test_optimization_drivers/test_nlopt_driver.py _____________________

ImportError while importing test module '/Users/banderso2/Tools/WISDEM/wisdem/test/test_optimization_drivers/test_nlopt_driver.py'.

Hint: make sure your test modules/packages have valid Python names.

Traceback:

/opt/anaconda3/envs/wisdem-env/lib/python3.7/importlib/__init__.py:127: in import_module

    return _bootstrap._gcd_import(name[level:], package, level)

../wisdem/test/test_optimization_drivers/test_nlopt_driver.py:14: in <module>

    from wisdem.optimization_drivers.nlopt_driver import NLoptDriver

../wisdem/optimization_drivers/nlopt_driver.py:13: in <module>

    from openmdao.utils.class_util import weak_method_wrapper

E   ImportError: cannot import name 'weak_method_wrapper' from 'openmdao.utils.class_util' (/opt/anaconda3/envs/wisdem-env/lib/python3.7/site-packages/openmdao/utils/class_util.py)

================================================== warnings summary ==================================================

../../../../../opt/anaconda3/envs/wisdem-env/lib/python3.7/site-packages/openmdao/components/exec_comp.py:7

../../../../../opt/anaconda3/envs/wisdem-env/lib/python3.7/site-packages/openmdao/components/exec_comp.py:7

  DeprecationWarning: /opt/anaconda3/envs/wisdem-env/lib/python3.7/site-packages/openmdao/components/exec_comp.py:7

  `np.complex` is a deprecated alias for the builtin `complex`. To silence this warning, use `complex` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.complex128` here.

  Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations



../../../../../opt/anaconda3/envs/wisdem-env/lib/python3.7/site-packages/openmdao/surrogate_models/response_surface.py:7

  DeprecationWarning: /opt/anaconda3/envs/wisdem-env/lib/python3.7/site-packages/openmdao/surrogate_models/response_surface.py:7

  The module numpy.dual is deprecated.  Instead of using dual, use the functions directly from numpy or scipy.



../../../../../opt/anaconda3/envs/wisdem-env/lib/python3.7/site-packages/pyoptsparse/pyOpt_MPI.py:50

  UserWarning: /opt/anaconda3/envs/wisdem-env/lib/python3.7/site-packages/pyoptsparse/pyOpt_MPI.py:50

  mpi4py could not be imported. mpi4py is required to use the parallel gradient analysis and parallel objective analysis for non-gradient based optimizers. Continuing using a dummy MPI module from pyOptSparse.



../../../../../opt/anaconda3/envs/wisdem-env/lib/python3.7/site-packages/pyDOE2/doe_factorial.py:16

  DeprecationWarning: /opt/anaconda3/envs/wisdem-env/lib/python3.7/site-packages/pyDOE2/doe_factorial.py:16

  the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses



../wisdem/rotorse/geometry_tools/geom_tools.py:84

  DeprecationWarning: /Users/banderso2/Tools/WISDEM/wisdem/rotorse/geometry_tools/geom_tools.py:84

  invalid escape sequence \p



../wisdem/rotorse/geometry_tools/geom_tools.py:97

  DeprecationWarning: /Users/banderso2/Tools/WISDEM/wisdem/rotorse/geometry_tools/geom_tools.py:97

  invalid escape sequence \p



../wisdem/rotorse/geometry_tools/geom_tools.py:108

  DeprecationWarning: /Users/banderso2/Tools/WISDEM/wisdem/rotorse/geometry_tools/geom_tools.py:108

  invalid escape sequence \p



../wisdem/rotorse/geometry_tools/geom_tools.py:190

  DeprecationWarning: /Users/banderso2/Tools/WISDEM/wisdem/rotorse/geometry_tools/geom_tools.py:190

  invalid escape sequence \l



-- Docs: https://docs.pytest.org/en/stable/warnings.html

============================================== short test summary info ===============================================

ERROR ../wisdem/test/test_optimization_drivers/test_nlopt_driver.py

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

============================================ 9 warnings, 1 error in 1.83s ============================================


Garrett, at what point in the install should I try that command?

Thanks!


From: Garrett Barter ***@***.***>
Date: Tuesday, November 2, 2021 at 3:36 PM
To: WISDEM/WISDEM ***@***.***>
Cc: Anderson, Benjamin ***@***.***>, Author ***@***.***>
Subject: Re: [WISDEM/WISDEM] Error while installing WISDEM (Issue #329)

CAUTION: This email originated from outside of NREL. Do not click links or open attachments unless you recognize the sender and know the content is safe.

Try:
conda config --set ssl_verify no

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FWISDEM%2FWISDEM%2Fissues%2F329%23issuecomment-958185623&data=04%7C01%7CBenjamin.Anderson%40nrel.gov%7C308e6805d57848f70cf008d99e48d13d%7Ca0f29d7e28cd4f5484427885aee7c080%7C0%7C0%7C637714857850365401%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=uUMd2Rt0wU5Asbu1PN2xkm8KwwbmDRKj2yuyqcEqMMY%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAI465NQZX2TGA5ZAJBMGEE3UKBRWNANCNFSM5HHOH6XA&data=04%7C01%7CBenjamin.Anderson%40nrel.gov%7C308e6805d57848f70cf008d99e48d13d%7Ca0f29d7e28cd4f5484427885aee7c080%7C0%7C0%7C637714857850375359%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=4NITW7ej3uMVn85J1EbcC0XvghT3uS%2BdE7P8oKtevjs%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7CBenjamin.Anderson%40nrel.gov%7C308e6805d57848f70cf008d99e48d13d%7Ca0f29d7e28cd4f5484427885aee7c080%7C0%7C0%7C637714857850385326%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=fPXmmro51ngnUmp2EF8fIhcdoaj9fg7ar8ketwazWoI%3D&reserved=0> or Android<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7CBenjamin.Anderson%40nrel.gov%7C308e6805d57848f70cf008d99e48d13d%7Ca0f29d7e28cd4f5484427885aee7c080%7C0%7C0%7C637714857850385326%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=gJ3PQku8HrTLff%2FkYGBHIfVVWLKqBew50JpgX84kidA%3D&reserved=0>.

**Comment by gbarter** [comment]
That is a one time command so that you can use conda with the vpn.

**Comment by johnjasa** [comment]
Great to hear it went better, @badeshiben! That error you're seeing now can be solved by using the develop branch of WISDEM instead of the master branch. You can do this via `git checkout develop`. We will also work to update the master branch to avoid this issue.

**Comment by badeshiben** [comment]
Thanks, John and Garrett. The test cases all run without errors now!
