### ISSUE TITLE
calculate strain

### ISSUE THREAD

**Issue by SeongwooCheon** [WISDEM/WISDEM#331]
I want to calculate the stress applied the blade.
So, I found the strain formula in the code,  strainU = M1 / EI11 * y - M2 / EI22 * x - F3 / EA

but, I can't understand this equation. why subtract the second and third term from this equation?
and If I want to calculate the stress, just multiply E11?

**Comment by gbarter** [comment]
In composites, it is easier to work in strain because different layers will have different stress but the displacements have to be consistent.

The equation was lifted from this [textbook](https://www.amazon.com/dp/113877507X/ref=cm_sw_em_r_mt_dp_XH90XNBGE6MCV3SWSFBW)

**Comment by SeongwooCheon** [comment]
https://github.com/WISDEM/WISDEM/blob/a4571e71cb5b9869c81790f8abb1bb7fba8fdb02/examples/02_reference_turbines/IEA-15-240-RWT.yaml#L753

**Comment by gbarter** [comment]
Sorry, Seongwoo, I'm not sure what you are asking with regards G_23 or nu_23 and your first question about stress.  Can you restate your full question?
