### ISSUE TITLE
Error installing WISDEM on Windows 10

### ISSUE THREAD

**Issue by amorissettenergica** [WISDEM/WISDEM#335]
## Description
Error during the installation of WISDEM on Windows 10, when running the command : 

pip install -e WISDEM

### Steps to reproduce issue

1. ```
(wisdem-env) C:\Users\amorissette>git clone https://github.com/WISDEM/WISDEM.git
Cloning into 'WISDEM'...
remote: Enumerating objects: 27127, done.
remote: Counting objects: 100% (3880/3880), done.
remote: Compressing objects: 100% (1486/1486), done.
remote: Total 27127 (delta 2889), reused 3292 (delta 2380), pack-reused 23247
Receiving objects: 100% (27127/27127), 75.79 MiB | 16.71 MiB/s, done.
Resolving deltas: 100% (18420/18420), done.
```

2. ```
(wisdem-env) C:\Users\amorissette>cd WISDEM

(wisdem-env) C:\Users\amorissette\WISDEM>git checkout develop
Switched to a new branch 'develop'
Branch 'develop' set up to track remote branch 'develop' from 'origin'.

(wisdem-env) C:\Users\amorissette\WISDEM>
(wisdem-env) C:\Users\amorissette\WISDEM>
```

3. `(wisdem-env) C:\Users\amorissette\WISDEM>pip install -e .`

### Current behavior

```
`Obtaining` file:///C:/Users/amorissette/WISDEM
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\amorissette\Anaconda3\envs\wisdem-env\python.exe' 'C:\Users\amorissette\Anaconda3\envs\wisdem-env\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py' get_requires_for_build_wheel 'C:\Users\AMORIS~1\AppData\Local\Temp\tmpa8n72evn'
       cwd: C:\Users\amorissette\WISDEM
  Complete output (18 lines):
  Traceback (most recent call last):
    File "C:\Users\amorissette\Anaconda3\envs\wisdem-env\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 363, in <module>
      main()
    File "C:\Users\amorissette\Anaconda3\envs\wisdem-env\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 345, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "C:\Users\amorissette\Anaconda3\envs\wisdem-env\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 130, in get_requires_for_build_wheel
      return hook(config_settings)
    File "C:\Users\amorissette\AppData\Local\Temp\pip-build-env-4ghv1i4u\overlay\Lib\site-packages\setuptools\build_meta.py", line 162, in get_requires_for_build_wheel
      return self._get_build_requires(
    File "C:\Users\amorissette\AppData\Local\Temp\pip-build-env-4ghv1i4u\overlay\Lib\site-packages\setuptools\build_meta.py", line 143, in _get_build_requires
      self.run_setup()
    File "C:\Users\amorissette\AppData\Local\Temp\pip-build-env-4ghv1i4u\overlay\Lib\site-packages\setuptools\build_meta.py", line 267, in run_setup
      super(_BuildMetaLegacyBackend,
    File "C:\Users\amorissette\AppData\Local\Temp\pip-build-env-4ghv1i4u\overlay\Lib\site-packages\setuptools\build_meta.py", line 158, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 8, in <module>
      from numpy.distutils.core import Extension, setup
  ModuleNotFoundError: No module named 'numpy'
  ----------------------------------------
WARNING: Discarding file:///C:/Users/amorissette/WISDEM. Command errored out with exit status 1: 'C:\Users\amorissette\Anaconda3\envs\wisdem-env\python.exe' 'C:\Users\amorissette\Anaconda3\envs\wisdem-env\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py' get_requires_for_build_wheel 'C:\Users\AMORIS~1\AppData\Local\Temp\tmpa8n72evn' Check the logs for full command output.
ERROR: Command errored out with exit status 1: 'C:\Users\amorissette\Anaconda3\envs\wisdem-env\python.exe' 'C:\Users\amorissette\Anaconda3\envs\wisdem-env\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py' get_requires_for_build_wheel 'C:\Users\AMORIS~1\AppData\Local\Temp\tmpa8n72evn' Check the logs for full command output.
```

### Code versions
_List versions only if relevant_
- Python 3.8.12
- conda 4.10.3

**Comment by gbarter** [comment]
Hi there,

Thanks for your interest in WISDEM.  We had been experimenting with using `pip` to do the install but encountered similar errors as you.  Sorry for not updating the instructions in the `develop` branch.  Please do `python setup.py develop` and that should run fine.  I will update the README.

Cheers,
Garrett

**Comment by amorissettenergica** [comment]
Hi,

Sorry my post didn't include any kind of presentation. I work for the research center Nergica, located in Gaspé, Canada. We're working on projects involving wind power, solar power and integration of renewables in microgrid . As part of a project on the impacts of climate change on wind energy potential, we are working on a brief economical analysis, so I am interested in using the NREL CSM.

Thank you very much for your very quick answer ! I did python setup.py develop and I didn't encounter any errors. But it seems like the installation is still not completed properly, cause some tests failed. I uninstalled the environnement and deleted the WISDEM file and started all over again with the same result.

Here is the error that appeared at the end of the response after running the `python test_all.py` file : 

`=============================================== short test summary info ===============================================
FAILED ..\wisdem\test\test_ccblade\test_gradients.py::TestGradients::test_dRhub2 - AssertionError:
FAILED ..\wisdem\test\test_examples\test_examples.py::TestExamples::test_all_scripts - AssertionError: '05_tower_mono...
FAILED ..\wisdem\test\test_gluecode\test_drivers.py::TestRegression::test_GA - numpy.linalg.LinAlgError: 'wt.towerse....
FAILED ..\wisdem\test\test_gluecode\test_drivers.py::TestRegression::test_cobyla - sqlite3.OperationalError: table gl...
FAILED ..\wisdem\test\test_gluecode\test_drivers.py::TestRegression::test_ld_slsqp - sqlite3.OperationalError: table ...
FAILED ..\wisdem\test\test_gluecode\test_drivers.py::TestRegression::test_nelder - sqlite3.OperationalError: table gl...
FAILED ..\wisdem\test\test_optimization_drivers\test_nlopt_driver.py::TestNLoptDriver::test_maxtime - ValueError: act...
======================= 7 failed, 1279 passed, 5 skipped, 109729 warnings in 1362.91s (0:22:42) =======================`

**Comment by gbarter** [comment]
Thanks for the context and I hope WISDEM and the NREL CSM can be useful to you.  If those are the only errors you are getting, you are probably still okay to proceed.  It might help us if you described your computing environment (Mac / Windows / Linux), operating system, etc.

For the application you described, it might also be worth investigating a couple of other NREL tools:
https://github.com/nrel/hopp
https://reopt.nrel.gov/

**Comment by amorissettenergica** [comment]
Thank you very much, it is indeed working properly now. Thank you for your support

And thanks I will surely check out the applications you mention !
