### ISSUE TITLE
MPI error & Data save

### ISSUE THREAD

**Issue by SeongwooCheon** [WISDEM/WISDEM#339]
When runing WISDEM, this error is occured initially like this:

> C:\ProgramData\anaconda3\envs\wisdem-env\lib\site-packages\pyoptsparse\pyOpt_MPI.py:50: UserWarning: mpi4py could not be imported. mpi4py is required to use the parallel gradient analysis and parallel objective analysis for non-gradient based optimizers. Continuing using a dummy MPI module from pyOptSparse.
>   warnings.warn(warn)
> 

but, it does not affect to run WISDEM, but I want to fix it.
I can fix it just installing mpi4py like this code? :
`pip install mpi4py`

and

I want to save all Data during the optimization process.
for example, when wisdem runs 5 times iteration, 5 output file is generated.

Where do I need to edit the python code?

thank you

**Comment by gbarter** [comment]
You can try to conda or pip install mpi4py.  It usually requires an underlying MPI installation and there are some challenges on Windows, so our install instructions only include it for Mac or Linux.

For saving the iteration data, WISDEM relies on the OpenMDAO "recorder" functionality.  You can activate it in the analysis_options file:
https://github.com/WISDEM/WISDEM/blob/master/examples/03_blade/analysis_options_aero.yaml#L48-L50

It will help to reference the OpenMDAO recorder docs:
https://openmdao.org/newdocs/versions/latest/features/recording/main.html
