### ISSUE TITLE
CCBlade Install Fails

### ISSUE THREAD

**Issue by evan-gaertner** [WISDEM/WISDEM#34]
I'm stuck trying to get CCBlade to install, all other modules are successfully installed.  Its crashing during the fortran compiling, but appears to be throwing a C error, caused by not being linked to the math library.  It seems odd to me because the pBeam install used gfortran and gcc successfully.  

I hate to bother yall, but is there anything glaring I'm missing?

Thank you!
Evan @ UMass

(openmdao-0.10.3.2) C:\Users\python\WISDEM-WISDEM-947a089\plugins\CCBlade>plugin 
install
installing distribution from current directory as a 'develop' egg
running develop
running build_scripts
running egg_info
running build_src
build_src
building py_modules sources
building extension "_bem" sources
f2py options: []
  adding 'build\src.win32-2.7\fortranobject.c' to sources.
  adding 'build\src.win32-2.7' to include_dirs.
build_src: building npy-pkg config files
writing requirements to src\CCBlade.egg-info\requires.txt
writing src\CCBlade.egg-info\PKG-INFO
writing top-level names to src\CCBlade.egg-info\top_level.txt
writing dependency_links to src\CCBlade.egg-info\dependency_links.txt
writing requirements to src\CCBlade.egg-info\requires.txt
writing src\CCBlade.egg-info\PKG-INFO
writing top-level names to src\CCBlade.egg-info\top_level.txt
writing dependency_links to src\CCBlade.egg-info\dependency_links.txt
reading manifest file 'src\CCBlade.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no directories found matching 'docs\_build\html'
writing manifest file 'src\CCBlade.egg-info\SOURCES.txt'
running build_ext
Cannot build msvcr library: "msvcr90d.dll" not found
customize Mingw32CCompiler
customize Mingw32CCompiler using build_ext
customize GnuFCompiler
Could not locate executable g77
Could not locate executable f77
customize IntelVisualFCompiler
Could not locate executable ifort
Could not locate executable ifl
customize AbsoftFCompiler
Could not locate executable f90
customize CompaqVisualFCompiler
Could not locate executable DF
customize IntelItaniumVisualFCompiler
Could not locate executable efl
customize Gnu95FCompiler
Found executable C:\MinGW\bin\gfortran.exe
Found executable C:\MinGW\bin\gfortran.exe
customize Gnu95FCompiler
customize Gnu95FCompiler using build_ext
building '_bem' extension
compiling C sources
C compiler: gcc -O2 -Wall -Wstrict-prototypes

compile options: '-DNPY_MINGW_USE_CUSTOM_MSVCR -D__MSVCRT_VERSION__=0x0900 -Ibui
ld\src.win32-2.7 -Ic:\users\python\anaconda2\lib\site-packages\numpy\core\includ
e -IC:\Users\python\Anaconda2\include -IC:\Users\python\openmdao-0.10.3.2\PC -IC
:\Users\python\Anaconda2\include -IC:\Users\python\openmdao-0.10.3.2\PC -c'
extra options: '-O2'
gcc -O2 -Wall -Wstrict-prototypes -DNPY_MINGW_USE_CUSTOM_MSVCR -D__MSVCRT_VERSIO
N__=0x0900 -Ibuild\src.win32-2.7 -Ic:\users\python\anaconda2\lib\site-packages\n
umpy\core\include -IC:\Users\python\Anaconda2\include -IC:\Users\python\openmdao
-0.10.3.2\PC -IC:\Users\python\Anaconda2\include -IC:\Users\python\openmdao-0.10
.3.2\PC -c build\src.win32-2.7\_bemmodule.c -o build\temp.win32-2.7\Release\buil
d\src.win32-2.7\_bemmodule.o -O2
Found executable C:\MinGW\bin\gcc.exe
gcc -O2 -Wall -Wstrict-prototypes -DNPY_MINGW_USE_CUSTOM_MSVCR -D__MSVCRT_VERSIO
N__=0x0900 -Ibuild\src.win32-2.7 -Ic:\users\python\anaconda2\lib\site-packages\n
umpy\core\include -IC:\Users\python\Anaconda2\include -IC:\Users\python\openmdao
-0.10.3.2\PC -IC:\Users\python\Anaconda2\include -IC:\Users\python\openmdao-0.10
.3.2\PC -c build\src.win32-2.7\fortranobject.c -o build\temp.win32-2.7\Release\b
uild\src.win32-2.7\fortranobject.o -O2
compiling Fortran sources
Fortran f77 compiler: C:\MinGW\bin\gfortran.exe -Wall -g -ffixed-form -fno-secon
d-underscore -O3 -funroll-loops
Fortran f90 compiler: C:\MinGW\bin\gfortran.exe -Wall -g -fno-second-underscore
-O3 -funroll-loops
Fortran fix compiler: C:\MinGW\bin\gfortran.exe -Wall -g -ffixed-form -fno-secon
d-underscore -Wall -g -fno-second-underscore -O3 -funroll-loops
compile options: '-Ibuild\src.win32-2.7 -Ic:\users\python\anaconda2\lib\site-pac
kages\numpy\core\include -IC:\Users\python\Anaconda2\include -IC:\Users\python\o
penmdao-0.10.3.2\PC -IC:\Users\python\Anaconda2\include -IC:\Users\python\openmd
ao-0.10.3.2\PC -c'
gfortran.exe:f90: src/bem.f90
C:\MinGW\bin\gfortran.exe -Wall -g -Wall -g -shared build\temp.win32-2.7\Release
\build\src.win32-2.7\_bemmodule.o build\temp.win32-2.7\Release\build\src.win32-2
.7\fortranobject.o build\temp.win32-2.7\Release\src\bem.o -Lc:\mingw\lib\gcc\min
gw32\4.9.3 -LC:\Users\python\Anaconda2\Libs -LC:\Users\python\openmdao-0.10.3.2\
libs -LC:\Users\python\openmdao-0.10.3.2\PCbuild -LC:\Users\python\openmdao-0.10
.3.2\PC\VS9.0 -lpython27 -lgfortran -o src\_bem.pyd
build\temp.win32-2.7\Release\src\bem.o: In function `windcomponents_':
C:\Users\python\WISDEM-WISDEM-947a089\plugins\CCBlade/src/bem.f90:255: undefined
 reference to `pow'
C:\Users\python\WISDEM-WISDEM-947a089\plugins\CCBlade/src/bem.f90:255: undefined
 reference to `pow'
C:\Users\python\WISDEM-WISDEM-947a089\plugins\CCBlade/src/bem.f90:255: undefined
 reference to `pow'
C:\Users\python\WISDEM-WISDEM-947a089\plugins\CCBlade/src/bem.f90:255: undefined
 reference to `pow'
C:\Users\python\WISDEM-WISDEM-947a089\plugins\CCBlade/src/bem.f90:255: undefined
 reference to `pow'
build\temp.win32-2.7\Release\src\bem.o:C:\Users\python\WISDEM-WISDEM-947a089\plu
gins\CCBlade/src/bem.f90:255: more undefined references to `pow' follow
collect2.exe: error: ld returned 1 exit status
error: Command "C:\MinGW\bin\gfortran.exe -Wall -g -Wall -g -shared build\temp.w
in32-2.7\Release\build\src.win32-2.7\_bemmodule.o build\temp.win32-2.7\Release\b
uild\src.win32-2.7\fortranobject.o build\temp.win32-2.7\Release\src\bem.o -Lc:\m
ingw\lib\gcc\mingw32\4.9.3 -LC:\Users\python\Anaconda2\Libs -LC:\Users\python\op
enmdao-0.10.3.2\libs -LC:\Users\python\openmdao-0.10.3.2\PCbuild -LC:\Users\pyth
on\openmdao-0.10.3.2\PC\VS9.0 -lpython27 -lgfortran -o src\_bem.pyd" failed with
 exit status 1

ERROR: command 'C:\Users\python\openmdao-0.10.3.2\Scripts\python.exe setup.py de
velop -N' returned error code: 1

**Comment by andrewning** [comment]
The error says "undefined reference to pow" which means its not linking against the math library.  This should happen automatically so it's odd that it's not in this case.  I'm not sure exactly what the syntax would be in the setup.py script.  under "Extension(" after the "extra_compile_args" option you could try adding the options: "libraries=['m']".  You could also try it manually using your call from above:

C:\MinGW\bin\gfortran.exe -Wall -g -Wall -g -shared build\temp.win32-2.7\Release
\build\src.win32-2.7_bemmodule.o build\temp.win32-2.7\Release\build\src.win32-2
.7\fortranobject.o build\temp.win32-2.7\Release\src\bem.o -Lc:\mingw\lib\gcc\min
gw32\4.9.3 -LC:\Users\python\Anaconda2\Libs -LC:\Users\python\openmdao-0.10.3.2\
libs -LC:\Users\python\openmdao-0.10.3.2\PCbuild -LC:\Users\python\openmdao-0.10
.3.2\PC\VS9.0 -lpython27 -lgfortran -o src_bem.pyd

Except you would add -lm right before the -o at the end.

**Comment by evan-gaertner** [comment]
Andrew,

Thanks for the quick reply.  Editing the setup.py options did the trick.  I had to add the library and the library directory to Extensions.  Just to be safe and avoid potential issues in the future, I also added "C:\MinGW\lib" to my PATH.  

Thanks again!
Evan

ext_modules=[Extension('_bem', ['src/bem.f90'], extra_compile_args=['-O2'], libraries=['m'], library_dirs=['C:/MinGW/lib'])],
