### ISSUE TITLE
Building w/ numpy=1.22

### ISSUE THREAD

**Issue by nikhar-abbas** [WISDEM/WISDEM#348]
## Description
I've run into a _somewhat_ specific bug when building WISDEM on eagle.

When using numpy=1.22 and intel compilers, ccblade does not build. I believe this is related to changes in numpy's distutils, as it seems that many functions in numpy.distutils are getting deprecated and moved to setuptools.

I have tried using setuptools instead of distutils in the setup.py, but this results in fortran recognition errors when doing `python setup.py develop` and a `No module named 'numpy'` error when doing `pip install -e .`.

### Steps to reproduce issue
_Must be on eagle with intel modules loaded_

1. Follow standard developer install steps on develop branch
2. Make sure that you are using numpy=1.22

### Current behavior
Cannot compile with numpy=1.22

### Expected behavior
Would like it to compile

### Code versions
- Python=3.8
- Numpy=1.22
- Loaded moduless on eagle:  `1) cmake/3.18.2   2) conda/4.9.2   3) comp-intel/2020.1.217   4) intel-mpi/2020.1.217   5) mkl/2020.1.217`

**Comment by gbarter** [comment]
Hopefully this is fixed in #349 

I don't think we are yet at a crossroads with numpy & setuptools.  I think pip just got pickier and needs to be told to install numpy before running `setup.py`

**Comment by gbarter** [comment]
@nikhar-abbas Can you do a `git pull` on the `develop` branch and try again on Eagle?  I tested it out and seems to work after a couple of other fixes.  I do not understand what changed- whether it was numpy or eagle intel packages- that broke the build, but I think things are working again (for WISDEM).

**Comment by nikhar-abbas** [comment]
okay, I think this was fixed in #349 - I'll update the submodule in https://github.com/WISDEM/WEIS/pull/156 and hopefully all of my eagle installation-related issues will be sorted!
