### ISSUE TITLE
Error with discrete inputs in opemdao v3.17

### ISSUE THREAD

**Issue by ptrbortolotti** [WISDEM/WISDEM#369]
## Description
OpenMDAO 3.17 errors out when we try to access a discrete input in a run_driver opt problem

Temporary fix: downgrade openmdao to 3.16, we're working to open an issue on the openmdao GitHub page

### Steps to reproduce issue
Run example 03 in WISDEM with openmdao 3.17

### Current behavior
RuntimeError: <model> <class WindPark>: Variable 'blade.internal_structure_2d_fem.definition_layer' is not local to rank 0. You can retrieve values from other processes using `get_val(<name>, get_remote=True)`.

### Expected behavior
No error

**Comment by gbarter** [comment]
Thank you for tracking this down!

**Comment by gbarter** [comment]
This seems to be resolved in the recently released v3.18.  I have a draft feature branch that resets the version requirements.
