### ISSUE TITLE
WISDEM output data transform

### ISSUE THREAD

**Issue by SeongwooCheon** [WISDEM/WISDEM#370]
Hello.

Thank you for reading my request.
I know that WISDEM is a steady state analysis program for wind turbine. So I want to analysis the aeroelasticity with repect to optimized wind turbine for WISEM using other aeroelastic program such as HAWC2, OpenFAST etc.
I consider HAWC2 for aeroelastic analysis. Due to different reference axes, coordinate systems, and modeling assumptions in OpenFAST and HAWC2, mass matrix or stiffness is not same value.

I want to transform WISDEM output data into HAWC2 input. How can I do for this?

**Comment by ptrbortolotti** [comment]
Hello,
running OpenFAST on WISDEM outputs is easy thanks to the framework WEIS. You can refer to one of the examples there, for example https://github.com/WISDEM/WEIS/tree/master/examples/06_IEA-15-240-RWT
Building a HAWC2 model from OpenFAST is quite a big deal (maybe surprisingly). We have developed a converter, available here https://github.com/OpenFAST/python-toolbox/blob/dev/pyFAST/converters/openfastToHawc2.py, but you'll need to run some comparison of the outputs to make sure that everything is built correctly.
Good luck!
Pietro

**Comment by SeongwooCheon** [comment]
thank you for your response!

the blade cross section properties of WISDEM output is obtained running the Timoshenko beam solver, Frame3dd(Elastodyn).
but, the blade properties that is obtained running Beamdyn, which is combined GEBT-LSFEs, is used to transform HAWC2 input.

is there method to transform the Elastodyn output into Beamdyn output?

**Comment by SeongwooCheon** [comment]
thank you!!
