### ISSUE TITLE
Mass matrix

### ISSUE THREAD

**Issue by SeongwooCheon** [WISDEM/WISDEM#377]
Hi,

I would like to inform you that there seems to be an error while constructing the mass matrix.

From the homepage about geometry Inputs, The mass matrix has components like this:
**M = [m, 0, 0, 0, 0, -mYcm, m, 0, 0, 0,mXcm, m, mYcm, -mXcm, 0, iedge, -icp, 0, iflap, 0, iplr]**

However, it seems to be calculated differently in the WISDEM code.
https://github.com/WISDEM/WISDEM/blob/8bf206a6a2c110997c6449cfa8106dfef68d6606/wisdem/glue_code/gc_LoadInputs.py#L934

If this problem is error, How can I solve this error?
Additionally, Does the mass matrix of WISDEM have same components as the mass matrix of BeamDyn??

**Comment by ptrbortolotti** [comment]
Hi,
this was a good catch, the inertia matrix wasn't writing out the flap and the cross product of inertias correctly. I've now fixed the first problem, however I understand that PreComp does not estimate the cross product of inertia, and I've therefore left it to 0. Also, PreComp does not estimate shear stiffness terms, and so the stiffness matrix cannot be fed to BeamDyn unless you assume those terms. We have developed the framework [SONATA](https://github.com/ptrbortolotti/SONATA) to generate accurate beamdyn files
I hope this helps.
Best regards,
Pietro

**Comment by SeongwooCheon** [comment]
> Traceback (most recent call last):
>   File "C:\ProgramData\anaconda3\envs\wisdem-env\Scripts\wisdem-script.py", line 33, in <module>
>     sys.exit(load_entry_point('WISDEM', 'console_scripts', 'wisdem')())
>   File "c:\users\chsu\wisdem\wisdem\main.py", line 69, in wisdem_cmd
>     wt_opt, modeling_options, opt_options = run_wisdem(sys.argv[1], sys.argv[2], sys.argv[3])
>   File "c:\users\chsu\wisdem\wisdem\glue_code\runWISDEM.py", line 175, in run_wisdem
>     wt_initial.write_ontology(wt_opt, froot_out)
>   File "c:\users\chsu\wisdem\wisdem\glue_code\gc_LoadInputs.py", line 969, in write_ontology
>     Ii[18] = wt_opt['re.precomp.flap_iner'][i]
>   File "C:\ProgramData\anaconda3\envs\wisdem-env\lib\site-packages\openmdao\core\problem.py", line 379, in __getitem__
>     return self.get_val(name, get_remote=None)
>   File "C:\ProgramData\anaconda3\envs\wisdem-env\lib\site-packages\openmdao\core\problem.py", line 416, in get_val
>     val = self.model.get_val(name, units=units, indices=indices, get_remote=get_remote,
>   File "C:\ProgramData\anaconda3\envs\wisdem-env\lib\site-packages\openmdao\core\system.py", line 4485, in get_val
>     raise KeyError('{}: Variable "{}" not found.'.format(self.msginfo, name))
> KeyError: '<model> <class WindPark>: Variable "re.precomp.flap_iner" not found.'

**Comment by ptrbortolotti** [comment]
https://github.com/WISDEM/WISDEM/commit/353458da9e2e8cac3ddf6d444afe745703af814f
Ii[18] = wt_opt['rotorse.re.precomp.flap_iner'][i]

**Comment by SeongwooCheon** [comment]
thank you for your response:)
