### ISSUE TITLE
output, web strat(end)_nd_arc value

### ISSUE THREAD

**Issue by SeongwooCheon** [WISDEM/WISDEM#380]
Hi,

When I run the example, IEA 15MW RWT, the wrong value of web start(end)_node_arc is output.
the attached figure is the comparison between IEA-15-240-RWT.yaml and output of IEA-15-240-RWT.yaml that was run by WISDEM.

Please check this error.

![web1_(end_nd_arc)](https://user-images.githubusercontent.com/77769771/173201610-4cd14fcc-0443-4e4d-8a1f-fd11d25ef4b3.png)
![web1_(start_nd_arc)](https://user-images.githubusercontent.com/77769771/173201614-3e0aac5b-a464-496e-bfd0-b57a6e08869c.png)
(same lengend)

and the IEA 15MW RWT yaml file contained in the SONATA example output this error message. I command the n_span=30.
but, When n_span is 50, this yaml file is successfully run.

How do I solve this error if I want to run this problem with n_span=30?

```
==
wt
==
ERROR** lower-surf last sector node out of bounds   1.0000139021913079        1.0000000000000000
```

**Comment by ptrbortolotti** [comment]
Hello,
you should be able to resolve the latter problem by deleting these two fields
https://github.com/ptrbortolotti/SONATA/blob/ebfce6dafbd67d6a238f1241ff8711c6a5fb658c/examples/1_IEA15MW/IEA-15-240-RWT.yaml#L175
https://github.com/ptrbortolotti/SONATA/blob/ebfce6dafbd67d6a238f1241ff8711c6a5fb658c/examples/1_IEA15MW/IEA-15-240-RWT.yaml#L194
This is a pretty annoying bug that I haven't had the time to track down. This solution will work for the time being. The issue hides in the fact that by prescribing non dimensional start and end in addition to the width you're over specifying the layer positions.

I am instead not able to replicate the first error. When I run this script https://github.com/WISDEM/WISDEM/blob/master/examples/02_reference_turbines/iea15mw_driver.py, I get a perfect match in the start and end positions of web0 between input and output yaml. Please provide more details or check your run.

Regards,
Pietro
