### ISSUE TITLE
using the bem.f90 file

### ISSUE THREAD

**Issue by aaronhsks** [WISDEM/WISDEM#395]
Hello,

I'm trying to use the RAFT python package (https://openraft.readthedocs.io/en/latest/#). To do this, I need to use the CCBlade module from WISDEM. This creates the following issue:

When I install WISDEM using 'conda install wisdem' an earlier/later version of the CCBlade module is installed, which does not correspond to the one needed for the RAFT package.

The CCBlade.ccblade.py module as shown on [WISDEM/wisdem/ccblade](https://github.com/WISDEM/WISDEM/tree/master/wisdem/ccblade) does correspond to the RAFT package. However, when I copy the script in CCBlade.ccblade.py from GitHub into the CCBlade.ccblade.py file as installed by 'conda install wisdem', I get the following error: 
**\ccblade.py", line 835, in __windComponents _, Vxd, _, Vyd = _bem.windcomponents_dv(ValueError: failed in converting 3rd argument `precurve' of _bem.windcomponents_dv to C/Fortran array**

My theory is that I need to use the entire CCBlade package from GitHub for it to work, not just the CCBlade.ccblade.py file.

The problem is that the CCBlade package on GitHub contains a **src\bem.f90** file with Fortran code.
When I install WISDEM using 'conda install wisdem', the CCBlade package contains the file '**_bem.cp39-win_amd64.pyd**'. It seems to me that this is the src\bem.f90 Fortran code compiled into a .pyd file that can communicate with the rest of the CCBlade package.

I tried to compile the src\bem.f90 file from GitHub into a compiled .pyd file, but I cannot manage this. Like I said, using '**_bem.cp39-win_amd64.pyd**' from the conda installed version with the GitHub CCBlade.ccblade.py is giving an error.

I tried installing the GitHub WISDEM version using the installation instructions on GitHub, but this still gives me the error that the src\bem.f90 file cannot be read.

Can you give me advice on how to solve this, or perhaps provide a functioning CCBlade packages in the version from GitHub, already containing a .pyd file instead of src/bem.f90?

Thanks a lot.

**Comment by gbarter** [comment]
Thank you for your interest in RAFT and the WISDEM suite!  I have put the question to the RAFT team.  My suspicion is that the best thing to do is install [CCBlade as a standalone](https://github.com/WISDEM/CCBlade), but I will defer to the RAFT team for confirmation.

**Comment by gbarter** [comment]
After discussing with the RAFT team, there is clearly some room for improvement in the software setup here.  For now, RAFT has an [import statement](https://github.com/WISDEM/RAFT/blob/dev/raft/raft_rotor.py#L19) that uses the CCBlade from WISDEM.  So, WISDEM must be properly installed.  I'm surprised that the `conda install wisdem` didn't work, as that should be [current](https://anaconda.org/conda-forge/wisdem/files).  The next step would be to try to install WISDEM directly from [source following the README instructions](https://github.com/WISDEM/WISDEM/tree/develop) (best to use the `dev` branch).

**Comment by gbarter** [comment]
That is a helpful comment, @dzalkind !

The current version of WISDEM is v3.6.1, but CCBlade hasn't changed since 3.5 or earlier.

**Comment by aaronhsks** [comment]
Hi! 

Thank you both for your answers. `conda install wisdem==3.5.0` is working. In addition I had to use `pip install matplotlib==3.5.0` to make sure the right version of matplotlib was installed, as the newest version gives an error as well.
