### ISSUE TITLE
3d modeling using WISDEM output

### ISSUE THREAD

**Issue by SeongwooCheon** [WISDEM/WISDEM#397]
I am working on 3d modeling of a wind turbine using WISDEM output.

I think the thickness of the airfoil surface (e.g., spar cap, skin, etc.) is defined as the material stacked inner direction.

So how is the thickness of the web defined?

**Comment by gbarter** [comment]
You use the same layer technique for the webs.  See this [example](https://github.com/WISDEM/WISDEM/blob/master/examples/02_reference_turbines/IEA-15-240-RWT.yaml#L278) on the IEA Wind 15-MW blade.
