### ISSUE TITLE
Potential equation error

### ISSUE THREAD

**Issue by WindfarmDesigner** [WISDEM/WISDEM#398]
## Description
Potential equation error in 'pile_mass' in WISDEM/wisdem/orbit/phases/design/monopile_design.py
The mass of the monopile is calculated via its estimated volume.
You calculate the volume as : volume = (pi / 4) * (Dp**2 - (Dp - tp) ** 2) * Lt
I guess, the wall thickness tp should be substracted twice when calculating the annulus surface...
That changes the estimated mass significantly.
Best regards

**Comment by gbarter** [comment]
Thank you for pointing this out!  I agree this looks like a bug/typo.

This error is in the monopile design code of ORBIT.  When using ORBIT, our BOS tool, through WISDEM, WISDEM supplies the monopile design details and bypasses this code.  When using ORBIT as a standalone model, then this code can be used to estimate monopile properties.

I am tagging the ORBIT team with this Issue.
@JakeNunemaker @Matt-Shields : The error is [here](https://github.com/WISDEM/ORBIT/blob/dev/ORBIT/phases/design/monopile_design.py#L358).

**Comment by gbarter** [comment]
Moved this over to an ORBIT issue
