### ISSUE TITLE
constraint question

### ISSUE THREAD

**Issue by SeongwooCheon** [WISDEM/WISDEM#399]
Hello.

I have one question about imposing constraints on maximum strains in the spar cap ss/ps.
I typed 0.0065 in the maximum value of strains_spar_cap_ss like this.

> blade:
>     strains_spar_cap_ss:
>         flag: true         
>         max:    0.00652439 
>         index_start: 1     
>         index_end: 10

but, after solving the optimization problem, the maximum strains (absolute value) in the spar cap ss or ps is 0.00706.
this value is obtained by rotorse.rs.strains.strainU_spar column.

I think it is something wrong, but I can't find what is wrong.

thank you

**Comment by gbarter** [comment]
Hi Seongwoo- Not all optimizers succeed in satisfying all constraints in all cases.  You can try a different optimizer, different initial condition, loosen design variable bounds, turn off other constraints, etc.
