### ISSUE TITLE
GA optimizer error

### ISSUE THREAD

**Issue by SeongwooCheon** [WISDEM/WISDEM#401]
Hello.

I want to optimize our wind turbine blade using GA optimizer.
So I set the design variables and control points like the attached file.
but, the error occurred like this:

> RuntimeWarning: C:\ProgramData\anaconda3\envs\wisdem-env\lib\site-packages\openmdao\drivers\genetic_algorithm_driver.py:971
> invalid value encountered in true_divideTraceback (most recent call last):
>   File "hybrid_opt.py", line 13, in <module>
>     wt_opt, modeling_options, analysis_options_1 = run_wisdem(fname_wt_input_1, fname_modeling_options, fname_analysis_options_struct_1)
>   File "c:\users\chsu\wisdem\wisdem\glue_code\runWISDEM.py", line 175, in run_wisdem
>     wt_opt.run_driver()
>   File "C:\ProgramData\anaconda3\envs\wisdem-env\lib\site-packages\openmdao\core\problem.py", line 722, in run_driver
>     return self.driver.run()
>   File "C:\ProgramData\anaconda3\envs\wisdem-env\lib\site-packages\openmdao\drivers\genetic_algorithm_driver.py", line 307, in run
>     desvar_new, obj, nfit = ga.execute_ga(x0, lower_bound, upper_bound, outer_bound,
>   File "C:\ProgramData\anaconda3\envs\wisdem-env\lib\site-packages\openmdao\drivers\genetic_algorithm_driver.py", line 624, in execute_ga
>     new_gen[0] = self.encode(x0, vlb, vub, bits)
>   File "C:\ProgramData\anaconda3\envs\wisdem-env\lib\site-packages\openmdao\drivers\genetic_algorithm_driver.py", line 976, in encode
>     result = np.array([int(c) for s in byte_str for c in s])
>   File "C:\ProgramData\anaconda3\envs\wisdem-env\lib\site-packages\openmdao\drivers\genetic_algorithm_driver.py", line 976, in <listcomp>
>     result = np.array([int(c) for s in byte_str for c in s])
> ValueError: invalid literal for int() with base 10: 'b'

[wt.zip](https://github.com/WISDEM/WISDEM/files/9995590/wt.zip)

**Comment by gbarter** [comment]
My guess is that the WISDEM wrappers and analysis options are not configured to properly initialize the OpenMDAO GA optimizer.  The list of approved and tested optimizers is [here](https://github.com/WISDEM/WISDEM/blob/master/wisdem/glue_code/gc_PoseOptimization.py).  

There is some code in that file mentioning the GA, so I understand that it is misleading.  If you aren't able to debug your error and make the code modifications yourself, I would suggest changing to a different optimizer.  The NLOpt choices may be worth looking into.
