### ISSUE TITLE
Failed tests

### ISSUE THREAD

**Issue by James-Ilosta** [WISDEM/WISDEM#404]
![image](https://user-images.githubusercontent.com/116352311/205064423-cd38380e-b669-44ab-ba77-e476a9c53155.png)

I ran the setup as instructed and I then run the test_all.py and get the following error. Would you be able to provide any information on what I have done wrong?

**Comment by gbarter** [comment]
Your WISDEM setup seems to be working fine.  Our regression tests use "truth" values generated for Mac and Linux machines with specific compilers.  Windows has a different setup and will see different answers to some decimal point.  I think you can ignore this error.

**Comment by James-Ilosta** [comment]
Thanks that's great to know!
