### ISSUE TITLE
Trying to run ccblade.py and I get this error

### ISSUE THREAD

**Issue by James-Ilosta** [WISDEM/WISDEM#405]
![image](https://user-images.githubusercontent.com/116352311/205100052-2578d545-f5dc-42a5-bb9c-9bc24bb15371.png)

![image](https://user-images.githubusercontent.com/116352311/205100684-7eb65ac0-97e7-402c-bdc6-d4d6c0b2fdbb.png)

I have installed wisdem as instructed on the main page. What's the best way to import wisdem from a file inside wisdem? Also it seems as though the file _bem.cp311-win_amd64.pyd can't be imported either. If I try to import it directly on interactive python I get the following error, by adding the path I get the following:
![image](https://user-images.githubusercontent.com/116352311/205101986-796d438e-dc30-41a5-8aa6-4eb5951928cc.png)

If I change the file name to just _bem.pyd then i get the following error:

![image](https://user-images.githubusercontent.com/116352311/205102412-96e399e4-1a69-468d-a64b-a6d5a2c6c3c0.png)

**Comment by gbarter** [comment]
I cannot see the full prompt to know if this is the issue, but make sure you are in the same conda environment as where you installed WISDEM (I think you labelled it `wisdem-env`).

**Comment by James-Ilosta** [comment]
Ahhh. So, I wanted to use wisdem from a different python version. Is this possible?

**Comment by gbarter** [comment]
Yes, that is possible.


Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by James-Ilosta** [comment]
How would I go about doing this?

**Comment by gbarter** [comment]
Just make sure you `conda activate wisdem-env` before running the script that has `import wisdem`

**Comment by James-Ilosta** [comment]
So my original python is 3.7. When I installed anaconda, it installed python 3.9. I can't use conda from my python 3.7 (as far as I'm aware). What's more I'm trying to automate and script a load of things and so, I only really need that one file now (_bem). If I activate that python module this would be the optimum outcome. Better yet, if I can just call ccblade.py and it would be able to handle the _bem import this would be even better. To be honest I don't understand what type of file the file called: _bem.cp311-win_amd64.pyd is. It seems to be a DLL file however I can't actually open it or simply import it as I have imported other DLL files using import, so I'm rather confused.

**Comment by James-Ilosta** [comment]
> Just make sure you `conda activate wisdem-env` before running the script that has `import wisdem`

I did try running `conda activate wisdem-env` and then `import wisdem` inside the anaconda command prompt and this didn't work. I've also tried activating it and moving to the folder where _bem is supposed to be and there is still just the file: _bem.cp311-win_amd64.pyd which I can't interact with:

![image](https://user-images.githubusercontent.com/116352311/205127960-262929b6-2666-4647-9728-18abaa4082d6.png)

**Comment by gbarter** [comment]
After doing `conda activate wisdem-env`, you then have to launch python in interactive mode by just typing `python`.  From there you can do `import wisdem`.  The prompt shouldn't need to be in the directory where you've located the WISDEM files.

**Comment by James-Ilosta** [comment]
So it appears to work now when using wisdem inside the environment. I think I'm going to have to install wisdem outside of the environment and then also upgrade my python to python 3.11 as then I should be able to simply import wisdem directly

![image](https://user-images.githubusercontent.com/116352311/205131263-84650ba1-f04a-490e-9143-c1bfe3fd35fb.png)
