### ISSUE TITLE
add design variables

### ISSUE THREAD

**Issue by SeongwooCheon** [WISDEM/WISDEM#406]
Hi
I want to add other design variables and constraints like filler thickness, web thickness[design variable], etc.
I followed Issue #283, but all design variable has not changed.
However, if considering only the new design variables, the thickness is changed. 

I added code for adding design variables like this:

[Desktop.zip](https://github.com/WISDEM/WISDEM/files/10149535/Desktop.zip)

The added design variable name is le_reinf.
Is it wrong?

thank you

**Comment by ptrbortolotti** [comment]
There could be different things going on. A test that I usually recommend is to start with few DVs and constraints and built the problem in complexity slowly. For example, try activating only spar caps DVs and one constraint and see if things change. Also, I'd recommend plotting DVs, merit figure, and constraints from the openmdao log file. You can do that by running these lines https://github.com/WISDEM/WISDEM/blob/29181252306f5b1a769ebbda67a6ca2796d91f14/wisdem/glue_code/gc_RunTools.py#L122
Just make sure that you're actually generating the log file. You need the flag set to True in the analysis options yaml, here https://github.com/WISDEM/WISDEM/blob/29181252306f5b1a769ebbda67a6ca2796d91f14/examples/03_blade/analysis_options_aero.yaml#L49
Good luck,
Pietro
