### ISSUE TITLE
Error problems of running the examples through WISDEM GUI

### ISSUE THREAD

**Issue by zhuifeng2015** [WISDEM/WISDEM#408]
Selecting three required YAML file type in the WISDEM GUI and click Run. 
The result cannot be calculated and the error is "ValueError: zero-size array to reduction operation minimum which has no identity".
![image](https://user-images.githubusercontent.com/26338872/209683568-eb9f8d1a-c3c4-4d76-8ef6-0188b16e740a.png)

**Comment by zhuifeng2015** [comment]
The first step and the second step of setting are OK, but there is a problem during running:
![image](https://user-images.githubusercontent.com/26338872/209683772-cb2285a8-5c46-452a-91f9-dc93f7d1b1a7.png)
![image](https://user-images.githubusercontent.com/26338872/209683821-f01c42e4-6a79-474a-a792-8b5d3ed98ca9.png)
![image](https://user-images.githubusercontent.com/26338872/209683971-24bf8374-84a7-4904-90c7-4cfa10e57ddf.png)

**Comment by gbarter** [comment]
I'm sorry you experienced an error.  I am actively working on a new GUI for WISDEM as the old one has been difficult to maintain due to conflicts with third party libraries.  For now, my best advice is to use the command line.  You can find tips and guidance in the documentation.

**Comment by gbarter** [comment]
Sorry, I was mistaken.  I am seeing this error now on recent builds.  This is not a GUI issue.  I will fix it and submit a change to the `develop` branch.  Are you comfortable switching branches on your WISDEM git clone/checkout?

**Comment by zhuifeng2015** [comment]
About "switching branches on your WISDEM git clone/checkout", do you mean that I upload my WISDEM installation files to the Github?
If I understand correctly, since I am not familiar with file uploading on Github, could you please tell me where I need to upload it?

**Comment by gbarter** [comment]
@zhuifeng2015 : From the command line inside of the directory where you downloaded WISDEM, do:
```
git checkout develop
git pull
```
And then try the GUI again.

**Comment by ptrbortolotti** [comment]
closing this for now
