### ISSUE TITLE
Are there updated install directions for windows?

### ISSUE THREAD

**Issue by ba-beracus** [WISDEM/WISDEM#41]
I've noticed from the NREL NWTC WISDEM website that the windows instructions are a bit dated.  For example, openmdao is now on version 1.7.3.  Also, Boost is on version 1.63, and if you are going to use the boost command:  "> cd boost_1_55_0\tools\build\v2\engine"  it should read, "cd boost_1_63_0\tools\build\src\engine"
I do not have experience installing programs and drivers like Boost and LAPACK.  Any help in installing the necessary support would be helpful.  Currently, I am getting an error trying to install the Boost build.bat.

I am able to run OpenMDAO tutorials.

**Comment by dykesk** [comment]
Hello –

We are in a process of refactoring our codes that will ultimately eliminate boost and lapack dependencies.  We don’t have any more thorough directions at present for the codes as they are unfortunately.

Best, - Katherine
