### ISSUE TITLE
Error with ccblade

### ISSUE THREAD

**Issue by junyoshitake** [WISDEM/WISDEM#413]
Hello

I am receiving an error when trying to run WISDEM through Anaconda Powershell where it is stating that a module is missing, shown below.

File "C:\WISDEM\wisdem\ccblade\ccblade.py", line 31, in <module>
    import wisdem.ccblade._bem as _bem
ModuleNotFoundError: No module named 'wisdem.ccblade._bem'

I followed the installation steps listed in the installation page for windows.
https://wisdem.readthedocs.io/en/master/installation.html

Could guidance be provided on how this can be resolved?

**Comment by gbarter** [comment]
Hello,

Yes, this means the installation was not successful.  We switched to a new build system and there have been some hiccups on Windows machines.  Can you confirm that you are current with the latest version in the repository by doing a `git pull`, delete any folder named `build` or `meson_build`, and trying `python setup.py develop` again?

Cheers,
Garrett

**Comment by KlootwijkBart** [comment]
I experienced the same trouble installing WISDEM on my windows machine. Following the steps suggested by Garrett solved my problem; there was a folder meson_build that I had to delete to successfully install the software. 

Thank you!
Bart

**Comment by gbarter** [comment]
Glad to hear it, Bart!
