### ISSUE TITLE
Having trouble installing WISDEM on Linux

### ISSUE THREAD

**Issue by ba-beracus** [WISDEM/WISDEM#42]
Hello,  I'm trying to install WISDEM on Ubuntu.  I follow the directions, but when I get to installing WISDEM I get the error:
sh: 1: plugin: not found
After that I get a list of the sub-plugins and a message telling me "Failed to install: []"

Any suggestions?
Can I use a newer OpenMDAO version? Currently, I am creating a virtual OpenMDAO environment with version 0.10.3.2.  OpenMDAO is not listed as a package in my Anaconda python 2.7 environment

Thanks in advance for any guidance.

**Comment by dykesk** [comment]
Closing this issue as it is old - old openmdao did not work well with anaconda.  we are currently migrating to new openmdao so this should no longer be a relevant issue

**Comment by crobarcro** [comment]
Not sure why this was closed, it still seems relevant to me since I have the same issue. Has the migration been completed? If so it would be great if you could point to the new version as I'd love to get started!
