### ISSUE TITLE
Error of NREL5MW_driver.py in 02_reference_turbines

### ISSUE THREAD

**Issue by joowandon** [WISDEM/WISDEM#426]
## Description

Errors in NREL5MW Reference turbine in '02_reference_turbines'

(wisdem-env-develop) PS D:\Users\GitHub\BranchDevelop\WISDEM\examples\02_reference_turbines> python .\nrel5mw_driver.py

==
wt
==
  **ERROR** last web out of sectors-bounded airfoil
[00m[00m[00m[00m[00mNL: NLBGS 1 ; 1.77048371e+12 1
  ERROR** last web out of sectors-bounded airfoil
[00m[00m[00m[00m[00mNL: NLBGS 2 ; 23165292.8 1.30841604e-05
  ERROR** last web out of sectors-bounded airfoil
[00m[00m[00m[00m[00mNL: NLBGS 3 ; 0 0**
NL: NLBGS Converged
FutureWarning: d:\users\github\branchdevelop\wisdem\wisdem\landbosse\model\ErectionCost.py:481
In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.FutureWarning: d:\users\github\branchdevelop\wisdem\wisdem\landbosse\model\ErectionCost.py:567
In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.FutureWarning: d:\users\github\branchdevelop\wisdem\wisdem\landbosse\model\ErectionCost.py:1311
In a future version, object-dtype columns with all-bool values will not be included in reductions with bool_only=True. Explicitly cast to bool dtype instead.FutureWarning: d:\users\github\branchdevelop\wisdem\wisdem\landbosse\model\ErectionCost.py:1041
The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.FutureWarning: d:\users\github\branchdevelop\wisdem\wisdem\landbosse\model\ErectionCost.py:1280
The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.########################################
Objectives
Turbine AEP: 23.9001684640 GWh
Blade Mass:  16469.8925506885 kg
LCOE:        51.8961397857 USD/MWh
Tip Defl.:   4.5072101787 m
########################################
blade mass: [16469.89255069]
blade moments of inertia: [35692016.04877505 17846008.02438752 17846008.02438752        0.
        0.                0.        ]
BRFM: [-15931403.57039435]
hub forces: [1157362.58475108    8627.43082479    9933.9497599 ]
hub moments: [10881583.54936924  1156513.61130747  1212682.3019354 ]

### Steps to reproduce issue
_Please provide a minimum working example (MWE) if possible_
1. WISDEM installed in 'develop' branch version as like follows. 

>>>conda env create --name wisdem-env-develop -f https://raw.githubusercontent.com/WISDEM/WISDEM/develop/environment.yml python=3.9
>>>git checkout develop
>>>git pull
>>>python setup.py develop

### Code versions
1. WISDEM
3. conda version 23.3.0
4. python version 3.10.9.final.0
5. conda/23.3.0 requests/2.28.1 CPython/3.10.9 Windows/10 Windows/10.0.19042 (win-64 platform)

**Comment by gbarter** [comment]
Your WISDEM installation is actually working just fine.  It looks like newer versions of third party libraries are throwing warnings about syntax that used to be valid but might not be in the future.  I can recreate those warnings on my computer and make the minor code edits to fix them.  We will include those changes in a future WISDEM release.  For now, I wouldn't worry about them.

Thank you for highlighting this issue.

**Comment by joowandon** [comment]
Dear Mr. gbarter, 

Great thanks for your kind comments.
