### ISSUE TITLE
Example 03/blade without optimization does not produce the correct graph of axial induction

### ISSUE THREAD

**Issue by arieknarie** [WISDEM/WISDEM#428]
After installing wisdem and successfully running the examples, it seem that running example 03_blade **_without optimization_**, does not produce the correct axial induction.

![induction](https://user-images.githubusercontent.com/55136700/230122497-9215501f-6e40-4ca5-8e10-748580bb509e.png)

This happens both when using analysis_options_no_opt.yaml or when the optimization flag is set to False.

**Comment by arieknarie** [comment]
Hello Pietro, I understand, but it is different than the one in the repository:
![bladeopt1_induction](https://user-images.githubusercontent.com/55136700/230126129-bbf1c146-ee19-4aa1-ab83-5c8bafa9128c.png)

**Comment by arieknarie** [comment]
To the best of my understanding the induction without optimization should correspond with the 'Initial' plot in the figure in the repository.

**Comment by gbarter** [comment]
It is possible the "initial" line is out-of-date due to model updates and changes in default values for optimization.  If your 'optimized' value looks similar, I wouldn't worry that there is anything wrong on your side.  This is certainly a good reminder for us to refresh the documentation files though.

**Comment by ptrbortolotti** [comment]
I now understand the confusion, I am sorry. You are following this example https://wisdem.readthedocs.io/en/master/examples/blade/tutorial.html, which was however based on an older rotor design (BAR0 vs BAR-USC). I will work to update the documentation with new plots for BAR-USC. In the meanwhile, please go ahead and trust your new results.
Thank you,
Pietro

**Comment by arieknarie** [comment]
Dear Pietro,
If possible could you share the original input file BAR0?
Thank you in advance and best regards,
Duncan

**Comment by ptrbortolotti** [comment]
https://github.com/WISDEM/WISDEM/blob/211f03ee5457a6c1e533c8ef1a438036e420ddc0/examples/03_blade/BAR0.yaml

**Comment by ptrbortolotti** [comment]
Thanks to @gbarter, the updated documentation for the blade optimization example is now available here https://wisdem.readthedocs.io/en/latest/examples/blade/tutorial.html
