### ISSUE TITLE
wisdem use to calculate the load of wind farm

### ISSUE THREAD

**Issue by clun1** [WISDEM/WISDEM#431]
can i use wisdem to calculate the floris load?i don't know how to start,any advise is good!

**Comment by gbarter** [comment]
If you want to calculate turbine loads that account for wakes and array effects, the best tool is FAST.Farm, which is part of the OpenFAST code suite.
https://github.com/OpenFAST/openfast
https://openfast.readthedocs.io/en/main/source/user/fast.farm/index.html

Computing steady state loads from FLORIS flowfields is an active area of research, but there is no solution available in NREL models yet.

**Comment by clun1** [comment]
Thank for your reply, I want to use wisdem as a simple tool to calculate the load of wind farm ,because i kown the ccblade can be use to calculate the load and  wisdem have this function, i don not kown whether i split this function use to calculate load?

**Comment by gbarter** [comment]
We have not used Floris and CCBlade together in this way.  You would have to do some custom development on your own.
