### ISSUE TITLE
Having trouble in optimizing spar cap redesign

### ISSUE THREAD

**Issue by Al-Evan** [WISDEM/WISDEM#437]
Hi,
I am using IEA 3.4 MW RWT and doing an optimization of spar-cap redesign (I am using the structural optimization analysis file and also no_optimization yaml file from the Example 3_Blade and using the Blade geometry yaml file from example_02_reference_turbines folder. I have attached the file here also that I am using). 

The results are giving me a sparcap redesign that is starting from the root of the blade (which isn't ideal) and also it should finish before the tip (which I am not getting as well as the spar cap is running nearly at the end of the tip). I want to have the spar cap redesign starting from where the spar cap is starting in the original blade (IEA 3.4MW RWT yaml). I have attached the comparative figure for the case.

Any suggestion on how to fix the issue (on how to start and finish the spar cap position in the optimized blade similar to the position of reference blade)?

Thanks,
Mohammed Al-Evan Chowdhury
PhD Student
The University of Texas at Dallas
[analysis_options_no_opt.txt](https://github.com/WISDEM/WISDEM/files/11226174/analysis_options_no_opt.txt)
[analysis_options_struct_IEA3_4_sparcap.txt](https://github.com/WISDEM/WISDEM/files/11226175/analysis_options_struct_IEA3_4_sparcap.txt)
[IEA-3p4-130-RWT_adjusted.txt](https://github.com/WISDEM/WISDEM/files/11226176/IEA-3p4-130-RWT_adjusted.txt)
[modeling_options_IEA_3_4.txt](https://github.com/WISDEM/WISDEM/files/11226177/modeling_options_IEA_3_4.txt)
![Optimize](https://user-images.githubusercontent.com/98569149/231874102-ba3f2d9d-18ac-4723-93f2-f03b2cc586c0.png)

**Comment by ptrbortolotti** [comment]
Hello Mohammed,
my apologies for the slow reply. It took me a while to find the time to look into this. This is partly a known weakness of the existing implementation of wisdem, mixed with a weakness introduced with a recent change in the interpolation scheme. I've fixed the latter here in this branch 
https://github.com/WISDEM/WISDEM/tree/pchip_extrapolate
I believe you can go around the first problem using a lot of control points as you do in your files. Watch out however to set the start and end index appropriately.
Alternatively you can start playing with the locations of the design variables, see here https://github.com/WISDEM/WISDEM/issues/430
Please let us know if this helps.
Best regards,
Pietro

**Comment by Al-Evan** [comment]
Good morning.
I have tried the thing you suggested. I have replaced the gc_PoseOptimization.py file with the updated one from your suggestion. While running wisdem after replacing the old one WISDEM didn't run (attached a screen shot with it).

I have tried to implement your suggestions from #430 But I have tried with changing the linspace from (0.0    1.0   to  0.1    0.94- which is the position of spar cap (10%-94% of blade span)). I have also tried to change the index start and index end manually (by putting numbers in- attached the screenshot of the code where I have changed the values). Maybe I have not implemented it correctly. Please let me know if you have any suggestions on how to play with the indices in the code.

Kind regards,
Evan
![wisdem_problem](https://user-images.githubusercontent.com/98569149/234623149-0747d2fb-5c31-4784-be70-f84424650ec9.png)
![Change_in_Code](https://user-images.githubusercontent.com/98569149/234623189-3cfbe667-8001-411d-8ee8-973de0c13909.png)

**Comment by ptrbortolotti** [comment]
The error that you show in the screenshot comes from somewhere else. Please make sure to be up to date with WISDEM master or develop and it should go away. 
Regarding your other attempts, you can change linspace, but make sure to keep points between 0 and 1 included. You can then play with the indices to decide what you want to see as active in the optimization

**Comment by Al-Evan** [comment]
Hi, I have kept the 0 and 1 point. Any suggestions on what should I change the linspace to?
