### ISSUE TITLE
opex negative for lcoe_se_assembly

### ISSUE THREAD

**Issue by dykesk** [WISDEM/WISDEM#44]
Opex is reporting negative when running the lcoe_se_assembly

**Comment by kilojoules** [comment]
@dykesk  How can I reproduce this issue? I'm finding opex to be positive

    $ python lcoe_se_assembly.py 
     
    Key Turbine Outputs for NREL 5 MW Reference Turbine
    mass rotor blades:54674.80 (kg) 
    mass hub system: 0.00 (kg) 
    mass nacelle: 235893.04 (kg) 
    mass tower: 348847.24 (kg) 
    maximum tip deflection: 10.42 (m) 
    ground clearance: 28.51 (m) 
    
    Key Plant Outputs for wind plant with NREL 5 MW Turbine
    COE: $0.0809 USD/kWh
    
    AEP per turbine: 15050698.6 kWh/turbine
    Turbine Cost: $8520707.21 USD
    BOS costs per turbine: $3084430.38 USD/turbine
    OPEX per turbine: $192127.10 USD/turbine

**Comment by dykesk** [comment]
Thats interesting- we will have to compare; you are sure you have the
master branch version lf all the modules?

**Comment by dykesk** [comment]
I can no longer generate this issue - will close for now
