### ISSUE TITLE
numbering of blade dofs

### ISSUE THREAD

**Issue by arieknarie** [WISDEM/WISDEM#443]
Just for confirmation I would like to ask about the numbering/labelling of the DOFs. To the best of my understanding the label of the first degree of freedom is '0'and the last one is 'n_opt-1'.  If I want to exclude the first dof from optimization I need to set index_start to 1.  If I want to exclude the last dof from the optimization I set index_end to 'n_opt-1'.

The confusion comes from the comments in the example in the documentation and the Python convention to exclude the last element of a slice.

![image](https://user-images.githubusercontent.com/55136700/233927109-9e7b19fe-27cc-4c48-a274-060bcaf351b0.png)

**Comment by ptrbortolotti** [comment]
Good catch! Your understanding is correct, the comment is wrong. I've fixed it here https://github.com/WISDEM/WISDEM/pull/442/commits/6aeb35886b34df4dc0556dd026921ea3ba02cf63
Thanks
