### ISSUE TITLE
How to calculate wind gust velocity

### ISSUE THREAD

**Issue by SeongwooCheon** [WISDEM/WISDEM#446]
Hello,

In WISDEM, the wind gust velocity is calculated by below equation:
https://github.com/WISDEM/WISDEM/blob/9a7e811bfb7f31483682d135372f523f8110ea98/wisdem/rotorse/rotor_power.py#L121

I cannot find the paper related to this equation.
Do you have any books or reference on this formula?

**Comment by ptrbortolotti** [comment]
The screenshot is taken from the IEC 61400-1 standards

<img width="411" alt="Screenshot 2023-05-02 at 8 40 18 AM" src="https://user-images.githubusercontent.com/20641647/235700033-9f17fe7e-4bbf-4603-bdd0-5c7f8742ace6.png">

**Comment by SeongwooCheon** [comment]
thanks
