### ISSUE TITLE
Result of example 18 for comparison

### ISSUE THREAD

**Issue by arieknarie** [WISDEM/WISDEM#447]
I tried to run example 18, but it runs for a very long time/number of iterations and it is unclear to me how many iterations are required. Would it be possible for you to share the result of the converged optimization for example 18?
thanks in advance and best.
Duncan

**Comment by gbarter** [comment]
That example is essentially a full turbine design all at once, so there are many design variables and constraints all being evaluated with finite differencing.  This means it will take, many, many iterations to solve to a sufficient tolerance.  We usually run this in hours on our cluster, but would easily be an overnight effort on a desktop/laptop.  I don't have an handy convergence plot for you, as it would depend on other customizations you make to the analysis setup.

I would also note that doing a full turbine design all at once is nice when it works, but often it requires iteration on the problem formulation, which can be easier to refine component-by-component.

**Comment by arieknarie** [comment]
Thank you for your explanation.  I am still  interested in the resulting yaml file from the original example.

**Comment by gbarter** [comment]
Sorry for the long delay.  Here is the archive of output files.
[20MW_opt.zip](https://github.com/WISDEM/WISDEM/files/11524163/20MW_opt.zip)
