### ISSUE TITLE
check the design variables during the optimization

### ISSUE THREAD

**Issue by SeongwooCheon** [WISDEM/WISDEM#449]
Hello

I am optimizing the wind turbine blade with GA algorithm.
Due to expensive computational cost of GA algorithm, I want to check the optimization trend of design variables.
It is possible by checking the figure using the .sql file (see, https://github.com/WISDEM/WISDEM/issues/433#issuecomment-1510475996)
but I want to save the data used to plot the figure in the form of a .dat, .txt etc.

Is it possible to modify the original code?

**Comment by gbarter** [comment]
Once you have a plot generated, you can lookup how to save the data from Matplotlib [documentation](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.savefig.html).  If you want to save the array data itself to a text file, you can lookup Numpy's `savetxt` ([docs link](https://numpy.org/doc/stable/reference/generated/numpy.savetxt.html)).

**Comment by SeongwooCheon** [comment]
thanks
