### ISSUE TITLE
Value differences between WISDEM and OpanFAST regarding IEA-15-240 tower properties

### ISSUE THREAD

**Issue by Stephen-cby** [WISDEM/WISDEM#456]
Hi, everyone.

### 1. Tower fore-aft and side-to-side mode shape

Firstly, the coefficients of tower fore-aft and side-to-side mode shape seem different between WISDEM and OpenFAST. According to the ElastoDyn_tower.dat in IEA-15-240, which is [https://github.com/IEAWindTask37/IEA-15-240-RWT/blob/master/OpenFAST/IEA-15-240-RWT-Monopile/IEA-15-240-RWT-Monopile_ElastoDyn_tower.dat](url).
---------------------- TOWER FORE-AFT MODE SHAPES ------------------------------
0.940629055234494      TwFAM1Sh(2) - Mode 1, coefficient of x^2 term
-0.11131971295705372   TwFAM1Sh(3) -       , coefficient of x^3 term
-0.1689308438200212    TwFAM1Sh(4) -       , coefficient of x^4 term
0.9870807522447572     TwFAM1Sh(5) -       , coefficient of x^5 term
-0.6474592507021764    TwFAM1Sh(6) -       , coefficient of x^6 term
-0.4098126359223273    TwFAM2Sh(2) - Mode 2, coefficient of x^2 term
2.014615886316636      TwFAM2Sh(3) -       , coefficient of x^3 term
-3.780431497994439     TwFAM2Sh(4) -       , coefficient of x^4 term
5.518464819150487      TwFAM2Sh(5) -       , coefficient of x^5 term
-2.342836571550357     TwFAM2Sh(6) -       , coefficient of x^6 term
---------------------- TOWER SIDE-TO-SIDE MODE SHAPES --------------------------
0.9311777730302138     TwSSM1Sh(2) - Mode 1, coefficient of x^2 term
-0.09476520851076765   TwSSM1Sh(3) -       , coefficient of x^3 term
-0.2049426588352373    TwSSM1Sh(4) -       , coefficient of x^4 term
1.0275535540013145     TwSSM1Sh(5) -       , coefficient of x^5 term
-0.6590234596855233    TwSSM1Sh(6) -       , coefficient of x^6 term
-0.5122368127986152    TwSSM2Sh(2) - Mode 2, coefficient of x^2 term
2.236214062644386      TwSSM2Sh(3) -       , coefficient of x^3 term
-4.450315822523695     TwSSM2Sh(4) -       , coefficient of x^4 term
6.21339621261931       TwSSM2Sh(5) -       , coefficient of x^5 term
-2.4870576399413857    TwSSM2Sh(6) -       , coefficient of x^6 term

I used WISDEM to calculate the example files of IEA-15-240, which are [https://github.com/WISDEM/WISDEM/tree/master/examples/02_reference_turbines](url). The output file shows the results as followed:
towerse.tower.fore_aft_modes
[[   0.98112364   -0.36574182    0.31044667    0.60138556   -0.52721405]
 [  65.64572688 -130.74672104  261.70130589 -299.05388808  103.45357635]
 [ -80.2774984   112.28796382  -55.90097699  123.16569491  -98.27518335]]
towerse.tower.side_side_modes
[[   0.96678032   -0.33607275    0.24761564    0.66828939   -0.5466126 ]
 [  28.83772727  -56.98105773  115.64532483 -129.2811914    42.77919703]
 [ -76.37512479  110.44584414  -71.8957118   139.08446157 -100.25946912]]

The output file is attached. 
[refturb_output.xlsx](https://github.com/WISDEM/WISDEM/files/11854426/refturb_output.xlsx)

My question is do the values in output file of WISDEM correspond with the coefficients in ElastoDyn_tower.dat of OpenFAST. Or is three any conversion relationship between them?

### 2. Distributed tower properties

Secondly, the definition of tower distributed properties seem different between WISDEM and OpenFAST. According to the ElastoDyn_tower.dat in IEA-15-240, which is [https://github.com/IEAWindTask37/IEA-15-240-RWT/blob/master/OpenFAST/IEA-15-240-RWT-Monopile/IEA-15-240-RWT-Monopile_ElastoDyn_tower.dat](url).
---------------------- DISTRIBUTED TOWER PROPERTIES ----------------------------
  HtFract       TMassDen         TwFAStif       TwSSStif
   (-)           (kg/m)           (Nm^2)         (Nm^2)
 0.000000000000000E+00  1.031484441173360E+04  3.065446681730710E+12  3.065446681730710E+12
 1.004745490238510E-01  1.031484441173360E+04  3.065446681730710E+12  3.065446681730710E+12
 1.004822778353140E-01  9.523818531177400E+03  2.832084716093430E+12  2.832084716093430E+12
 2.009490980477020E-01  9.453084405718950E+03  2.769450452002750E+12  2.769450452002750E+12
 2.009568268591660E-01  8.761306059261840E+03  2.568166429175230E+12  2.568166429175230E+12
 3.014236470715530E-01  8.333524388530640E+03  2.210055981076240E+12  2.210055981076240E+12
 3.014313758830170E-01  7.943339505959190E+03  2.107286870484590E+12  2.107286870484590E+12
 4.018981960954040E-01  7.428459476674180E+03  1.723500010954970E+12  1.723500010954970E+12
 4.019059249068680E-01  7.087214160266680E+03  1.644879215976750E+12  1.644879215976750E+12
 5.023727451192560E-01  6.538098082624470E+03  1.291405296742770E+12  1.291405296742770E+12
 5.023804739307190E-01  6.197174861548130E+03  1.224548874057190E+12  1.224548874057190E+12
 6.028472941431070E-01  5.616516314866140E+03  9.115849751112290E+11  9.115849751112290E+11
 6.028550229545700E-01  5.253477923437150E+03  8.530980440238870E+11  8.530980440238870E+11
 7.033218431669580E-01  4.910275969995680E+03  6.965892589608760E+11  6.965892589608760E+11
 7.033295719784210E-01  4.334167603205980E+03  6.154309947959970E+11  6.154309947959970E+11
 8.037963921908090E-01  4.232816565257490E+03  5.732589718113060E+11  5.732589718113060E+11
 8.038041210022720E-01  3.673387789838780E+03  4.979639354642210E+11  4.979639354642210E+11
 9.042709412146600E-01  3.577282612388080E+03  4.598937820986930E+11  4.598937820986930E+11
 9.042786700261230E-01  4.120141253172980E+03  5.291723868157960E+11  5.291723868157960E+11
 1.000000000000000E+00  4.074837331422720E+03  5.119078821628500E+11  5.119078821628500E+11

20 nodes are usded to difine the tower.

In WISDEM, I guess only 11 nodes are used.   According to IEA-15-240-RWT.yaml in WISDEM, which is https://github.com/WISDEM/WISDEM/blob/master/examples/02_reference_turbines/IEA-15-240-RWT.yaml](url).
`    tower:
        outer_shape_bem:
            reference_axis: &id003
                x:
                    grid: [0.0, 0.10047454902385111, 0.20094909804770222, 0.30142364707155334, 0.40189819609540445, 0.5023727451192556, 0.6028472941431067, 0.7033218431669578, 0.8037963921908089, 0.90427094121466, 1.0]
                    values: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
                y:
                    grid: [0.0, 0.10047454902385111, 0.20094909804770222, 0.30142364707155334, 0.40189819609540445, 0.5023727451192556, 0.6028472941431067, 0.7033218431669578, 0.8037963921908089, 0.90427094121466, 1.0]
                    values: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
                z:
                    grid: [0.0, 0.10047454902385111, 0.20094909804770222, 0.30142364707155334, 0.40189819609540445, 0.5023727451192556, 0.6028472941431067, 0.7033218431669578, 0.8037963921908089, 0.90427094121466, 1.0]
                    values: [15.0, 28.0, 41.0, 54.0, 67.0, 80.0, 93.0, 106.0, 119.0, 132.0, 144.386]
            outer_diameter:
                grid: [0.0, 0.10047454902385111, 0.20094909804770222, 0.30142364707155334, 0.40189819609540445, 0.5023727451192556, 0.6028472941431067, 0.7033218431669578, 0.8037963921908089, 0.90427094121466, 1.0]
                values: [10.0, 10.0, 9.926, 9.443, 8.833, 8.151, 7.39, 6.909, 6.748, 6.572, 6.5]
            drag_coefficient:
                grid: [0.0, 1.0]
                values: [0.5, 0.5]
        internal_structure_2d_fem:
            outfitting_factor: 1.07
            reference_axis: *id003
            layers:
               -  name: tower_wall
                  material: steel
                  thickness:
                      grid: [0.0, 0.10047454902385111, 0.20094909804770222, 0.30142364707155334, 0.40189819609540445, 0.5023727451192556, 0.6028472941431067, 0.7033218431669578, 0.8037963921908089, 0.90427094121466, 1.0]
                      values: [0.039496, 0.039496, 0.033416, 0.034142, 0.030242, 0.031174, 0.027028, 0.027398, 0.02062, 0.021032, 0.026964]
`
I want to change the value of diameter and thickness of tower. Please share any suggestion for me how to switch 11-nodes definition to 20-nodes definition. What is the relatioship between distributed tower properties of OpenFAST and WIDEM.

**Comment by gbarter** [comment]
@Stephen-cby : Yes, things should be the same and it looks like the differences are small (likely in the noise).

The IEA Wind 15MW repository has seen some small tweaks to the tower-monopile definition over the recent minor releases (see the [release notes](https://github.com/IEAWindTask37/IEA-15-240-RWT/blob/master/ReleaseNotes.md)).  The updated YAML input file from that repository has not yet been copied over to the WISDEM repository.  If you want to do that manually, just copy [this file](https://github.com/IEAWindTask37/IEA-15-240-RWT/blob/master/WT_Ontology/IEA-15-240-RWT.yaml) into [this directory](https://github.com/WISDEM/WISDEM/tree/master/examples/02_reference_turbines).

**Comment by Stephen-cby** [comment]
Dear @gbarter,

Thanks for your help. I have copied the newest version of YAML input file from IEA-15-240 to WISDEM. I agree that the differences of tower Mode 1's coefficients between OpenFAST and WISDEM are small.

Regaring the Mode 2 of TOWER FORE-AFT and SIDE-TO-SIDE  MODE SHAPES, they seem much different between WISDEM and Openfast. I apology that I do not know if it is right to compare the Mode 2 data in OpenFAST with the second row data of towerse.tower.fore_aft_modes and towerse.tower.side_side_modes in WISDEM.

The coefficent of Mode 2 in ElastoDyn_tower.dat in OpenFAST.
---------------------- TOWER FORE-AFT MODE SHAPES ------------------------------
-0.4098126359223273    TwFAM2Sh(2) - Mode 2, coefficient of x^2 term
2.014615886316636      TwFAM2Sh(3) -       , coefficient of x^3 term
-3.780431497994439     TwFAM2Sh(4) -       , coefficient of x^4 term
5.518464819150487      TwFAM2Sh(5) -       , coefficient of x^5 term
-2.342836571550357     TwFAM2Sh(6) -       , coefficient of x^6 term
---------------------- TOWER SIDE-TO-SIDE MODE SHAPES --------------------------
-0.5122368127986152    TwSSM2Sh(2) - Mode 2, coefficient of x^2 term
2.236214062644386      TwSSM2Sh(3) -       , coefficient of x^3 term
-4.450315822523695     TwSSM2Sh(4) -       , coefficient of x^4 term
6.21339621261931       TwSSM2Sh(5) -       , coefficient of x^5 term
-2.4870576399413857    TwSSM2Sh(6) -       , coefficient of x^6 term

The outcome of modes in WISDEM. The output file is attached here. 
[refturb_output.xlsx](https://github.com/WISDEM/WISDEM/files/11861745/refturb_output.xlsx)

Second row data in _towerse.tower.fore_aft_modes_:
 [ 6.87210090e+01 -1.35574361e+02  2.70133071e+02 -3.09220897e+02 1.06941178e+02]

Second row data in _towerse.tower.side_side_modes_:
 [  28.89845741  -56.40186313  113.92014557 -127.42941847   42.01267861]

**Comment by gbarter** [comment]
@Stephen-cby : The WISDEM output of `towerse.tower.fore_aft_modes` is appropriate for land-based towers.  For towers sitting on top of monopiles, you have to look at `fixedse.tower_fore_aft_modes`.  For that output, I see the second row / mode shape coefficients of:
[ -0.37316491,   2.10415959,  -4.09462896,   5.86254156,  -2.49890728]
Again, there are small differences with the OpenFAST model.

Regardless, you have a identified a shortcoming in that we didn't update the OpenFAST mode shape coefficients with the minor geometry correction we recently pushed through.

**Comment by Stephen-cby** [comment]
Dear @gbarter,

Thanks for your help. The mode shape coefficients have become clear for me.

I am interested in the tower top displacement. Is `towerse.tower.top_deflection` should I check? Or other output name?
