### ISSUE TITLE
Installation problems using anaconda on windows 11

### ISSUE THREAD

**Issue by juanjohasbun** [WISDEM/WISDEM#457]
## Description
I am following the instructions for installation using an anaconda power shell. I added conda-forge to the channels (re-checked using conda config --show channels), but when I try to create the environment I get the following output:

```
conda create --name wisdem-env -f https://raw.githubusercontent.com/WISDEM/WISDEM/master/environment.yml python=3.10
Collecting package metadata (current_repodata.json): \ DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): repo.anaconda.com:443
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): repo.anaconda.com:443
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): repo.anaconda.com:443
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): repo.anaconda.com:443
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): repo.anaconda.com:443
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): repo.anaconda.com:443
\ DEBUG:urllib3.connectionpool:https://repo.anaconda.com:443 "GET /pkgs/msys2/win-64/current_repodata.json HTTP/1.1" 304 0
| DEBUG:urllib3.connectionpool:https://repo.anaconda.com:443 "GET /pkgs/msys2/noarch/current_repodata.json HTTP/1.1" 304 0
DEBUG:urllib3.connectionpool:https://repo.anaconda.com:443 "GET /pkgs/main/win-64/current_repodata.json HTTP/1.1" 304 0
DEBUG:urllib3.connectionpool:https://repo.anaconda.com:443 "GET /pkgs/main/noarch/current_repodata.json HTTP/1.1" 304 0
/ DEBUG:urllib3.connectionpool:https://repo.anaconda.com:443 "GET /pkgs/r/noarch/current_repodata.json HTTP/1.1" 304 0
DEBUG:urllib3.connectionpool:https://repo.anaconda.com:443 "GET /pkgs/r/win-64/current_repodata.json HTTP/1.1" 304 0
done
Solving environment: unsuccessful attempt using repodata from current_repodata.json, retrying with next repodata source.
Collecting package metadata (repodata.json): - DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): repo.anaconda.com:443
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): repo.anaconda.com:443
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): repo.anaconda.com:443
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): repo.anaconda.com:443
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): conda.anaconda.org:443
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): repo.anaconda.com:443
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): conda.anaconda.org:443
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): repo.anaconda.com:443
\ DEBUG:urllib3.connectionpool:https://repo.anaconda.com:443 "GET /pkgs/r/win-64/repodata.json HTTP/1.1" 304 0
DEBUG:urllib3.connectionpool:https://repo.anaconda.com:443 "GET /pkgs/msys2/win-64/repodata.json HTTP/1.1" 304 0
DEBUG:urllib3.connectionpool:https://repo.anaconda.com:443 "GET /pkgs/msys2/noarch/repodata.json HTTP/1.1" 304 0
| DEBUG:urllib3.connectionpool:https://conda.anaconda.org:443 "GET /conda-forge/win-64/repodata.json HTTP/1.1" 200 None
/ DEBUG:urllib3.connectionpool:https://conda.anaconda.org:443 "GET /conda-forge/noarch/repodata.json HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://repo.anaconda.com:443 "GET /pkgs/r/noarch/repodata.json HTTP/1.1" 304 0
DEBUG:urllib3.connectionpool:https://repo.anaconda.com:443 "GET /pkgs/main/noarch/repodata.json HTTP/1.1" 304 0
- DEBUG:urllib3.connectionpool:https://repo.anaconda.com:443 "GET /pkgs/main/win-64/repodata.json HTTP/1.1" 304 0
done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - //raw.githubusercontent.com/wisdem/wisdem/master/environment.yml

Current channels:

  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch
  - https://conda.anaconda.org/conda-forge/win-64
  - https://conda.anaconda.org/conda-forge/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

```
I have searched for the PackagesNotFoundError with conda but I keep getting the suggestion to check whether my channels are well set. Could you help me out?

Thank you in advance.

**Comment by gbarter** [comment]
It seems as though every month, the `conda` command struggles more and more.  We have switched to using `mamba` for all of our Anaconda package management and commands.  My first suggestion is to start with that, using the Mambaforge install packages [here](https://github.com/conda-forge/miniforge#mambaforge).  If you still have "Solving environment: failed" errors, let me know.

**Comment by juanjohasbun** [comment]
Thanks for the quick reply, apparently mamba can't find the environment.yml? Thanks for your support

`
mamba create --name wisdem-env -f https://raw.githubusercontent.com/WISDEM/WISDEM/master/environment.yml python=3.10

                  __    __    __    __
                 /  \  /  \  /  \  /  \
                /    \/    \/    \/    \
███████████████/  /██/  /██/  /██/  /████████████████████████
              /  / \   / \   / \   / \  \____
             /  /   \_/   \_/   \_/   \    o \__,
            / _/                       \_____/  `
            |/
        ███╗   ███╗ █████╗ ███╗   ███╗██████╗  █████╗
        ████╗ ████║██╔══██╗████╗ ████║██╔══██╗██╔══██╗
        ██╔████╔██║███████║██╔████╔██║██████╔╝███████║
        ██║╚██╔╝██║██╔══██║██║╚██╔╝██║██╔══██╗██╔══██║
        ██║ ╚═╝ ██║██║  ██║██║ ╚═╝ ██║██████╔╝██║  ██║
        ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═════╝ ╚═╝  ╚═╝

        mamba (1.4.2) supported by @QuantStack

        GitHub:  https://github.com/mamba-org/mamba
        Twitter: https://twitter.com/QuantStack

█████████████████████████████████████████████████████████████


Looking for: ['//raw.githubusercontent.com/wisdem/wisdem/master/environment.yml', 'python=3.10']

conda-forge/noarch                                  13.8MB @   3.8MB/s  5.2s
conda-forge/win-64                                  21.7MB @   3.8MB/s  8.4s
Could not solve for environment specs
The following package could not be installed
└─ //raw.githubusercontent.com/wisdem/wisdem/master/environment.yml   does not exist (perhaps a typo or a missing chann.
`

**Comment by gbarter** [comment]
Hello,

I can confirm that the command still works.  Are you sure you pasted it in correctly and that your network is working from the terminal?  From the error message, `//raw.githubusercontent.com/wisdem/wisdem/master/environment.yml does not exist`, maybe the `https` was missing?

**Comment by juanjohasbun** [comment]
The https is definitely there when I type the command, but it is gone when the error pops up.. just to check I downloaded the yml and tried to create the environment using the local file: still get the same error.. I made a quick online search but did not find possible reasons... any ideas?
thank you in advance

**Comment by gbarter** [comment]
If using a local file, be sure that the file is in the same directory as your current working directory in the command prompt:
```
cd /path-to-environment-file
mamba env create -f environment.yml
```
If that doesn't work, you can always create the environment and add the packages by name
```
mamba create --name wisdem-env
mamba activate wisdem-env
mamba install coveralls cython git jsonschema make matplotlib...
```
A final option is to just `mamba install wisdem`, which is fine if you don't anticipate needing or wanting to make any tweaks to the source code.

**Comment by juanjohasbun** [comment]
Thanks for your support, turns out the problem was I was always typing `mamba create` instead of `mamba env create`, because I read in stack-overflow that the "new" command was just `conda create`.. now mamba seems to do the trick.. thank you very much!
