### ISSUE TITLE
ScipyOptimizeDriver: Constraint '****' does not depend on any design variables. Please check your problem formulation

### ISSUE THREAD

**Issue by mftatfcyclone** [WISDEM/WISDEM#458]
## Description
The new release of openmdao 3.28.0 (Aug. 31st 2023) has introduced a new relevance check for the dependency of constraints on the design variables. So, when constraints are not dependent on any design vars, make that an error instead of a warning.
Consequently, I can not run many of the examples of WISDEM. More information can be found [here.](https://github.com/OpenMDAO/OpenMDAO/issues/2980)

### Steps to reproduce issue
1. Start a clean installation of wisdem 3.10.1 as described [here](https://wisdem.readthedocs.io/en/master/installation.html)
2. Ensure you have the latest version of openmdao which is 3.28.0
3. Run any example ex: 03_blade, or  05_tower_monopile

### Current behavior
The following error is generated when running example with python driver file "03_blade":
"RuntimeError: ScipyOptimizeDriver: Constraint 'wt.rotorse.stall_check.no_stall_constraint' does not depend on any design variables. Please check your problem formulation."

### Expected behavior
To solve this problem I had to install openmdao v3.27.0 and the example was running as expected

### Code versions
Working environment: Linux Manjaro XFCE 4.18 x64 rolling kernel 6.5.1-1-MANJARO
WISDEM: v3.10.1
Python: v3.11.5
OpenMDAO: v3.28.0
![error](https://github.com/WISDEM/WISDEM/assets/35344195/00d7062d-c6da-4e5e-b437-3304dcc79fe4)

**Comment by gbarter** [comment]
Thank you for bringing this to our attention.  This is definitely an issue that needs to be resolved ASAP.

**Comment by gbarter** [comment]
I have filed the issue with the OpenMDAO team [here](https://github.com/OpenMDAO/OpenMDAO/issues/3026).

In the meantime, you will have to downgrade OpenMDAO back to v3.27.  Is that something you are comfortable with?

**Comment by mftatfcyclone** [comment]
Thank you for prompt reply.
Yes, I already downgrade my OPENMDAO to v3.27.

**Comment by gbarter** [comment]
The most recent version of OpenMDAO (v3.31) should fix this
