### ISSUE TITLE
Error about precomp.py When Run compare_designs.py

### ISSUE THREAD

**Issue by Tang960** [WISDEM/WISDEM#464]
Hello!
  When I used the reslut of examples/03_balde to run the command:
      compare_designs BAR_USC.yaml outputs_aero/blade_out.yaml --labels Init Opt
The error occurred: 
     AttributeError: 'wt.rotorse.re.precomp' <class RunPreComp>: Error calling compute(), module 'wisdem.rotorse.precomp' has no attribute 'tw_rate'
And when I commented out the related line, something else happened:
    AttributeError: 'wt.rotorse.re.precomp' <class RunPreComp>: Error calling compute(), module 'wisdem.rotorse.precomp' has no attribute 'properties'
  I downloaded WISDEM rensently, but I guess there is a problem with the code. Can you help me?
  Thanks

**Comment by gbarter** [comment]
Can you be sure that you are consistent with the `master` branch?  There was a series of bug-fixes a couple of weeks ago.  I cannot replicate your error.

**Comment by Tang960** [comment]
Hello, gbarter
  Thank you for your reply. According to your suggestion, I updated the version of WISDEM and ran compare_designs to get the result, which is a table comparing the main information of the wind turbine before and after optimization. I wonder how to get  figures such as Fig.1 and Fig.2 at https://wisdem.readthedocs.io/en/master/examples/blade/tutorial.html#fig-opt1-induction. Is there any source code for these diagrams for reference?
  Thanks

**Comment by gbarter** [comment]
So you were able to run without an error?  The `compare_designs` script should have created and saved a number of figures similar to the one you linked to.  Please check the directories where you ran the script.

**Comment by ptrbortolotti** [comment]
you should have these figures in the output folder where you've run compare_designs

**Comment by Tang960** [comment]
Hello,  gbarter
  The results I ran "compare_designs BAR_USC.yaml outputs_aero/blade_out.yaml --labels Init Opt" in the terminal are as follows. I didn't find any figures.

Running WISDEM for BAR_USC.yaml.
==
wt
==
NL: NLBGS 1 ; 3.88821874e+12 1
NL: NLBGS 2 ; 48311072.4 1.24249883e-05
NL: NLBGS 3 ; 0 0
NL: NLBGS Converged
FutureWarning: e:\wisdem\wisdem\landbosse\model\FoundationCost.py:663
The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.FutureWarning: e:\wisdem\wisdem\la
ndbosse\model\SitePreparationCost.py:362
The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.FutureWarning: e:\wisdem\wisdem\la
ndbosse\model\SitePreparationCost.py:362
The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.FutureWarning: e:\wisdem\wisdem\la
ndbosse\model\SitePreparationCost.py:657
The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.FutureWarning: e:\wisdem\wisdem\la
ndbosse\model\CollectionCost.py:847
The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.FutureWarning: e:\wisdem\wisdem\la
ndbosse\model\DevelopmentCost.py:76
Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`FutureWarning: e:\wisdem\wisdem\landbosse\model\ErectionCost.py:695
The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.FutureWarning: e:\wisdem\wisdem\la
ndbosse\model\ErectionCost.py:1224
Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`FutureWarning: e:\wisdem\wisdem\landbosse\model\ErectionCost.py:256
Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`FutureWarning: e:\wisdem\wisdem\landbosse\model\ErectionCost.py:262
Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`FutureWarning: e:\wisdem\wisdem\landbosse\model\ErectionCost.py:266
Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`FutureWarning: e:\wisdem\wisdem\landbosse\model\ErectionCost.py:272
Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`FutureWarning: e:\wisdem\wisdem\landbosse\model\ErectionCost.py:276
Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`FutureWarning: e:\wisdem\wisdem\landbosse\model\ErectionCost.py:282
Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`FutureWarning: e:\wisdem\wisdem\landbosse\model\ManagementCost.py:370
Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead########################################
Objectives
Turbine AEP: 24.3487187688 GWh
Blade Mass:  50972.3711777633 kg
LCOE:        36.6719273464 USD/MWh
Tip Defl.:   14.5601135853 m
########################################

Loading WISDEM data for outputs_aero/blade_out.yaml.
+----------------------------------------------------------------------+
|          Comparison between WISDEM results from yaml files           |
+----------------------------------------------------------------------+
| Data name       | Init            | Opt             | Units          |
+----------------------------------------------------------------------+
| Rotor Diameter  |       206.00000 |       206.00000 | m              |
| TSR             |        10.50000 |        10.50000 | None           |
| AEP             |        24.34872 |        24.58806 | GW*h           |
| LCOE            |        36.67193 |        36.30643 | USD/(MW*h)     |
| Rated velocity  |         8.97148 |         8.44915 | m/s            |
| Rated rpm       |         7.89381 |         7.89381 | rpm            |
| Rated pitch     |         0.00000 |         0.00000 | deg            |
| Rated thrust    |       840.80510 |      1059.68626 | kN             |
| Rated torque    |      6702.04870 |      6702.05195 | kN*m           |
| Blade mass      |     50972.37118 |     50882.74532 | kg             |
| Tip defl        |        14.56011 |        15.26746 | m              |
| Tip defl ratio  |         1.10213 |         1.15568 | None           |
| Flap freqs_0    |         0.58383 |         0.58519 | Hz             |
| Flap freqs_1    |         1.64915 |         1.64849 | Hz             |
| Flap freqs_2    |         3.29410 |         3.24395 | Hz             |
| Flap freqs_3    |         7.40323 |         7.42105 | Hz             |
| Flap freqs_4    |        10.50803 |        10.53644 | Hz             |
| Edge freqs_0    |         0.88790 |         0.88535 | Hz             |
| Edge freqs_1    |         2.68944 |         2.72963 | Hz             |
| Edge freqs_2    |         4.75308 |         4.80276 | Hz             |
| Edge freqs_3    |         5.73296 |         5.66940 | Hz             |
| Edge freqs_4    |         9.77995 |         9.75671 | Hz             |
| 3P freq         |         0.39469 |         0.39469 | None           |
| 6P freq         |         0.78938 |         0.78938 | None           |
| Nacelle mass    |    222304.89027 |    222304.73418 | kg             |
| RNA mass        |    410360.26575 |    410175.48644 | kg             |
| Tower mass      |    791445.95808 |    791445.95808 | kg             |
| Tower cost      |   2148240.64008 |   2148240.64008 | USD            |
| Tower freqs_0   |         0.20796 |         0.20801 | Hz             |
| Tower freqs_1   |         0.21038 |         0.21043 | Hz             |
| Tower freqs_2   |         0.78232 |         0.78258 | Hz             |
| Tower freqs_3   |         0.98965 |         0.98985 | Hz             |
| Tower freqs_4   |         1.14718 |         1.14740 | Hz             |
| Tower freqs_5   |         2.32153 |         2.32173 | Hz             |
+----------------------------------------------------------------------+

**Comment by gbarter** [comment]
The files are there somewhere.  When I tested things out and ran the `compare_designs` script, it created a new `outputs` folder in the directory where it was run and put the figure files there.  Maybe check in your `examples/03_blade` directory for an `outputs` folder.

**Comment by Tang960** [comment]
Hello, gbarter
    Thank you for your help. I have found figure files in  the folder.
