### ISSUE TITLE
Depend on upstream ruamel.yaml instead of unmaintained ruamel_yaml

### ISSUE THREAD

**Issue by mbargull** [WISDEM/WISDEM#471]
# Description of feature
I'm currently looking at what packages on conda-forge have a dependency on the non-maintained `ruamel_yaml` package.

It'd be good if we could have this package depend on `ruamel.yaml` instead of `ruamel_yaml`, too.

NB: The latest `conda-forge::ruamel_yaml` is still at version `0.15.80` -- upstream released that version 5 years ago.

# Potential solution
AFAICT, https://github.com/WISDEM/WISDEM/blob/v3.11.1/wisdem/inputs/validation.py#L6-L12 is the only place in WISDEM that imports `ruamel_yaml`.
With the `ruamel.yaml` fallback in place, we should be able to just swap out the `ruamel_yaml` in the recipe without issue.
My suggestion would be to remove the `ruamel_yaml` import completely as just use `ruamel.yaml` -- or, as a second to best solution, use `ruamel_yaml` as the fallback and try to import `ruamel.yaml` first.

----
xref: https://github.com/conda-forge/wisdem-feedstock/issues/39

**Comment by gbarter** [comment]
Just realized that I never responded here.  Thank you for pointing this out and the issue has been addressed.
