### ISSUE TITLE
Variable Documentation & Missing / Mislabeled Variables

### ISSUE THREAD

**Issue by SoundsSerious** [WISDEM/WISDEM#477]
Hi

Big fan of WISDEM! its helping alot with some NSF research I'm doing outside of a major institution. 

I'm finding the documentation to be very helpful to understand the general concepts in modules, however I was looking for something more along the lines of a list of variables. I did find `docs/docstrings/variable_guide.csv` and think it would be great if you could put this in a .md file on github or as a section in the documentation that would go along way to helping to understand the example files (for the drivetrain / generator in my case).

There are a few variables such as `drivese.generator.B_g` which doesn't appear to be used in the code, or `drivese.generator.h_sr` which appears to be labeled structural mass however is used to calculate the `R_out or Outer Radius`. 

You've built a wonderful tool, however it is hard for someone outside of the research community to completely understand what is going on in the examples or even with the documentation.

A couple of ideas to improve adoption and usability.
1. put the variable list in the documentation online that would be a great first step
2. run a script (perhaps using the `n2` diagram code) to interrogate the codebase for variables not in the list or variables in the list that are no longer used.
3. make a publicly comment-able google sheet (or equivalent) so folks like me can ask questions and collab on the documentation.

Thanks!

**Comment by gbarter** [comment]
Thank you for the kind words and suggestions.  The variable table is markdown is probably doable.

Is your core interest the generator models?  The variables are indeed tougher to track and understand with some of the global variables only used in some of the generator models but not others.  Many of the variable names follow diagrams in [this report](https://www.osti.gov/biblio/1395455), which might be helpful to you.

We have also recently dabbled in a slightly higher fidelity generator design approach wrapped around the [FEMM](https://www.femm.info/wiki/HomePage) tool, but we haven't connect it to the rest of WISDEM quite yet (and might keep it separate regardless).  You can explore this a little bit in this [repository](https://github.com/WISDEM/GeneratorSE) and these [two](https://www.sciencedirect.com/science/article/pii/S0306261923006360) [reports](https://ieeexplore.ieee.org/abstract/document/10239029).

**Comment by gbarter** [comment]
Thank you for the context and good luck with the project.  Let us know when future questions arise.
