### ISSUE TITLE
mpi4py package wisdem conda/mamba installation message

### ISSUE THREAD

**Issue by mikilosta** [WISDEM/WISDEM#482]
## Description
I am installing wisdem following the steps in the installation guide (https://wisdem.readthedocs.io/en/latest/installation.html).
I am using mamba via the Miniforge distribution.
After installing the packages I get this comment regarding the mpi4py package:

C:\Users\user>if not "" == "" (
set "MSMPI_BIN="
 set "MSMPI_BIN_CONDA_BACKUP="
)  else (set "MSMPI_BIN=" )

C:\Users\user>if not "" == "" (
set "MSMPI_INC="
 set "MSMPI_INC_CONDA_BACKUP="
)  else (set "MSMPI_INC=" )

C:\Users\user>if not "" == "" (
set "MSMPI_LIB64="
 set "MSMPI_LIB64_CONDA_BACKUP="
)  else (set "MSMPI_LIB64=" )

C:\Users\user>if not """" == "" (
set "MSMPI_LIB32="""
 set "MSMPI_LIB32_CONDA_BACKUP="
)

is this something expected? I think it is related with compatibility issues with the latest version of mpi4py(?) I just want to double check.

If starting a new mamba environment with python 3.10:
mamba install mpi4pi
this does install mpi, mpi4pi and msmpi, but I still get the same message.

I guess that as mpi is for multiprocessing wisdem would still run, but I am worried it would do it much slower(?)

Thanks for your time! :)

**Comment by gbarter** [comment]
`mpi4py` wraps around an existing mpi installation that you have locally and is only needed on HPC clusters.  You can leave it out of your environment and WISDEM should work just fine.

**Comment by mikilosta** [comment]
Alright.
Many thanks, I'll do that then and report if any issues :) 
Mik
