### ISSUE TITLE
error when running RotorSE with IEA RWT 

### ISSUE THREAD

**Issue by emmwind** [WISDEM/WISDEM#492]
Hi, 

I am trying to run RotorSE using the geometry file for the IEA RWT that is in the example folder 02.  I have everything except for RotorSE in the modelling file set to "False". I am not running an optimization, i.e. I have an "empty" analysis file. 

However, I am getting this error:
KeyError: '<model> <class WindPark>: Variable "tcons.max_allowable_td_ratio" not found.'

Attached are the input files I am using. 

[analysis_options.txt](https://github.com/WISDEM/WISDEM/files/14373903/analysis_options.txt)
[IEA-3.4-130-RWT.txt](https://github.com/WISDEM/WISDEM/files/14373905/IEA-3.4-130-RWT.txt)
[modeling_options.txt](https://github.com/WISDEM/WISDEM/files/14373907/modeling_options.txt)

**Comment by emmwind** [comment]
I am not getting this error, if I turn all the "False" in my modeling_options file to "True". But I only want to run the RotorSE, not DrivetrainSE, TowerSE etc, is that not possible?

**Comment by gbarter** [comment]
Thank you for raising this issue!  This was indeed a bug that has been addressed in a PR to the develop-branch (#493).  Are you comfortable switching to the develop branch or would you need some guidance?

**Comment by emmwind** [comment]
Thank you! I'll give it a go, and let you know if I run into any trouble.

**Comment by emmwind** [comment]
I think I got it to work, but I have a follow up question. If I then want to run the TowerSE module (I am running them separately to get a better understanding), can I in the output file from RotorSE find all data to go into "Loading" in the modeling_options file? I am specififcally thinking of the loads, do I get them from RotorSE or do I need to define them myself?

**Comment by gbarter** [comment]
Yes, we do this all the time and you have identified the right procedure.  I would recommend running the full turbine to get the tower loading though, as DrivetrainSE will properly include nacelle mass properties and compute the loads at the tower top.  You can find the quantities you need in the following outputs:

- `drivese.rna_mass`
- `drivese.rna_cm`
- `drivese.rna_I_TT`
- `drivese.base_F`
- `drivese.base_M`
- `rotorse.rp.gust.V_gust`

**Comment by emmwind** [comment]
Perfect, thank you. I was a bit confused because if I run an optimization of the tower with those inputs, it reduces its weight with more than half from the original IEA RWT design (from ~640 ton to ~224 ton), by reducing the wall thickness a lot. But maybe that has to do with my choice of constraints then.

**Comment by gbarter** [comment]
The tower design is extremely sensitive to constraints on the natural frequency.  That is my guess for the discrepancy.

**Comment by emmwind** [comment]
I see, I did a quick test run now of TowerSE where I put the frequency_1 constraint so that it matched the tower frequency output when running a base case (RotorSE + DrivetrainSE + TowerSE, no optimization), and the result was much more reasonable. Thanks for your help.
