### ISSUE TITLE
installation issues on different OS

### ISSUE THREAD

**Issue by dykesk** [WISDEM/WISDEM#5]
update installation for WISDEM, pBEAM, RotorSE to accomodate the issues associated with boost libraries and lapack etc

**Comment by codenamenikky** [comment]
Katherine , i am having the below issues when trying to install WISDEM and i think I Failed to install:  ['akima', 'CCBlade', 'RotorSE', 'pyFrame3DD', 'pBEAM'] so i tried to install them in the interactive session and downloaded the MSVC it was requesting but then around error popped up so i was wondering if there is a way to solve this please let me know if this makes sense. 


---------------------------------------------------------------------------------------------------------------------------
writing dependency_links to src\WISDEM.egg-info\dependency_links.txt
writing manifest file 'src\WISDEM.egg-info\SOURCES.txt'
reading manifest file 'src\WISDEM.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files matching 'openmdao_log.txt' found anywhere
 in distribution
writing manifest file 'src\WISDEM.egg-info\SOURCES.txt'
running build_ext
Creating c:\openmdao\openmdao-0.12.0\lib\site-packages\WISDEM.egg-link (link to
src)
Adding WISDEM 0.1.1 to easy-install.pth file

Installed c:\wisdem-master\src


Attempted to install WISDEM and its sub-plugins:  ['Turbine_CostsSE', 'CommonSE'
, 'Plant_CostsSE', 'Plant_FinanceSE', 'Plant_EnergySE', 'AeroelasticSE', 'Airfoi
lPreppy', 'CCBlade', 'DriveSE', 'DriveWPACT', 'NREL_CSM', 'RotorSE', 'TowerSE',
'pyFrame3DD', 'pBEAM', 'JacketSE']
Failed to install:  ['akima', 'CCBlade', 'RotorSE', 'pyFrame3DD', 'pBEAM']

(openmdao-0.12.0) C:\WISDEM-master>python setup_all.py
Traceback (most recent call last):
  File "setup_all.py", line 3, in <module>
    include_dirs=[join(path, 'pBEAM'), 'C:/boost_1_55_0/boost_1_55_0'],
NameError: name 'join' is not defined

(openmdao-0.12.0) C:\WISDEM-master>python setup_all.py
Traceback (most recent call last):
  File "setup_all.py", line 3, in <module>
    include_dirs=[''.join(path, 'pBEAM'), 'C:/boost_1_55_0/boost_1_55_0'],
NameError: name 'path' is not defined

(openmdao-0.12.0) C:\WISDEM-master>cd plugins\pBEAM

(openmdao-0.12.0) C:\WISDEM-master\plugins\pBEAM>python setup.py
========================================================================
Starting interactive session
------------------------------------------------------------------------

Tasks:
  i       - Show python/platform/machine information
  ie      - Show environment information
  c       - Show C compilers information
  c<name> - Set C compiler (current:None)
  f       - Show Fortran compilers information
  f<name> - Set Fortran compiler (current:None)
  e       - Edit proposed sys.argv[1:].

Task aliases:
  0         - Configure
  1         - Build
  2         - Install
  2<prefix> - Install with prefix.
  3         - Inplace build
  4         - Source distribution
  5         - Binary distribution

Proposed sys.argv = ['setup.py']

Choose a task (^D to quit, Enter to continue with setup):
------------------------------------------------------------------------
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: no commands supplied
------------------------------------------------------------------------
Press ENTER to close the interactive session..
========================================================================

(openmdao-0.12.0) C:\WISDEM-master\plugins\pBEAM>python setup.py
========================================================================
Starting interactive session
------------------------------------------------------------------------

Tasks:
  i       - Show python/platform/machine information
  ie      - Show environment information
  c       - Show C compilers information
  c<name> - Set C compiler (current:None)
  f       - Show Fortran compilers information
  f<name> - Set Fortran compiler (current:None)
  e       - Edit proposed sys.argv[1:].

Task aliases:
  0         - Configure
  1         - Build
  2         - Install
  2<prefix> - Install with prefix.
  3         - Inplace build
  4         - Source distribution
  5         - Binary distribution

Proposed sys.argv = ['setup.py']

Choose a task (^D to quit, Enter to continue with setup): 2


Tasks:
  i       - Show python/platform/machine information
  ie      - Show environment information
  c       - Show C compilers information
  c<name> - Set C compiler (current:None)
  f       - Show Fortran compilers information
  f<name> - Set Fortran compiler (current:None)
  e       - Edit proposed sys.argv[1:].

Task aliases:
  0         - Configure
  1         - Build
  2         - Install
  2<prefix> - Install with prefix.
  3         - Inplace build
  4         - Source distribution
  5         - Binary distribution

Proposed sys.argv = ['setup.py', 'install']

Choose a task (^D to quit, Enter to continue with setup):
------------------------------------------------------------------------
running install
C:\OpenMDAO\openmdao-0.12.0\lib\site-packages\setuptools-12.0.5-py2.7.egg\pkg_re
sources\__init__.py:2510: PEP440Warning: 'pytz (2011k)' is being parsed as a leg
acy, non PEP 440, version. You may find odd behavior and sort order. In particul
ar it will be sorted as less than 0.0. It is recommend to migrate to PEP 440 com
patible versions.
running bdist_egg
running egg_info
running build_src
build_src
building extension "_pBEAM" sources
build_src: building npy-pkg config files
writing pBEAM.egg-info\PKG-INFO
writing top-level names to pBEAM.egg-info\top_level.txt
writing dependency_links to pBEAM.egg-info\dependency_links.txt
reading manifest file 'pBEAM.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'CHANGELOG.md'
warning: no directories found matching 'docs\_build\html'
warning: no directories found matching 'test'
writing manifest file 'pBEAM.egg-info\SOURCES.txt'
installing library code to build\bdist.win32\egg
running install_lib
running build_ext
No module named msvccompiler in numpy.distutils; trying from distutils
customize MSVCCompiler
customize MSVCCompiler using build_ext
No module named msvccompiler in numpy.distutils; trying from distutils
customize MSVCCompiler
Missing compiler_cxx fix for MSVCCompiler
customize MSVCCompiler using build_ext
building '_pBEAM' extension
compiling C sources
error: Microsoft Visual C++ 9.0 is required (Unable to find vcvarsall.bat). Get
it from http://aka.ms/vcpython27
------------------------------------------------------------------------
Press ENTER to close the interactive session..
========================================================================

(openmdao-0.12.0) C:\WISDEM-master\plugins\pBEAM>python setup.py
========================================================================
Starting interactive session
------------------------------------------------------------------------

Tasks:
  i       - Show python/platform/machine information
  ie      - Show environment information
  c       - Show C compilers information
  c<name> - Set C compiler (current:None)
  f       - Show Fortran compilers information
  f<name> - Set Fortran compiler (current:None)
  e       - Edit proposed sys.argv[1:].

Task aliases:
  0         - Configure
  1         - Build
  2         - Install
  2<prefix> - Install with prefix.
  3         - Inplace build
  4         - Source distribution
  5         - Binary distribution

Proposed sys.argv = ['setup.py']

Choose a task (^D to quit, Enter to continue with setup): 2


Tasks:
  i       - Show python/platform/machine information
  ie      - Show environment information
  c       - Show C compilers information
  c<name> - Set C compiler (current:None)
  f       - Show Fortran compilers information
  f<name> - Set Fortran compiler (current:None)
  e       - Edit proposed sys.argv[1:].

Task aliases:
  0         - Configure
  1         - Build
  2         - Install
  2<prefix> - Install with prefix.
  3         - Inplace build
  4         - Source distribution
  5         - Binary distribution

Proposed sys.argv = ['setup.py', 'install']

Choose a task (^D to quit, Enter to continue with setup):
------------------------------------------------------------------------
running install
C:\OpenMDAO\openmdao-0.12.0\lib\site-packages\setuptools-12.0.5-py2.7.egg\pkg_re
sources\__init__.py:2510: PEP440Warning: 'pytz (2011k)' is being parsed as a leg
acy, non PEP 440, version. You may find odd behavior and sort order. In particul
ar it will be sorted as less than 0.0. It is recommend to migrate to PEP 440 com
patible versions.
running bdist_egg
running egg_info
running build_src
build_src
building extension "_pBEAM" sources
build_src: building npy-pkg config files
writing pBEAM.egg-info\PKG-INFO
writing top-level names to pBEAM.egg-info\top_level.txt
writing dependency_links to pBEAM.egg-info\dependency_links.txt
reading manifest file 'pBEAM.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'CHANGELOG.md'
warning: no directories found matching 'docs\_build\html'
warning: no directories found matching 'test'
writing manifest file 'pBEAM.egg-info\SOURCES.txt'
installing library code to build\bdist.win32\egg
running install_lib
running build_ext
No module named msvccompiler in numpy.distutils; trying from distutils
customize MSVCCompiler
customize MSVCCompiler using build_ext
No module named msvccompiler in numpy.distutils; trying from distutils
customize MSVCCompiler
Missing compiler_cxx fix for MSVCCompiler
customize MSVCCompiler using build_ext
building '_pBEAM' extension
compiling C sources
creating build
creating build\temp.win32-2.7
creating build\temp.win32-2.7\Release
creating build\temp.win32-2.7\Release\src
creating build\temp.win32-2.7\Release\src\pBEAM
creating build\temp.win32-2.7\Release\src\pyBEAM
C:\Users\nikhil.kondabala\AppData\Local\Programs\Common\Microsoft\Visual C++ for
 Python\9.0\VC\Bin\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -Isrc\pBEAM -IC:/
boost_1_55_0/boost_1_55_0 -Ic:\python27\arcgis10.1\lib\site-packages\numpy\core\
include -IC:\Python27\ArcGIS10.1\include -IC:\OpenMDAO\openmdao-0.12.0\PC /Tpsrc
\pBEAM\Poly.cpp /Fobuild\temp.win32-2.7\Release\src\pBEAM\Poly.obj -O2 /Zm1000
Found executable C:\Users\nikhil.kondabala\AppData\Local\Programs\Common\Microso
ft\Visual C++ for Python\9.0\VC\Bin\cl.exe
Poly.cpp
C:\Users\nikhil.kondabala\AppData\Local\Programs\Common\Microsoft\Visual C++ for
 Python\9.0\VC\Include\xlocale(342) : warning C4530: C++ exception handler used,
 but unwind semantics are not enabled. Specify /EHsc
src\pBEAM\Poly.cpp(155) : error C2057: expected constant expression
src\pBEAM\Poly.cpp(155) : error C2466: cannot allocate an array of constant size
 0
src\pBEAM\Poly.cpp(155) : error C2133: 'x' : unknown size
src\pBEAM\Poly.cpp(181) : error C2057: expected constant expression
src\pBEAM\Poly.cpp(181) : error C2466: cannot allocate an array of constant size
 0
src\pBEAM\Poly.cpp(181) : error C2133: 'z' : unknown size
src\pBEAM\Poly.cpp(233) : error C2057: expected constant expression
src\pBEAM\Poly.cpp(233) : error C2466: cannot allocate an array of constant size
 0
src\pBEAM\Poly.cpp(233) : error C2133: 'z_array' : unknown size
src\pBEAM\Poly.cpp(277) : error C2057: expected constant expression
src\pBEAM\Poly.cpp(277) : error C2466: cannot allocate an array of constant size
 0
src\pBEAM\Poly.cpp(277) : error C2133: 'x' : unknown size
src\pBEAM\Poly.cpp(336) : error C2057: expected constant expression
src\pBEAM\Poly.cpp(336) : error C2466: cannot allocate an array of constant size
 0
src\pBEAM\Poly.cpp(336) : error C2133: 'x' : unknown size
src\pBEAM\Poly.cpp(355) : error C2057: expected constant expression
src\pBEAM\Poly.cpp(355) : error C2466: cannot allocate an array of constant size
 0
src\pBEAM\Poly.cpp(355) : error C2133: 'pout' : unknown size
src\pBEAM\Poly.cpp(401) : error C2057: expected constant expression
src\pBEAM\Poly.cpp(401) : error C2466: cannot allocate an array of constant size
 0
src\pBEAM\Poly.cpp(401) : error C2133: 'result' : unknown size
error: Command "C:\Users\nikhil.kondabala\AppData\Local\Programs\Common\Microsof
t\Visual C++ for Python\9.0\VC\Bin\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -
Isrc\pBEAM -IC:/boost_1_55_0/boost_1_55_0 -Ic:\python27\arcgis10.1\lib\site-pack
ages\numpy\core\include -IC:\Python27\ArcGIS10.1\include -IC:\OpenMDAO\openmdao-
0.12.0\PC /Tpsrc\pBEAM\Poly.cpp /Fobuild\temp.win32-2.7\Release\src\pBEAM\Poly.o
bj -O2 /Zm1000" failed with exit status 2
------------------------------------------------------------------------
Press ENTER to close the interactive session..
========================================================================

(openmdao-0.12.0) C:\WISDEM-master\plugins\pBEAM>

**Comment by dykesk** [comment]
we made a small change to setup_all.py so that it should only use mingw and not try msvc; see if that helps for the wisdem setup_all install
