### ISSUE TITLE
Installation Problem

### ISSUE THREAD

**Issue by Rene36** [WISDEM/WISDEM#50]
Dear WISDEM Team,

I am having trouble installing WISDEM on my Windows 10 PC.

I followed the instructions under: https://nwtc.nrel.gov/WISDEM 

However, when I run "> bjam toolset=gcc --with-python link=shared" the .../stage/lib folder is created but it stays empty.
Further does the "setup_all.py" gives me the error "'plugin' is not recognized as an internal or external command, operable program or batch file.", which comes when it wants to install WISDEM itself. All other packages like FUSED-WIND or Turbine_CostsSE is installed correctly.
Do I need to add "plugin" to my PATH variables and what does the "install" stands for in the "setup_all.py"? There is nothing called "install" in the WISDEM root directory.

finally install WISDEM itself
os.chdir(rootdir)
os.system("plugin **install**")

Thanks for your help and of course I can provide you with required additional information.

Sincerely,
René

**Comment by dykesk** [comment]
Rene - i'm not sure this is an actually issue; please email systems.engineering@nrel.gov so we can take this discussion offline
