### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by James-Ilosta** [WISDEM/WISDEM#500]
Hi, I've been looking through the examples and I can't seem to find any documentation for the drivetrain optimisation. There are some parameter names that I'm unfamiliar with. 

opt = {}
opt["WISDEM"] = {}
opt["WISDEM"]["n_dlc"] = 1
opt["WISDEM"]["DriveSE"] = {}
opt["WISDEM"]["DriveSE"]["direct"] = False
opt["WISDEM"]["DriveSE"]["hub"] = {}
opt["WISDEM"]["DriveSE"]["hub"]["hub_gamma"] = 2.0
opt["WISDEM"]["DriveSE"]["hub"]["spinner_gamma"] = 1.5
opt["WISDEM"]["DriveSE"]["gamma_f"] = 1.35
opt["WISDEM"]["DriveSE"]["gamma_m"] = 1.3
opt["WISDEM"]["DriveSE"]["gamma_n"] = 1.0
opt["WISDEM"]["RotorSE"] = {}
opt["WISDEM"]["RotorSE"]["n_pc"] = 20
opt["materials"] = {}
opt["materials"]["n_mat"] = 4
opt["flags"] = {}
opt["flags"]["generator"] = False

"pitch_system.BRFM"
"pitch_system_scaling_factor"
"flange_t2shell_t"
"flange_OD2hub_D"
"flange_ID2flange_OD"
"hub_in2out_circ"
"hub_stress_concentration"
"n_front_brackets"
"n_rear_brackets"
"clearance_hub_spinner"
"spin_hole_incr"
"blades_I"

Is "spinner_gust_ws" the designed maximum gust as taken from the IEC wind classes?

It would be great to have a diagram of these if that is possible.

I was also unsure about the F_hub and M_hub. Are these just static loads from the rotor mass?

I was also wondering if you could set values for the cost function or if it was only possible to minimise this?

Thank you in advance :)

**Comment by gbarter** [comment]
Hello,

Thanks for your interest in WISDEM and the DrivetrainSE module.  We certainly acknowledge a deficiency in the documentation in this area.  The best that is available is [here](https://wisdem.readthedocs.io/en/master/wisdem/drivetrainse/components.html), however the variable names you listed are not described on that page.  It would probably be easiest to look directly at the source code in this [file](https://github.com/WISDEM/WISDEM/blob/master/wisdem/drivetrainse/hub.py).

At the bigger picture, we are not fully satisfied with the parameterization or sizing approach of the hub system.  It suits the needs of WISDEM for now, but is is not general enough to be included in the [WindIO](https://github.com/IEAWindTask37/windIO) effort, and has a number of hard coded sizing assumptions, instead of using design optimization with constraints like the rest of the WISDEM modules.  Of course, what we once viewed as a placeholder has taken hold and been the main approach for a number of years now.

**Comment by James-Ilosta** [comment]
Thanks Garrett for the reply. That is very helpful. I had a further question as I've been looking through the documentation. From what I can see the loading from the rotor is static.

I'm guessing though that this means the forces are balanced and not dynamically changing? Thus the rotor is not stationary?

I also was hoping if you had guidance on how to calculate these values?

**Comment by gbarter** [comment]
WISDEM is a steady-state/static code.  It computes an idealized, steady-state power curve for performance and AEP calculations.  For loading, it assumes a gust arrives while at rated conditions to form an ultimate limit state (ULS) that drives the sizing of the components.  This load case is propagated from the rotor down through the load path.  Fatigue is not considered.

For your questions:

- Rotor loading is static? Yes
- Forces balanced?  Not sure what you mean here.  There is a shear profile along the wind profile, so there are non-torque loads on the rotor, shaft, bearings, etc.
- Not dynamically changing? Yes, it is steady state
- Rotor not stationary?  The rotor is not moving.  The three blades are frozen at azimuth=0 / 120 / 240 deg for the load calculation.
- The values F_hub, M_hub, BRFM (blade root flap moment), have to come from a rotor simulation.  If you have a full turbine description, just run WISDEM once without any optimization and they will be calculated in the output file.  If you have a higher fidelity OpenFAST-type simulation, you could take a statistic from the timeseries (mean / P90 / max, etc).

**Comment by James-Ilosta** [comment]
That was really useful. Thanks Garret.

I had another question which I guess still relates to documentation. I'm trying to run a turbine yaml file through wisdem and I'm getting an error:

Exception has occurred: KeyError
'<model> <class WindPark>: Variable "tcons.max_allowable_td_ratio" not found.'

From what I can tell, I'm missing a turbine constraint for the max allowable tip deflection ratio, but I'm not sure how I can specific this?

I couldn't see any documentation relating to this. I could only see tip deflection, which i specified in my analysis_options.yaml

**Comment by gbarter** [comment]
@James-Ilosta - That error usually arises when you have activated the tip deflection constraint, but have deactivated some of the modules necessary to calculate it.  Would you be able to post your modeling_options and analysis_options files?

**Comment by James-Ilosta** [comment]
Hi Garrett, I had towerSE set to false, managed to trace it through the script. I was also wondering if you had a list of the design variables, constraints, optimisers and options for each of them similar to the OpenFAST 'OutListParameters.xlsx' for all of the components. I guess I'm wondering too what are the limits for wisdem currently in terms of design optimisation? what can/ can't it do for the aero or structural design?

**Comment by gbarter** [comment]
For blade design, WISDEM is limited to the steady state analysis that we discussed above, and therefore cannot account for fatigue or off-design performance.  There have been recent improvements in being able to design the many composite layers that comprise the blades, but it will still be a conceptual design, and not a detailed composite design.  Furthermore, the PreComp composite structural solver we use does not model all of the degrees of freedom, so you won't be able to account for torsional stability, for instance.  Finally, the structural checks that are used as constraints are focused on leading edge, trailing edge, and spar cap strain.  More advanced buckling analyses are not performed.

Internally, we use WISDEM to give us a very good conceptual starting point that we assume will need some tweaks as we elevate to the OpenFAST level of design iteration.

For a guide on the built in optimization options, see [this page](https://wisdem.readthedocs.io/en/latest/schema/analysis_schema.html) in the docs.  We recently coded up the capability for any output to serve as the objective function or constraint.  [See this example](https://wisdem.readthedocs.io/en/latest/examples/03_blade/user.html).  A complete list of outputs that could qualify is [here](https://wisdem.readthedocs.io/en/latest/docstrings/wisdem_outputs.html).

**Comment by James-Ilosta** [comment]
That is very interesting. Thank you.

I have some further questions. I have read through the GeneratorSE report and am still unsure about some of the parameters that I have seen.

Inside generator.py and also contained within the generator examples there are the parameters:
"alpha_p"
"cofi"
"h_i"
"h_0"
"h_sy0"
"m"
"phi"
"ratio_mw2pp"
"rad_ag"

which I am unsure about. Additionally, I was unsure about the parameter "sigma". I believe this is the shear stress in the high speed shaft, but I didn't see the definition of what this means or how it is derived? Apologies if I missed it.

**Comment by gbarter** [comment]
@James-Ilosta - Which generator technology model were you looking at?  One of the PMSGs?  DFIG?

@lssraman - Once answered, would you be able to explain some of these variables?  I can define some but not all.

**Comment by James-Ilosta** [comment]
DFIG and SCIG. Do the parameters have different meanings depending on the
technology?

**Comment by gbarter** [comment]
I've tracked down all but `alpha_p`:

"alpha_p"
"cofi" - power factor
"h_i" - coil insulation thickness
"h_0" - Slot height
"h_sy0" - (Don't know, but it isn't used in any calculations)
"m" - number of phases
"phi" - max tilt angle (such as during transportation or installation, usually 90deg)
"ratio_mw2pp" - ratio of magnet width to pole pitch(bm / self.tau_p)
"rad_ag" - Radius at air gap

@lssraman - Let me know if I got these wrong
