### ISSUE TITLE
Wisdem env activation

### ISSUE THREAD

**Issue by Ardemia1** [WISDEM/WISDEM#501]
After installing Wisdem, when I run the command "conda activate wisdem env" in my Spyder console, I get this:
"
Traceback (most recent call last):

  Cell In[1], line 1
    get_ipython().run_line_magic('conda', 'activate wisdem env')

  File ~\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py:2456 in run_line_magic
    result = fn(*args, **kwargs)

  File ~\anaconda3\Lib\site-packages\IPython\core\magics\packaging.py:30 in wrapper
    return func(*args, **kwargs)

  File ~\anaconda3\Lib\site-packages\IPython\core\magics\packaging.py:128 in conda
    conda = _get_conda_like_executable("conda")

  File ~\anaconda3\Lib\site-packages\IPython\core\magics\packaging.py:53 in _get_conda_like_executable
    match = re.search(

  File ~\anaconda3\Lib\re\__init__.py:176 in search
    return _compile(pattern, flags).search(string)

  File ~\anaconda3\Lib\re\__init__.py:294 in _compile
    p = _compiler.compile(pattern, flags)

  File ~\anaconda3\Lib\re\_compiler.py:745 in compile
    p = _parser.parse(p, flags)

  File ~\anaconda3\Lib\re\_parser.py:989 in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)

  File ~\anaconda3\Lib\re\_parser.py:464 in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,

  File ~\anaconda3\Lib\re\_parser.py:872 in _parse
    p = _parse_sub(source, state, sub_verbose, nested + 1)

  File ~\anaconda3\Lib\re\_parser.py:464 in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,

  File ~\anaconda3\Lib\re\_parser.py:548 in _parse
    code = _escape(source, this, state)

  File ~\anaconda3\Lib\re\_parser.py:402 in _escape
    raise source.error("incomplete escape %s" % escape, len(escape))

error: incomplete escape \U
"
How can I solve it?
![1](https://github.com/WISDEM/WISDEM/assets/164352596/570bd5b2-2ac9-41bc-af38-9e2d5e5d7cc7)

**Comment by Ardemia1** [comment]
Yes, but even with conda activate wisdem-env I get the same outcome

**Comment by gbarter** [comment]
Did you already create a "wisdem-env" environment in your Spyder console?  Sometimes Spyder and separate conda terminals work with different environment sets, depending on how things were installed.

**Comment by Ardemia1** [comment]
Thanks. By working directly in the Spyder console this is what I get.
Am I doing the correct procedure?
![1](https://github.com/WISDEM/WISDEM/assets/164352596/489f8265-56f2-429d-b3db-3d7f16379eaf)
![2](https://github.com/WISDEM/WISDEM/assets/164352596/67213ba8-200f-41b4-8de3-563a4d6644f8)

**Comment by gbarter** [comment]
Okay, I see that there are a few things wrong here.  

First is that you are installing WISDEM from pip, but then trying to build it from source.  You don't need to do both.  If you do "pip install wisdem" or "conda install wisdem", then you don't need to follow the WISDEM build instructions.  We find the "conda" is more reliable than "pip" for wisdem package installation.  However, you do need to enter these commands at a terminal command line, which is the second point.

Second, you are entering command line terms into the python interpreter in Spyder.  The Spyder python interpreter is for python code.  There is a way to get a [command prompt within Spyder](https://docs.spyder-ide.org/current/plugins/terminal.html), but it depends on how you installed Spyder into your computer.  That would be the place to enter all of the "conda" commands.

**Comment by Ardemia1** [comment]
Thanks, I'll try. I am new at Python so sorry for the mistakes :)

**Comment by Ardemia1** [comment]
I did "conda install wisdem" through the terminal in Spyder following your instructions. What should I do next?

**Comment by gbarter** [comment]
Well, what got you interested in WISDEM or what is your use case?  That will determine what you do next.

It also might be confusing to learn conda, python, WISDEM, and other concepts all commingled together.  There are a number of free tutorials out there that might be worth your time.
