### ISSUE TITLE
Intel MPI build fails to import MPI

### ISSUE THREAD

**Issue by cfrontin** [WISDEM/WISDEM#509]
Running with Intel MPI on NREL's Kestrel, `MPI` is set to `None` [because none of the variable formats here](https://github.com/WISDEM/WISDEM/blob/f1227621f1e1e734aec3abfb78d3a2f0fba301b9/wisdem/commonse/mpi_tools.py#L20C1-L20C41) are used by the Intel MPI build.

I have:
```
>>> for name in os.environ.keys():
...   if "MPI" in name:
...     print(name)
... 
I_MPI_PMI_LIBRARY
I_MPI_PMI
MPICC
INTEL_ONEAPI_COMPILERS_ROOT_DIR
INTEL_ONEAPI_MPI_ROOT_DIR
I_MPI_ROOT
```
so it's probably adequate to include `I_MPI_ROOT` to the list?

A current workaround is to create a dummy env variable (e.g. `export MPICH_I_MPI_DUMMY=1`) that satisfies the requirements, allowing `mpi4py.MPI` to get used correctly in an intel build.

**Comment by gbarter** [comment]
@cfrontin - Keep open or close?

**Comment by cfrontin** [comment]
This change works locally for me- I defer to you on whether it should go into the repo or not?

**Comment by cfrontin** [comment]
I do think some folks are running serial exclsusively on Kestrel because of this as of two weeks ago

**Comment by gbarter** [comment]
Should be resolved with [this](https://github.com/WISDEM/WISDEM/commit/0aa8e66e37b4ae824986016c92e8afef4465aa01) commit.
