### ISSUE TITLE
Doubts on the outputs of the blade structural optimization

### ISSUE THREAD

**Issue by Ardemia1** [WISDEM/WISDEM#510]
Hello! I'm performing a structural optimization on the IEA 15MW turbine and I doubt the outputs of my simulation.
I'm just varying the thickness of the spar caps and my figure of merit is the blade mass.
The output I get is the one in the image:
![op1_nuova](https://github.com/WISDEM/WISDEM/assets/164352596/8f6aeb8d-32e7-4101-92bf-59643b03b251)
Why do rated velocity, rpm, pitch, thrust, and torque change? Shouldn't they be constant?
Looking at the outputs, it seems like a thrust peak shaving is performed in the initial configuration, while this does not happen in the optimized solution.
![thrust](https://github.com/WISDEM/WISDEM/assets/164352596/ff92b619-3cd1-41dc-a131-5ef3760bda18)
Thanks in advance for the help.

**Comment by ptrbortolotti** [comment]
that's a little puzzling... is it possible for you to send me the input yaml files? I suspect that in the Opt case the peak thrust shaving is failing (if it is turned on in the first place...)

**Comment by Ardemia1** [comment]
Of course! The geometry file is "12mw.yaml" because in my case study I am limiting the rated power to 12MW, since we are studying the turbine for applications in the Mediterranean sea. Thanks for the help!
[Input files.zip](https://github.com/WISDEM/WISDEM/files/14893194/Input.files.zip)

**Comment by ptrbortolotti** [comment]
Try adding the peak thrust shaving to the modeling options. You can do so by adding these two lines in the modeling_options._struct.yaml under WISDEM->RotorSE
        peak_thrust_shaving: True
        thrust_shaving_coeff: 0.8


@gbarter Moving forward we should move this number to the controller section of the geometry yaml...

**Comment by Ardemia1** [comment]
Thanks, it works now!
