### ISSUE TITLE
Spar cap thicknesses plot

### ISSUE THREAD

**Issue by Ardemia1** [WISDEM/WISDEM#511]
Hello! When I run the "compare_designs.py" script for the blade structural optimization the spar cap thicknesses plot does not generate. 
This is the portion of the code responsible for the plot:
`    # Spar caps
    try:
        fsc, axsc = plt.subplots(1, 1, figsize=(5.3, 4))

        for idx, (yaml_data, label) in enumerate(zip(list_of_sims, list_of_labels)):
            s_opt_sc = yaml_data["blade.opt_var.s_opt_spar_cap_ss"]
            sc_opt = yaml_data["blade.opt_var.spar_cap_ss_opt"] * 1e3
            n_layers = yaml_data["blade.ps.layer_thickness_param"].shape[0]
            ilayer = None
            if ilayer is None:
                for i in range(n_layers):
                    layer_name = modeling_options["WISDEM"]["RotorSE"]["layer_name"][i]
                    if modeling_options["WISDEM"]["RotorSE"]["spar_cap_ss"] == layer_name:
                        ilayer = i

            if ilayer is None:
                raise KeyError("Suction side spar cap layer not found")
            axsc.plot(
                yaml_data["blade.outer_shape_bem.s"],
                yaml_data["blade.ps.layer_thickness_param"][ilayer, :] * 1e3,
                "-",
                color=colors[idx],
                label=label,
            )
            axsc.plot(s_opt_sc, sc_opt, "o", color=colors[idx], markersize=3)

        s_opt_sc = list_of_sims[0]["blade.outer_shape_bem.s"]
        sc_opt = list_of_sims[0]["blade.ps.layer_thickness_param"][ilayer, :] * 1e3
        axsc.plot(
            s_opt_sc,
            np.array(analysis_options["design_variables"]["blade"]["structure"]["spar_cap_ss"]["max_decrease"])
            * sc_opt,
            ":o",
            color=colors[idx + 1],
            markersize=3,
            label="Bounds",
        )
        axsc.plot(
            s_opt_sc,
            np.array(analysis_options["design_variables"]["blade"]["structure"]["spar_cap_ss"]["max_increase"])
            * sc_opt,
            ":o",
            color=colors[idx + 1],
            markersize=3,
        )

        if mult_flag:
            axsc.legend(fontsize=font_size)
        plt.xlabel("Blade Nondimensional Span [-]", fontsize=font_size + 2, fontweight="bold")
        plt.ylabel("Spar Caps Thickness [mm]", fontsize=font_size + 2, fontweight="bold")
        plt.xticks(fontsize=font_size)
        plt.yticks(fontsize=font_size)
        plt.grid(color=[0.8, 0.8, 0.8], linestyle="--")
        plt.subplots_adjust(bottom=0.15, left=0.15)
        fig_name = "sc_opt" + extension
        fsc.savefig(os.path.join(folder_output, fig_name), pad_inches=0.1, bbox_inches="tight")
    except KeyError:
        pass`

I don't know the cause of the problem: maybe yaml data have different names in my specific case? For example, where can I find "blade.opt_var.s_opt_spar_cap_ss" and "blade.opt_var.spar_cap_ss_opt"?

P.s. I don't have the error "Suction side spar cap layer not found", so that for sure is not my issue.

Thanks for the help, I appreciate it.

**Comment by ptrbortolotti** [comment]
Thanks for spotting a bug. It should now be fixed here https://github.com/WISDEM/WISDEM/tree/compare_designs
Let us know if it works!

**Comment by ptrbortolotti** [comment]
(you can try the new branch by doing `git checkout compare_designs` in your terminal)

**Comment by Ardemia1** [comment]
It works, thank you!

However, I think there is a similar issue for the trailing edge reinforcements plot.

**Comment by Ardemia1** [comment]
While waiting for your answer, I have an additional question.
This is my spar cap thicknesses plot:
![sc_opt](https://github.com/WISDEM/WISDEM/assets/164352596/4cabc445-7c03-42fc-94cc-fdc313934bd2)
As you can see, in some points (e.g. blade nondimensional span equal to 0.6) the thicknesses of the spar caps have reduced up to the allowed maximum (set to 0.7). For this reason, I've been wanting to try to decrease this value to see if a further reduction of the blade mass could be achieved. I tried to set the max decrease to 0.6: the optimization terminates successfully after some iterations but when I look at the results I see that they are exactly the same as the initial non-optimized case. How is this possible? If the thickness could not be further reduced, shouldn't the optimization outcome be exactly the same as the plotted one?
Thanks for your time.

**Comment by Ardemia1** [comment]
> The bounds should be working correctly. I don't know that I understand your plot exactly, but please try loosening the bounds further (say 0.3) and try tightening them (say 0.9), and the solution should change

Thanks, I'll try and let you know if it works

**Comment by ptrbortolotti** [comment]
> > good point again. do a `git pull` from that `compare_designs` branch and try again please
> 
> I'm afraid it still doesn't work

It works on my end... what plots do you get?

**Comment by Ardemia1** [comment]
I get these plots:
![image](https://github.com/WISDEM/WISDEM/assets/164352596/bb281d5c-f623-42ea-baaa-3ae40375d7be)

**Comment by ptrbortolotti** [comment]
it looks like you haven't updated wisdem. in a terminal please do `git branch` and make sure that you are on the `compare_designs` branch. if that's the case, please type `pip install --no-deps -e . -v` and try recalling `compare_design 12mw.yaml`

**Comment by ptrbortolotti** [comment]
That's puzzling. Again, if you can please send me the yamls

**Comment by Ardemia1** [comment]
[input files.zip](https://github.com/WISDEM/WISDEM/files/14979464/input.files.zip)
Thanks for your help.

**Comment by Ardemia1** [comment]
I seem to have a bigger problem. Even with your 12mw.yaml version, I get these errors when running "blade_driver.py" (I'm basically asking it to perform the structural optimization again):
![error](https://github.com/WISDEM/WISDEM/assets/164352596/b422e447-ee11-41d3-b0da-ae3187cd13ef)
I attach here the blade_driver file:
[blade_driver.zip](https://github.com/WISDEM/WISDEM/files/15001617/blade_driver.zip)

**Comment by ptrbortolotti** [comment]
the `blade_driver.py` script runs multiple cases, not just the blade structural optimization. I would comment out what you don't need and rerun
Next, I would kindly ask you to run a fresh installation of WISDEM as I cannot replicate the error... or try do `conda list` and `git status` so that I can see what WISDEM version you are using
Thank you for the patience!

**Comment by Ardemia1** [comment]
Yes, I've commented out the other cases. 
Anyway, by doing `conda list` I find out that I'm using WISDEM 3.14.0 (wisdem                    3.14.0          py311h2a191ef_101    conda-forge), but if I do `git status` I get "fatal: not a git repository (or any of the parent directories): .git"
Thanks for the help!

**Comment by Ardemia1** [comment]
Yes, I had already commented out the other cases, but I still get the three errors I've attached you in the previous comment.
Anyway, by doing `conda list` I find out that I'm using WISDEM 3.14.0 (wisdem 3.14.0 py311h2a191ef_101 conda-forge), and with `git status` I get "On branch master
Your branch is up to date with 'origin/master'".
Thanks for the help!
