### ISSUE TITLE
Error in documentation of direct-drive layout

### ISSUE THREAD

**Issue by verlivkra** [WISDEM/WISDEM#512]
## Description
I think the equation in line 54 in docs/wisdem/drivetrainse/layout.rst is wrong. I think it should include the hub radius (or the hub length, $L_{hub}$ - but I haven't found information about this anywhere). 

### Current behavior
$H_{bedplate} = H_{htt}-L_{drive}\sin{\gamma}$

### Expected behavior
$H_{bedplate} = H_{htt}-\left(L_{drive}+D_{hub}/2\right)\sin{\gamma}$

**Comment by ptrbortolotti** [comment]
Great catch, thank you very much! 
I've just updated the docs for both geared and direct-drive here https://github.com/WISDEM/WISDEM/commit/a8c85235f344eb499773d23416330484f51f4cae
We'll merge the commit into develop in the next few days. In a few weeks the commit will make its way into the master branch and readthedocs will be updated

**Comment by verlivkra** [comment]
Hi, 

While I see that the height of the bedplate is updated, I think the length of the bedplate should be updated too. I might be wrong, but I believe the hub diameter is not part of the length of the drivetrain, while it is part of the overhang. 

**Current behavior**
$L_{bedplate} = L_{overhang} - L_{drive}\cos\gamma$

**Expected behavior**
$L_{bedplate} = L_{overhang} - \left(L_{drive} + D_{hub}/2\right)\cos\gamma$

**Comment by gbarter** [comment]
Thank you for keeping us honest!  This has been fixed in documentation and code [here](https://github.com/WISDEM/WISDEM/commit/3d8e858694eb8deec5511a4fcb1be63c47ed76c5).  Will be a bit before it is pushed to the main branch in a new release.
