### ISSUE TITLE
GeneratorSE DFIG optimisation: Positive directional derivative for linesearch

### ISSUE THREAD

**Issue by James-Ilosta** [WISDEM/WISDEM#517]
When I run a wisdem optimisation, I get the following error:
"Positive directional derivative for linesearch"

This appears to arise as the optimiser cannot find an optimal solution. I'm not too sure how to improve my problem setup. Do you have any suggestions?

I guess I also don't know enough about how the actual optimisation is setup, does the optimiser use forward backward or central difference? I couldn't see how to modify this.

Additionally, I was wondering if it is possible to just check if my generator meets the design constraints of GeneratorSE, rather than running an optimisation?

**Comment by gbarter** [comment]
This is where optimization becomes a little bit of an art.  In the beginning, it might feel like trial-and-error, but with some experience, it starts to become best practices.

It will be tough to help on your question without seeing your problem setup- what is your design variable list, objective function and constraints?  What optimizer are you using with what parameters?

**Comment by James-Ilosta** [comment]
Apologies for the delay on this.

My problem:

`    # Example optimization of a generator for costs on a 5 MW reference turbine
    prob = om.Problem(reports=False)
    prob.model = Generator(design="dfig", n_pc=n_pc)

    if opt_flag:
        # add optimizer and set-up problem (using user defined input on objective function)
        prob.driver = om.ScipyOptimizeDriver()
        prob.driver.options["optimizer"] = "SLSQP"

        # Specificiency target efficiency(%)
        Eta_Target = 0.930

        eps = 1e-6

        # Design variables
        # prob.model.add_design_var("r_s", lower=r_s_min, upper=r_s_max)
        prob.model.add_design_var("len_s", lower=0.02, upper=0.4)
        prob.model.add_design_var("h_s", lower=0.002, upper=0.02)
        prob.model.add_design_var("B_symax", upper=2.0 - eps)
        prob.model.add_design_var("I_0", lower=0.26, upper=20.98, ref=1e2)
        prob.model.add_design_var("S_Nmax", lower=-0.3*2, upper=-0.1/2)

        # Constraints
        prob.model.add_constraint("generator_efficiency", lower=Eta_Target, indices=[-1])
        prob.model.add_constraint("E_p", lower=50.0 + eps, upper=10000.0 - eps, ref=1e3) # No load voltage
        prob.model.add_constraint("TCr", lower=0.0 + eps)
        prob.model.add_constraint("TCs", lower=0.0 + eps)
        prob.model.add_constraint("B_g", lower=0.7, upper=1.2)
        prob.model.add_constraint("B_trmax", upper=2.0 - eps)
        prob.model.add_constraint("B_tsmax", upper=2.0 - eps)
        prob.model.add_constraint("A_1", upper=60000.0 - eps, ref=1e5, indices=[-1])
        prob.model.add_constraint("J_s", upper=6.0)
        prob.model.add_constraint("J_r", upper=6.0)
        prob.model.add_constraint("Slot_aspect_ratio1", lower=4.0, upper=10.0)
        prob.model.add_constraint("K_rad", lower=0.2, upper=1.5)
        prob.model.add_constraint("D_ratio", lower=1.37, upper=1.4)
        prob.model.add_constraint("Current_ratio", lower=0.1, upper=0.6)

        Objective_function = "generator_mass"
        prob.model.add_objective(Objective_function,ref=Eta_Target)#, scaler=1e-5)


    prob.setup()

    # Specify Target machine parameters
    prob["p"] = 2.0
    prob["freq"] = 50
    prob["machine_rating"] = 500000
    prob["shaft_rpm"] = np.linspace(200, 1500, n_pc)
    prob["cofi"] = 0.9 #0.9 Apparently this is a reasonable assumption for DFIG
    prob["sigma"] = 629480.1
    prob["h_0"] = 0.1
    prob["I_0"] = 4.2# 40.0191207049 #40.0 #Ampere
    prob["len_s"] = 0.12 #0.49  # 1.06173588215 #0.49 #meter
    prob["h_s"] = 0.07 #0.08  # 0.1 # 0.08 #meter
    prob["rad_ag"] = 0.06 #0.61  # 0.493167295965 #0.61 #meter

    prob["y_tau_p"] = 12.0 / 15.0
    prob["B_symax"] = 1.3  # 1.59611292026 #1.3 #Tesla
    prob["S_Nmax"] = -0.2  # -0.3 #-0.2
    prob["k_fillr"] = 0.55
    prob["q1"] = 5

    # ---------------------------------------------------
    prob["E"] = 2e11
    prob["G"] = 79.3e9

    # Specific costs
    prob["C_Cu"] = 4.786  # Unit cost of Copper $/kg
    prob["C_Fe"] = 0.556  # Unit cost of Iron $/kg
    prob["C_Fes"] = 0.50139  # specific cost of Structural_mass $/kg
    prob["C_PM"] = 95.0

    # Material properties
    prob["rho_Fe"] = 7700.0  # Steel density Kg/m3
    prob["rho_Fes"] = 7850  # structural Steel density Kg/m3
    prob["rho_Copper"] = 8900.0  # copper density Kg/m3
    prob["rho_PM"] = 7450.0  # typical density Kg/m3 of neodymium magnets (added 2019 09 18) - for pmsg_[disc|arms]`


terminal output:

Positive directional derivative for linesearch    (Exit mode 8)
            Current function value: 740.8754668279825
            Iterations: 10
            Function evaluations: 6
            Gradient evaluations: 6
Optimization FAILED.
Positive directional derivative for linesearch
-----------------------------------
101 Input(s) in 'model'

varname             val                     units           prom_name
------------------  ----------------------  --------------  ----------------
poisson
  E                 [2.e+11]                Pa              E
  G                 [7.93e+10]              Pa              G
generator
  B_r               [1.2]                   T               B_r
  E                 [2.e+11]                Pa              E
  G                 [7.93e+10]              Pa              G
  P_Fe0e            [1.]                    W/kg            P_Fe0e
  P_Fe0h            [4.]                    W/kg            P_Fe0h
  S_N               [-0.002]                None            S_N
  alpha_p           [1.09955743]            None            alpha_p
  b_r_tau_r         [0.45]                  None            b_r_tau_r
  b_ro              [0.004]                 m               b_ro
  b_s_tau_s         [0.45]                  None            b_s_tau_s
  b_so              [0.004]                 m               b_so
  cofi              [0.9]                   None            cofi
  freq              [50.]                   Hz              freq
  h_i               [0.001]                 m               h_i
  h_sy0             [0.]                    None            h_sy0
  h_w               [0.005]                 m               h_w
  k_fes             [0.9]                   None            k_fes
  k_fillr           [0.55]                  None            k_fillr
  k_fills           [0.65]                  None            k_fills
  k_s               [0.2]                   None            k_s
  mu_0              [1.25663706e-06]        m*kg/s**2/A**2  mu_0
  mu_r              [1.06]                  m*kg/s**2/A**2  mu_r
  p                 [2.]                    None            p
  phi               [1.57079633]            rad             phi
  ratio_mw2pp       [0.7]                   None            ratio_mw2pp
  resist_Cu         [2.52e-08]              ohm/m           resist_Cu
  sigma             [629480.09528803]       Pa              sigma
  v                 [0.26103405]            None            v
  y_tau_p           [0.8]                   None            y_tau_p
  y_tau_pr          [0.83333333]            None            y_tau_pr
  I_0               [9.67426493]            A               I_0
  rated_torque      [0.]                    N*m             rated_torque
  d_r               [0.]                    m               d_r
  h_m               [0.]                    m               h_m
  h_0               [0.1]                   m               h_0
  h_s               [0.00701873]            m               h_s
  len_s             [0.06559519]            m               len_s
  machine_rating    [500000.]               W               machine_rating
  shaft_rpm         |4190.84214624|         rpm             shaft_rpm
  n_r               [0.]                    None            n_r
  rad_ag            [0.06]                  m               rad_ag
  t_wr              [0.]                    m               t_wr
  n_s               [0.]                    None            n_s
  b_st              [0.]                    m               b_st
  d_s               [0.]                    m               d_s
  t_ws              [0.]                    m               t_ws
  D_shaft           [0.]                    m               D_shaft
  rho_Copper        [8900.]                 kg/m**3         rho_Copper
  rho_Fe            [7700.]                 kg/m**3         rho_Fe
  rho_Fes           [7850.]                 kg/m**3         rho_Fes
  rho_PM            [7450.]                 kg/m**3         rho_PM
  S_Nmax            [-0.6]                  None            S_Nmax
  B_symax           [1.999999]              T               B_symax
  m                 3                       Unavailable     m
  q1                5                       Unavailable     q1
  q2                4                       Unavailable     q2
mofi
  R_out             [0.07476602]            m               R_out
  stator_mass       [0.]                    kg              stator_mass
  rotor_mass        [0.]                    kg              rotor_mass
  generator_mass    [689.01418415]          kg              generator_mass
  len_s             [0.06559519]            m               len_s
gen_cost
  C_Cu              [4.786]                 USD/kg          C_Cu
  C_Fe              [0.556]                 USD/kg          C_Fe
  C_Fes             [0.50139]               USD/kg          C_Fes
  C_PM              [95.]                   USD/kg          C_PM
  Copper            [31.05278962]           kg              Copper
  Iron              [-4.53909397]           kg              Iron
  mass_PM           [0.]                    kg              mass_PM
  Structural_mass   [662.5004885]           kg              Structural_mass
constr
  u_allow_s         [0.]                    m               u_allow_s
  u_as              [0.]                    m               u_as
  z_allow_s         [0.]                    m               z_allow_s
  z_as              [0.]                    m               z_as
  y_allow_s         [0.]                    m               y_allow_s
  y_as              [0.]                    m               y_as
  b_allow_s         [0.]                    m               b_allow_s
  b_st              [0.]                    m               b_st
  u_allow_r         [0.]                    m               u_allow_r
  u_ar              [0.]                    m               u_ar
  y_allow_r         [0.]                    m               y_allow_r
  y_ar              [0.]                    m               y_ar
  z_allow_r         [0.]                    m               z_allow_r
  z_ar              [0.]                    m               z_ar
  b_allow_r         [0.]                    m               b_allow_r
  b_arm             [0.]                    m               b_arm
  TC1               [0.00050803]            m**3            TC1
  TC2r              [0.00023614]            m**3            TC2r
  TC2s              [0.]                    m**3            TC2s
  B_g               [0.1831527]             T               B_g
  B_smax            [0.]                    T               B_smax
  K_rad             [0.54662662]            None            K_rad
  K_rad_LL          [0.]                    None            K_rad_LL
  K_rad_UL          [0.]                    None            K_rad_UL
  D_ratio           [1.24610029]            None            D_ratio
  D_ratio_LL        [0.]                    None            D_ratio_LL
  D_ratio_UL        [0.]                    None            D_ratio_UL
eff
  machine_rating    [500000.]               W               machine_rating
  shaft_rpm         |4190.84214624|         rpm             shaft_rpm
  eandm_efficiency  |0.00447214|            None            eandm_efficiency


88 Explicit Output(s) in 'model'

varname                   val                      units    prom_name
------------------------  -----------------------  -------  ----------------------
poisson
  v                       [0.26103405]             None     v
generator
  B_rymax                 [1.999999]               T        B_rymax
  B_trmax                 [-0.47816467]            T        B_trmax
  B_tsmax                 [0.33300491]             T        B_tsmax
  B_g                     [0.1831527]              T        B_g
  B_g1                    [0.17684926]             T        B_g1
  B_pm1                   [0.]                     None     B_pm1
  N_s                     [20.]                    None     N_s
  b_s                     [0.00282743]             m        b_s
  b_t                     [0.00345575]             m        b_t
  A_Curcalc               [43.98243962]            mm**2    A_Curcalc
  A_Cuscalc               [1.14156229]             mm**2    A_Cuscalc
  b_m                     [0.]                     None     b_m
  mass_PM                 [0.]                     kg       mass_PM
  Copper                  [31.05278962]            kg       Copper
  Iron                    [-4.53909397]            kg       Iron
  Structural_mass         [662.5004885]            kg       Structural_mass
  generator_mass          [689.01418415]           kg       generator_mass
  f                       |139.69473821|           None     f
  I_s                     |488717.90194801|        A        I_s
  R_s                     |0.4266203|              ohm      R_s
  L_s                     [1.39673757e-05]         None     L_s
  J_s                     |428113.21379436|        A/m**2   J_s
  A_1                     |155563739.74505094|     None     A_1
  K_rad                   [0.54662662]             None     K_rad
  Losses                  |34866973559.704544|     W        Losses
  eandm_efficiency        |0.00447214|             None     eandm_efficiency
  u_ar                    [0.]                     m        u_ar
  u_as                    [0.]                     m        u_as
  u_allow_r               [0.]                     m        u_allow_r
  u_allow_s               [0.]                     m        u_allow_s
  y_ar                    [0.]                     m        y_ar
  y_as                    [0.]                     m        y_as
  y_allow_r               [0.]                     m        y_allow_r
  y_allow_s               [0.]                     m        y_allow_s
  z_ar                    [0.]                     m        z_ar
  z_as                    [0.]                     m        z_as
  z_allow_r               [0.]                     m        z_allow_r
  z_allow_s               [0.]                     m        z_allow_s
  b_allow_r               [0.]                     m        b_allow_r
  b_allow_s               [0.]                     m        b_allow_s
  TC1                     [0.00050803]             m**3     TC1
  TC2r                    [0.00023614]             m**3     TC2r
  TC2s                    [0.]                     m**3     TC2s
  R_out                   [0.07476602]             m        R_out
  S                       [60.]                    None     S
  Slot_aspect_ratio       [0.]                     None     Slot_aspect_ratio
  Slot_aspect_ratio1      [2.4823663]              None     Slot_aspect_ratio1
  Slot_aspect_ratio2      [28.7993726]             None     Slot_aspect_ratio2
  D_ratio                 [1.24610029]             None     D_ratio
  J_r                     |11111.65965667|         None     J_r
  L_sm                    [0.00055186]             None     L_sm
  Q_r                     [48.]                    None     Q_r
  R_R                     [0.0054311]              None     R_R
  b_r                     [0.0034723]              None     b_r
  b_tr                    [0.00424392]             None     b_tr
  b_trmin                 [-0.00295556]            None     b_trmin
  N_r                     [33.]                    None     N_r
  L_r                     [0.00013988]             None     L_r
  h_yr                    [0.00274729]             None     h_yr
  h_ys                    [0.00274729]             None     h_ys
  tau_p                   [0.09424778]             None     tau_p
  Current_ratio           |0.00076049|             None     Current_ratio
  E_p                     |7.86091693|             None     E_p
mofi
  generator_I             |2.57615114|             kg*m**2  generator_I
  rotor_I                 |1.28807557|             kg*m**2  rotor_I
  stator_I                |1.28807557|             kg*m**2  stator_I
gen_cost
  generator_cost          [2168.7199675]           USD      generator_cost
constr
  con_uas                 [0.]                     m        con_uas
  con_zas                 [0.]                     m        con_zas
  con_yas                 [0.]                     m        con_yas
  con_bst                 [0.]                     m        con_bst
  con_uar                 [0.]                     m        con_uar
  con_yar                 [0.]                     m        con_yar
  con_zar                 [0.]                     m        con_zar
  con_br                  [0.]                     m        con_br
  TCr                     [-0.00027189]            m**3     TCr
  TCs                     [-0.00050803]            m**3     TCs
  con_TC2r                [-0.00050803]            m**3     con_TC2r
  con_TC2s                [-0.00050803]            m**3     con_TC2s
  con_Bsmax               [0.1831527]              T        con_Bsmax
  K_rad_L                 [0.54662662]             None     K_rad_L
  K_rad_U                 [0.54662662]             None     K_rad_U
  D_ratio_L               [1.24610029]             None     D_ratio_L
  D_ratio_U               [1.24610029]             None     D_ratio_U
eff
  converter_efficiency    |4.39642759|             None     converter_efficiency
  transformer_efficiency  |4.1909444|              None     transformer_efficiency
  generator_efficiency    |0.00411957|             None     generator_efficiency


0 Implicit Output(s) in 'model'


Efficiency table:
 rpm     converter  transformer  generator
-------------------------------------------
[[2.00000000e+02 9.75186053e-01 9.66579200e-01 9.42594555e-04]
 [2.68421053e+02 9.78170283e-01 9.65440789e-01 9.44365490e-04]
 [3.36842105e+02 9.79940379e-01 9.63969808e-01 9.44632940e-04]
 [4.05263158e+02 9.81111293e-01 9.62166258e-01 9.43992182e-04]
 [4.73684211e+02 9.81942670e-01 9.60030139e-01 9.42694557e-04]
 [5.42105263e+02 9.82563072e-01 9.57561449e-01 9.40864520e-04]
 [6.10526316e+02 9.83043431e-01 9.54760191e-01 9.38570734e-04]
 [6.78947368e+02 9.83426086e-01 9.51626362e-01 9.35854189e-04]
 [7.47368421e+02 9.83737870e-01 9.48159965e-01 9.32740864e-04]
 [8.15789474e+02 9.83996616e-01 9.44360997e-01 9.29248025e-04]
 [8.84210526e+02 9.84214636e-01 9.40229460e-01 9.25387596e-04]
 [9.52631579e+02 9.84400705e-01 9.35765354e-01 9.21168074e-04]
 [1.02105263e+03 9.84561246e-01 9.30968678e-01 9.16595682e-04]
 [1.08947368e+03 9.84701070e-01 9.25839433e-01 9.11675080e-04]
 [1.15789474e+03 9.84823848e-01 9.20377618e-01 9.06409827e-04]
 [1.22631579e+03 9.84932434e-01 9.14583233e-01 9.00802690e-04]
 [1.29473684e+03 9.85029077e-01 9.08456279e-01 8.94855850e-04]
 [1.36315789e+03 9.85115577e-01 9.01996756e-01 8.88571054e-04]
 [1.43157895e+03 9.85193387e-01 8.95204663e-01 8.81949713e-04]
 [1.50000000e+03 9.85263696e-01 8.88080000e-01 8.74992983e-04]]

**Comment by James-Ilosta** [comment]
I was wondering if you had any advice on estimating no-load magnetisation current?

**Comment by gbarter** [comment]
I don't see the full script in your post to be able to just copy and run it, but it looks like you are templating off of this [example file](https://github.com/WISDEM/WISDEM/blob/master/examples/07_generator/dfig.py) (which is great).  However, I can see that you have removed the order-of-magnitude conditioning on the objective function in this [line](https://github.com/WISDEM/WISDEM/blob/master/examples/07_generator/dfig.py#L49).  Poor conditioning, in this case having big swings in order-of-magnitude across design variables and constraints can exactly lead to the error you are seeing.

**Comment by James-Ilosta** [comment]
Ah I see. How does the scalar parameter work? I'm unfamiliar with it

**Comment by gbarter** [comment]
That scaler parameter works similar to the `ref` parameter that appears in some of your design variable and constraint lines.  It might even be easier to just use `ref` and avoid `scalar` to remove the confusion about any differences between the two.  They just intercept the values being computed by the model before they are seen by the optimizer so that everything is roughly on the same order of magnitude.
