### ISSUE TITLE
issue while import _pBEAM: DLL load failed

### ISSUE THREAD

**Issue by ansfab** [WISDEM/WISDEM#52]
Hello everyone,

I'm quite new to WISDEM and tried to install the program for over two weeks now because we think the blade optimizer will be very helpful in our project. I got it running on Ubuntu 16 with 32 bit, but somehow the SNOPT optimizer with 32bit is just available for windows. The installation on windows 10 worked now with some modifications, but I got an issue with importing _pBEAM in python because there seems to be a DLL missing. I'm very glad for any help. Here is the output of a separate pBEAM installation:

############################################################################
(openmdao-0.10.3.2) C:\workspace\WISDEM\plugins\pBEAM>python setup.py config --compiler=mingw32 build --compiler=mingw32 --force install
running config
running build
running config_cc
unifing config_cc, config, build_clib, build_ext, build commands --compiler options
running config_fc
unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
running build_src
build_src
building extension "_pBEAM" sources
build_src: building npy-pkg config files
running build_ext
customize Mingw32CCompiler
customize Mingw32CCompiler using build_ext
customize Mingw32CCompiler
customize Mingw32CCompiler using build_ext
building '_pBEAM' extension
compiling C++ sources
C compiler: g++ -O2 -Wall

compile options: '-DNPY_MINGW_USE_CUSTOM_MSVCR -D__MSVCRT_VERSION__=0x1500 -Isrc\pBEAM -IC:/boost_1_55_0 -IC:\openmdao-0.10.3.2\lib\site-packages\numpy\core\include -IC:\Python27\include -IC:\openmdao-0.10.3.2\PC -c'
extra options: '-O2'
g++ -O2 -Wall -DNPY_MINGW_USE_CUSTOM_MSVCR -D__MSVCRT_VERSION__=0x1500 -Isrc\pBEAM -IC:/boost_1_55_0 -IC:\openmdao-0.10.3.2\lib\site-packages\numpy\core\include -IC:\Python27\include -IC:\openmdao-0.10.3.2\PC -c src\pBEAM\Poly.cpp -o build\temp.win32-2.7\Release\src\pbeam\poly.o -O2g++ -O2 -Wall -DNPY_MINGW_USE_CUSTOM_MSVCR -D__MSVCRT_VERSION__=0x1500 -Isrc\pBEAM -IC:/boost_1_55_0 -IC:\openmdao-0.10.3.2\lib\site-packages\numpy\core\include -IC:\Python27\include -IC:\openmdao-0.10.3.2\PC -c src\pBEAM\BeamFEA.cpp -o build\temp.win32-2.7\Release\src\pbeam\beamfea.o -O2

g++ -O2 -Wall -DNPY_MINGW_USE_CUSTOM_MSVCR -D__MSVCRT_VERSION__=0x1500 -Isrc\pBEAM -IC:/boost_1_55_0 -IC:\openmdao-0.10.3.2\lib\site-packages\numpy\core\include -IC:\Python27\include -IC:\openmdao-0.10.3.2\PC -c src\pyBEAM\pyBEAM.cpp -o build\temp.win32-2.7\Release\src\pybeam\pybeam.o -O2g++ -O2 -Wall -DNPY_MINGW_USE_CUSTOM_MSVCR -D__MSVCRT_VERSION__=0x1500 -Isrc\pBEAM -IC:/boost_1_55_0 -IC:\openmdao-0.10.3.2\lib\site-packages\numpy\core\include -IC:\Python27\include -IC:\openmdao-0.10.3.2\PC -c src\pBEAM\Beam.cpp -o build\temp.win32-2.7\Release\src\pbeam\beam.o -O2

g++ -O2 -Wall -DNPY_MINGW_USE_CUSTOM_MSVCR -D__MSVCRT_VERSION__=0x1500 -Isrc\pBEAM -IC:/boost_1_55_0 -IC:\openmdao-0.10.3.2\lib\site-packages\numpy\core\include -IC:\Python27\include -IC:\openmdao-0.10.3.2\PC -c src\pBEAM\myMath.cpp -o build\temp.win32-2.7\Release\src\pbeam\mymath.o -O2
g++ -shared build\temp.win32-2.7\Release\src\pbeam\poly.o build\temp.win32-2.7\Release\src\pbeam\mymath.o build\temp.win32-2.7\Release\src\pbeam\beamfea.o build\temp.win32-2.7\Release\src\pbeam\beam.o build\temp.win32-2.7\Release\src\pybeam\pybeam.o -LC:/boost_1_55_0/stage/lib -LC:/lapack -LC:\Python27\Libs -LC:\openmdao-0.10.3.2\libs -LC:\openmdao-0.10.3.2\PCbuild -LC:\openmdao-0.10.3.2\PC\VS9.0 -lboost_python-mgw63-mt-1_55 -llapack -lblas -lpython27 -lmsvcr90 -o build\lib.win32-2.7\_pBEAM.pyd
running install
running bdist_egg
running egg_info
writing pBEAM.egg-info\PKG-INFO
writing top-level names to pBEAM.egg-info\top_level.txt
writing dependency_links to pBEAM.egg-info\dependency_links.txt
reading manifest file 'pBEAM.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'CHANGELOG.md'
warning: no directories found matching 'docs\_build\html'
warning: no directories found matching 'test'
writing manifest file 'pBEAM.egg-info\SOURCES.txt'
installing library code to build\bdist.win32\egg
running install_lib
creating build\bdist.win32\egg
copying build\lib.win32-2.7\_pBEAM.pyd -> build\bdist.win32\egg
creating stub loader for _pBEAM.pyd
byte-compiling build\bdist.win32\egg\_pBEAM.py to _pBEAM.pyc
creating build\bdist.win32\egg\EGG-INFO
copying pBEAM.egg-info\PKG-INFO -> build\bdist.win32\egg\EGG-INFO
copying pBEAM.egg-info\SOURCES.txt -> build\bdist.win32\egg\EGG-INFO
copying pBEAM.egg-info\dependency_links.txt -> build\bdist.win32\egg\EGG-INFO
copying pBEAM.egg-info\top_level.txt -> build\bdist.win32\egg\EGG-INFO
writing build\bdist.win32\egg\EGG-INFO\native_libs.txt
zip_safe flag not set; analyzing archive contents...
creating 'dist\pBEAM-0.1.0-py2.7-win32.egg' and adding 'build\bdist.win32\egg' to it
removing 'build\bdist.win32\egg' (and everything under it)
Processing pBEAM-0.1.0-py2.7-win32.egg
Removing c:\openmdao-0.10.3.2\lib\site-packages\pBEAM-0.1.0-py2.7-win32.egg
Copying pBEAM-0.1.0-py2.7-win32.egg to c:\openmdao-0.10.3.2\lib\site-packages
pBEAM 0.1.0 is already the active version in easy-install.pth

Installed c:\openmdao-0.10.3.2\lib\site-packages\pbeam-0.1.0-py2.7-win32.egg
Processing dependencies for pBEAM==0.1.0
Finished processing dependencies for pBEAM==0.1.0
############################################################################
(openmdao-0.10.3.2) C:\workspace\WISDEM\plugins\pBEAM>python
Python 2.7.15 |Anaconda, Inc.| (default, May  1 2018, 18:37:12) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import wisdem.lcoe.lcoe_csm_assembly

>>> import wisdem.lcoe.lcoe_se_assembly
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\workspace\wisdem\src\wisdem\lcoe\lcoe_se_assembly.py", line 19, in <module>
    from wisdem.turbinese.turbine import configure_turbine
  File "c:\workspace\wisdem\src\wisdem\turbinese\turbine.py", line 15, in <module>
    from rotorse.rotor import RotorSE
  File "c:\workspace\wisdem\plugins\rotorse\src\rotorse\rotor.py", line 24, in <module>
    import _pBEAM
ImportError: DLL load failed: Das angegebene Modul wurde nicht gefunden.
>>> import _pBEAM
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: DLL load failed: Das angegebene Modul wurde nicht gefunden.
>>>
#############################################################################

Is this a known error? Or is it possible to get to know which DLL is missing?
Best Regards,
Fabian

**Comment by dykesk** [comment]
Hi Fabian,

We have started migrating away from the older version of openmdao.  You might try installing pbeam from the develop-GB branch and the other models from the openmdao1 branches (compatible with openmdao1).  The following script can help with this.  None of this has been officially released yet but should in the coming months.

**Comment by ansfab** [comment]
Dear Katherine,
thanks a lot for the prompt answer. The develop branch you mentioned, together with openmdao 0.10.3.2, renaming/deleting the g77.exe in my MinGW\Lib and erasing the '#undef hypot' command in the cmath MinGW file, did the trick. The last days/weeks I eagerly tried to get the SNOPT optimizer running with Rotorse, but (I guess mostly due to a lack of knowledge in building and linking libraries properly) I'm still struggling. But this is another topic for the SNOPT-community and I'd say that this issue here can, therefore, be closed.
Best regards,
Fabian

**Comment by dykesk** [comment]
okay super - i'm going to close this then
