### ISSUE TITLE
Missing Airfoils.initFromAerodynFiles

### ISSUE THREAD

**Issue by Tianmaru** [WISDEM/WISDEM#525]
Ok, so I was really confused, why all the CCBlade tutorials ended up with the error:

```
AttributeError: type object 'CCAirfoil' has no attribute 'initFromAerodynFile'
```

Well, turns out, this function was removed in the Wisdem.CCBlade version, while it is still present in the CCBlade repo itself and all the tutorials still reference it.

**Comment by gbarter** [comment]
Thank you for catching this and bringing it to our attention.  The code in the [example](https://github.com/WISDEM/WISDEM/blob/master/examples/10_ccblade/example.py) is more up-to-date with best practices of grabbing information from the yaml files.  I am updating the language in the example tutorial accordingly (#526 ), thanks to your prompt.

**Comment by Tianmaru** [comment]
Ok, thank you, I will refer to the example code then. I think I got it to work, but I noticed that the validation method will fail if the file path is provided as a PosixPath instead of a string:

```
WARNING: Be sure to pip install simpy and marmot-agents for offshore BOS runs
Traceback (most recent call last):
  File "/home/user/ida/projects/w2erl-gym/tests/ccblade_nrel5_test.py", line 22, in <module>
    data = load_geometry_yaml(baseyaml)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File <path>, line 128, in load_geometry_yaml
    return validate_with_defaults(finput, fschema_geom)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "lib/python3.12/site-packages/wisdem/inputs/validation.py", line 122, in validate_with_defaults
    DefaultValidatingDraft7Validator(yaml_schema).validate(myobj)
  File "lib/python3.12/site-packages/jsonschema/validators.py", line 438, in validate
    raise error
jsonschema.exceptions.ValidationError: PosixPath('/home/user/project/nrel5mw.yaml') is not of type 'object'
```

Also, would it be possible to include e.g. the reference turbines in the distribution to make them accessible via `importlib.resources`? Or does it mean legal trouble to redistribute the models?

**Comment by gbarter** [comment]
I'm not sure what the suggested action is on the yaml read functions.  Is this just for your own script?  Seems like you can just convert to a string before passing to the function?

On the reference turbine files, you are asking for the files to be installed as package data files instead of just files in [this example](https://github.com/WISDEM/WISDEM/tree/master/examples/02_reference_turbines) directory?

**Comment by Tianmaru** [comment]
Sure, I also ended up converting the Path object to a string myself - however, keep in mind that unfamiliar users like myself would expect Path objects to work for file paths, and the error message isn't clearly stating that the yaml validation function is expecting the file paths to be provided only as strings, leaving the impression that the validation function might be broken.

Regarding the turbine reference files: yes, I think that is what me from a month ago was suggesting - I am not really sure about the benefits anymore though.
