### ISSUE TITLE
Using WISDEM

### ISSUE THREAD

**Issue by reshmighosh** [WISDEM/WISDEM#53]
Hello,

I am a little unsure about how to use WISDEM correctly. Do you have any documentation with examples listed to run through the model?

Best,
Reshmi

**Comment by gbarter** [comment]
Hi, sorry for the long delay here.  We have started a concerted effort to make the user experience and learning curve easier.  It will take us a little bit to get there, but eventually we hope to have current, complete documentation, yaml input files (no python necessary), and even a GUI.  Apologies that we don't have a better start for you now.
