### ISSUE TITLE
Rated Wind Speed as input

### ISSUE THREAD

**Issue by Viola99user** [WISDEM/WISDEM#530]
# Description of feature
Hi, i would ask if is possible to model the IEA-15-240-RWT.yaml, by entering as input (fixed variable) the rated wind speed at 9.5m/s. Is it possible? And if so, how can i do it? 
Thanks.

**Comment by ptrbortolotti** [comment]
it is not possible, and I'm curious what you're trying to do. in a common setting, rated wind speed is an output given a certain rotor diameter, rotor performance, drivetrain efficiency, and generator power. how are you hoping to hard-code a desired rated wind speed? would that lower your generator power?

**Comment by ptrbortolotti** [comment]
I'll close this now. Please reopen a new issue if you need anything from us!
