### ISSUE TITLE
Cannot install on windows

### ISSUE THREAD

**Issue by zcgzcg50** [WISDEM/WISDEM#537]
## Description
using`pip install --no-deps -e . -v` to install WISDEM-3.15.3, get an error as follows. So the examples can't run.
could you give me some advice?
`meson.build:16:0: ERROR: Compiler gfortran cannot compile programs.`

### Steps to reproduce issue
full message is shown below.
`(wisdem-env) D:\00nrel\WISDEM>pip install --no-deps -e . -v
Using pip 24.0 from d:\ProgramData\miniconda3\envs\wisdem-env\Lib\site-packages\pip (python 3.12)
Obtaining file:///D:/00nrel/WISDEM
  Running command pip subprocess to install build dependencies
  Collecting setuptools
    Using cached setuptools-70.0.0-py3-none-any.whl.metadata (5.9 kB)
  Collecting numpy
    Using cached numpy-1.26.4-cp312-cp312-win_amd64.whl.metadata (61 kB)
  Collecting ninja
    Using cached ninja-1.11.1.1-py2.py3-none-win_amd64.whl.metadata (5.4 kB)
  Collecting meson>=1.1
    Using cached meson-1.4.1-py3-none-any.whl.metadata (1.8 kB)
  Collecting wheel
    Using cached wheel-0.43.0-py3-none-any.whl.metadata (2.2 kB)
  Using cached setuptools-70.0.0-py3-none-any.whl (863 kB)
  Using cached numpy-1.26.4-cp312-cp312-win_amd64.whl (15.5 MB)
  Using cached ninja-1.11.1.1-py2.py3-none-win_amd64.whl (312 kB)
  Using cached meson-1.4.1-py3-none-any.whl (937 kB)
  Using cached wheel-0.43.0-py3-none-any.whl (65 kB)
  Installing collected packages: ninja, wheel, setuptools, numpy, meson
  Successfully installed meson-1.4.1 ninja-1.11.1.1 numpy-1.26.4 setuptools-70.0.0 wheel-0.43.0
  Installing build dependencies ... done
  Running command Checking if build backend supports build_editable
  Checking if build backend supports build_editable ... done
  Running command Getting requirements to build editable
  ['C:\\Users\\xxx\\AppData\\Local\\Temp\\pip-build-env-hbdwr5ez\\overlay\\Scripts\\meson.EXE', 'setup', 'meson_build', '--wipe', '--prefix=D:\\00nrel\\WISDEM\\meson_build', '-Dpython.purelibdir=.', '-Dpython.platlibdir=.']
  The Meson build system
  Version: 1.4.1
  Source dir: D:\00nrel\WISDEM
  Build dir: D:\00nrel\WISDEM\meson_build
  Build type: native build
  Project name: wisdem
  Project version: undefined
  C compiler for the host machine: gcc (gcc 5.3.0 "gcc (Rev5, Built by MSYS2 project) 5.3.0")
  C linker for the host machine: gcc ld.bfd 2.25.1
  Host machine cpu family: x86_64
  Host machine cpu: x86_64

  meson.build:16:0: ERROR: Compiler gfortran cannot compile programs.

  A full log can be found at D:\00nrel\WISDEM\meson_build\meson-logs\meson-log.txt

  Traceback (most recent call last):
    File "d:\ProgramData\miniconda3\envs\wisdem-env\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
      main()
    File "d:\ProgramData\miniconda3\envs\wisdem-env\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "d:\ProgramData\miniconda3\envs\wisdem-env\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 132, in get_requires_for_build_editable
      return hook(config_settings)
             ^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\xxx\AppData\Local\Temp\pip-build-env-hbdwr5ez\overlay\Lib\site-packages\setuptools\build_meta.py", line 448, in get_requires_for_build_editable
      return self.get_requires_for_build_wheel(config_settings)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\xxx\AppData\Local\Temp\pip-build-env-hbdwr5ez\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\xxx\AppData\Local\Temp\pip-build-env-hbdwr5ez\overlay\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
      self.run_setup()
    File "C:\Users\xxx\AppData\Local\Temp\pip-build-env-hbdwr5ez\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
      exec(code, locals())
    File "<string>", line 102, in <module>
    File "<string>", line 62, in run_meson_build
  OSError: [Errno ['C:\\Users\\xxx\\AppData\\Local\\Temp\\pip-build-env-hbdwr5ez\\overlay\\Scripts\\meson.EXE', 'setup', 'meson_build', '--wipe', '--prefix=D:\\00nrel\\WISDEM\\meson_build', '-Dpython.purelibdir=.', '-Dpython.platlibdir=.']] The meson setup command failed! Check the log at meson_build\setup.log for more information.
  error: subprocess-exited-with-error

  × Getting requirements to build editable did not run successfully.
  │ exit code: 1
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: 'd:\ProgramData\miniconda3\envs\wisdem-env\python.exe' 'd:\ProgramData\miniconda3\envs\wisdem-env\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py' get_requires_for_build_editable 'C:\Users\xxx\AppData\Local\Temp\tmpuprgukty'
  cwd: D:\00nrel\WISDEM
  Getting requirements to build editable ... error
error: subprocess-exited-with-error

× Getting requirements to build editable did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.`
## Code versions
wisdem 3.15.3
Python 3.12.3

**Comment by gbarter** [comment]
Hello- Did you install the packages in the `environment.yml` file and the compiler packages for Windows as described in the Install section of the [README](https://github.com/WISDEM/WISDEM/blob/master/README.md)?

**Comment by zcgzcg50** [comment]
> Hello- Did you install the packages in the `environment.yml` file and the compiler packages for Windows as described in the Install section of the [README](https://github.com/WISDEM/WISDEM/blob/master/README.md)?

Yes, I followed steps in the README. And I tested on two laptops, both failed.

**Comment by gbarter** [comment]
Okay, interesting.  Can you try to remove `git` from your conda environment (`conda remove git`)?  I had an anecdote that the conda git libraries conflict with the conda gfortran.  I have not yet updated the README or `environment.yml` file to reflect that.

**Comment by zcgzcg50** [comment]
> Okay, interesting. Can you try to remove `git` from your conda environment (`conda remove git`)? I had an anecdote that the conda git libraries conflict with the conda gfortran. I have not yet updated the README or `environment.yml` file to reflect that.

thanks for your reply. I will try.

**Comment by zcgzcg50** [comment]
> Okay, interesting. Can you try to remove `git` from your conda environment (`conda remove git`)? I had an anecdote that the conda git libraries conflict with the conda gfortran. I have not yet updated the README or `environment.yml` file to reflect that.

It finally worked. A wonderful solution.
