### ISSUE TITLE
error in examples 15_step_size_study

### ISSUE THREAD

**Issue by zcgzcg50** [WISDEM/WISDEM#542]
## Description
Console outputs are zeros. 
Step size | Deriv
000.01     0.0
00.005     0.0
00.001     0.0
0.0005     0.0
0.0001     0.0
05e-05     0.0
01e-05     0.0
05e-06     0.0
01e-06     0.0
05e-07     0.0
01e-07     0.0
05e-08     0.0
01e-08     0.0

### Steps to reproduce issue
I have checked other derives, which are also zeros.
![image](https://github.com/WISDEM/WISDEM/assets/97574914/50744f99-1a10-4d0b-b970-30c87cee3664)

### Current behavior
![image](https://github.com/WISDEM/WISDEM/assets/97574914/f3322e30-6da9-495c-b3c1-c570b965e0f8)
### Expected behavior
examples 15_step_size_study outputs are not zeros.

### Code versions
- wisdem 3.15.3
- Python 3.12

**Comment by gbarter** [comment]
Yes, we get the same result on our side.  Something changed in the upstream OpenMDAO library a while back such that this example stopped working.  It is a low priority for us to fix it, so this is essentially an empty example.  Let me know if this step size investigation is critical for you.
