### ISSUE TITLE
Reference axis not updating in model yaml

### ISSUE THREAD

**Issue by TheMercer** [WISDEM/WISDEM#543]
## Description
For example, take example 03 and you set wisdem to change rotor diameter. The .CSV will have all updated information. However the model yaml reference axis is not updating when this happens. 

The code is "updating" however the reference axis end length doesn't change. For example IEA 15MW. if I changed it's diameter to 235 or 245. The reference axis total length stays at 117 meters.

### Steps to reproduce issue
_Please provide a minimum working example (MWE) if possible_

1. Example 03 Blade with wisdem lines on Rotor to change rotor diameter 
2. rotor_diameter:
        flag: True
        minimum: 236
        maximum: 236

### Current behavior
… CSV has all correct information. However model yaml does not.

### Expected behavior
… Model yaml information to match CSV output 
IEA15MW chnaging diamter to 236
blade.outer_shape_bem.ref_axis - > [0.00000000e+00
 4.03448276e+00
 8.06896552e+00
 ...
 1.08931034e+02
 1.12965517e+02
 1.17000000e+02]

however
configuration.rotor_diameter_user = 236
rotorse.rc.blade_length = 115.68213766 (this is what the blade length should be)

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/ksm/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/ksm/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link=blue vlink=purple>

rotorse.rc.blade_length
--

</body>

</html>

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/ksm/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/ksm/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link=blue vlink=purple>

configuration.rotor_diameter_user
--

</body>

</html>

### Code versions
_List versions only if relevant_
- Used WEIS 
- …

**Comment by TheMercer** [comment]
I had to update ref_axis z manually. Is there a way to get wisdom to change the length of the blade for you?

**Comment by gbarter** [comment]
WISDEM intentionally does not overwrite any input files.  In the output directory, you should see the output yaml files.  If you run an optimization, the design variables will be updated in the yaml file in the output directory.

From the inputs you provided, it looks like you want to specify the rotor diameter directly, and not really let it be a design variable.  If that is the case, you can change the `rotor_diameter` parameter at the top of the input yaml file. WISDEM should update the reference axis accordingly.

**Comment by TheMercer** [comment]
Oh okay I will try that, just wasn't doing it when I was trying but will try with fresh set up.

**Comment by TheMercer** [comment]
@gbarter Yeah just tried it, where I changed diameter in input yaml. 

The ref axis didn't change, it stayed at 117, rotor diameter of 236 and hub of 5, blade length should be 115.5

**Comment by TheMercer** [comment]
output yaml

name: IEA 15MW Offshore Reference Turbine, with taped chord tip design
assembly: {turbine_class: I, turbulence_class: B, drivetrain: direct_drive, rotor_orientation: Upwind, number_of_blades: 3, hub_height: 150.0, rotor_diameter: 236.0, rated_power: 15000000.0, lifetime: 25.0}

                z:
                    grid: [0.0, 0.034482758620689655, 0.06896551724137931, 0.10344827586206896, 0.13793103448275862, 0.1724137931034483, 0.20689655172413793, 0.24137931034482757, 0.27586206896551724, 0.3103448275862069, 0.3448275862068966, 0.3793103448275862, 0.41379310344827586, 0.4482758620689655, 0.48275862068965514, 0.5172413793103449, 0.5517241379310345, 0.5862068965517241, 0.6206896551724138, 0.6551724137931034, 0.6896551724137931, 0.7241379310344828, 0.7586206896551724, 0.7931034482758621, 0.8275862068965517, 0.8620689655172413, 0.896551724137931, 0.9310344827586207, 0.9655172413793103, 1.0]
                    values: [0.0, 4.0344827586206895, 8.068965517241379, 12.10344827586207, 16.13793103448276, 20.17241379310345, 24.20689655172414, 28.241379310344826, 32.27586206896552, 36.31034482758621, 40.3448275862069, 44.37931034482758, 48.41379310344827, 52.44827586206897, 56.48275862068966, 60.51724137931035, 64.55172413793103, 68.58620689655172, 72.62068965517243, 76.6551724137931, 80.6896551724138, 84.72413793103448, 88.75862068965517, 92.79310344827586, 96.82758620689656, 100.86206896551724, 104.89655172413794, 108.93103448275863, 112.9655172413793, 116.99999999999999]

**Comment by TheMercer** [comment]
Also optimising twist and chord does that lock it ?

should I scale then optimise ?

**Comment by ptrbortolotti** [comment]
hello @TheMercer , optimizing chord and twist won't affect the scaling. the scaling should definitely work. let me confirm: in the input yaml file you can set your desired rotor diameter, and this will scale the z field in the blade aero reference axis. aside from the reference axis, are your outputs changing when you vary your rotor diameter?

**Comment by TheMercer** [comment]
Yeah the grid is changing etc, twist and chord is changing just the total length of ref_axis is not

**Comment by ptrbortolotti** [comment]
Maybe I'm confused. The grid fields in the yaml files are defined nondimensional, and should not change. Where are those changing?

**Comment by TheMercer** [comment]
Input yaml:
                z:
                    grid: [0.0, 0.01694915254237288, 0.03389830508474576, 0.05084745762711865, 0.06779661016949153, 0.0847457627118644, 0.1016949152542373, 0.11864406779661017, 0.13559322033898305, 0.15254237288135594, 0.1694915254237288, 0.1864406779661017, 0.2033898305084746, 0.22033898305084745, 0.23728813559322035, 0.2542372881355932, 0.2711864406779661, 0.288135593220339, 0.3050847457627119, 0.3220338983050847, 0.3389830508474576, 0.3559322033898305, 0.3728813559322034, 0.3898305084745763, 0.4067796610169492, 0.423728813559322, 0.4406779661016949, 0.4576271186440678, 0.4745762711864407, 0.4915254237288136, 0.5084745762711864, 0.5254237288135594, 0.5423728813559322, 0.559322033898305, 0.576271186440678, 0.5932203389830508, 0.6101694915254238, 0.6271186440677966, 0.6440677966101694, 0.6610169491525424, 0.6779661016949152, 0.6949152542372882, 0.711864406779661, 0.7288135593220338, 0.7457627118644068, 0.7627118644067796, 0.7796610169491526, 0.7966101694915254, 0.8135593220338984, 0.8305084745762712, 0.847457627118644, 0.864406779661017, 0.8813559322033898, 0.8983050847457628, 0.9152542372881356, 0.9322033898305084, 0.9491525423728814, 0.9661016949152542, 0.9830508474576272, 1.0]
                    values: [0.0, 1.9830508474576272, 3.9661016949152543, 5.9491525423728815, 7.932203389830508, 9.915254237288135, 11.898305084745765, 13.881355932203391, 15.864406779661019, 17.847457627118647, 19.83050847457627, 21.8135593220339, 23.79661016949153, 25.77966101694915, 27.76271186440678, 29.74576271186441, 31.728813559322038, 33.71186440677967, 35.694915254237294, 37.67796610169491, 39.66101694915254, 41.644067796610166, 43.62711864406779, 45.610169491525426, 47.59322033898305, 49.57627118644068, 51.559322033898304, 53.54237288135593, 55.525423728813564, 57.50847457627119, 59.4915254237288, 61.47457627118645, 63.45762711864406, 65.44067796610169, 67.42372881355932, 69.40677966101696, 71.38983050847459, 73.37288135593221, 75.35593220338983, 77.33898305084746, 79.32203389830508, 81.30508474576271, 83.28813559322035, 85.27118644067797, 87.2542372881356, 89.23728813559322, 91.22033898305085, 93.20338983050847, 95.18644067796612, 97.16949152542374, 99.15254237288136, 101.13559322033899, 103.11864406779661, 105.10169491525424, 107.08474576271188, 109.0677966101695, 111.05084745762711, 113.03389830508475, 115.01694915254238, 116.99999999999999]
                    
 output yaml
                 z:
                    grid: [0.0, 0.034482758620689655, 0.06896551724137931, 0.10344827586206896, 0.13793103448275862, 0.1724137931034483, 0.20689655172413793, 0.24137931034482757, 0.27586206896551724, 0.3103448275862069, 0.3448275862068966, 0.3793103448275862, 0.41379310344827586, 0.4482758620689655, 0.48275862068965514, 0.5172413793103449, 0.5517241379310345, 0.5862068965517241, 0.6206896551724138, 0.6551724137931034, 0.6896551724137931, 0.7241379310344828, 0.7586206896551724, 0.7931034482758621, 0.8275862068965517, 0.8620689655172413, 0.896551724137931, 0.9310344827586207, 0.9655172413793103, 1.0]
                    values: [0.0, 4.0344827586206895, 8.068965517241379, 12.10344827586207, 16.13793103448276, 20.17241379310345, 24.20689655172414, 28.241379310344826, 32.27586206896552, 36.31034482758621, 40.3448275862069, 44.37931034482758, 48.41379310344827, 52.44827586206897, 56.48275862068966, 60.51724137931035, 64.55172413793103, 68.58620689655172, 72.62068965517243, 76.6551724137931, 80.6896551724138, 84.72413793103448, 88.75862068965517, 92.79310344827586, 96.82758620689656, 100.86206896551724, 104.89655172413794, 108.93103448275863, 112.9655172413793, 116.99999999999999]

**Comment by ptrbortolotti** [comment]
you are correct, the grid changes because WISDEM reinterpolates every field onto a common grid. The discretization of the common grid can be specified in the modeling options yaml file, under n_span https://github.com/WISDEM/WISDEM/blob/d0632f85116f4cf6073abede4c517f4b1f703e60/wisdem/inputs/modeling_schema.yaml#L50

I can now also see that the blade refs was no longer being updated. It is now in this branch https://github.com/WISDEM/WISDEM/tree/Issue543, which we'll merge soon to WISDEM develop. The commit is very simple, so feel free to cherry pick it

**Comment by TheMercer** [comment]
Oh okay, perfect I didn't realise it was already own issue. I will have a look at this in the morning.

**Comment by TheMercer** [comment]
I got this error after updating those 3 lines

Traceback (most recent call last):
  File "P:\UNCLASSIFIED\NONE\021523\GLOBAL\PV_modelling\BladeWEIS-Master\01_v236\blade_driver.py", line 15, in <module>
    wt_opt, modeling_options, analysis_options = run_wisdem(
                                                 ^^^^^^^^^^^
  File "C:\Miniconda3\envs\weis-env\Lib\site-packages\wisdem\glue_code\runWISDEM.py", line 186, in run_wisdem
    wt_initial.write_ontology(wt_opt, froot_out)
  File "C:\Miniconda3\envs\weis-env\Lib\site-packages\wisdem\glue_code\gc_LoadInputs.py", line 862, in write_ontology
    self.wt_init["components"]["blade"]["outer_shape_bem"]["reference_axis"]["x"]["values"] = wt_opt[
                                                                                              ^^^^^^^
  File "C:\Miniconda3\envs\weis-env\Lib\site-packages\openmdao\core\problem.py", line 504, in __getitem__
    return self.get_val(name, get_remote=None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Miniconda3\envs\weis-env\Lib\site-packages\openmdao\core\problem.py", line 545, in get_val
    val = self.model.get_val(name, units=units, indices=indices, get_remote=get_remote,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Miniconda3\envs\weis-env\Lib\site-packages\openmdao\core\system.py", line 5267, in get_val
    raise KeyError('{}: Variable "{}" not found.'.format(self.msginfo, name))
KeyError: '<model> <class WindPark>: Variable "high_level_blade_props.blade_ref_axis" not found.'

**Comment by TheMercer** [comment]
@ptrbortolotti @gbarter, Thank you both for the support on this issue, I have checked it on my current set up as well and all working well.
