### ISSUE TITLE
Failed tests after installation

### ISSUE THREAD

**Issue by hishamtariq19** [WISDEM/WISDEM#572]
I installed WISDEM on Windows 11 and tried to run units tests in the test directory. However, I got the following summary:

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
===================================================================== short test summary info =====================================================================
FAILED ..\wisdem\test\test_ccblade\test_gradients.py::TestGradients::test_dhubht1 - AssertionError:
FAILED ..\wisdem\test\test_ccblade\test_gradients.py::TestGradients::test_dtheta1 - AssertionError:
FAILED ..\wisdem\test\test_ccblade\test_gradients.py::TestGradients::test_dtheta2 - AssertionError:
FAILED ..\wisdem\test\test_ccblade\test_gradients.py::TestGradients_RHub_Tip::test_dchord2 - AssertionError:
FAILED ..\wisdem\test\test_ccblade\test_gradients.py::TestGradients_RHub_Tip::test_dhubht1 - AssertionError:
FAILED ..\wisdem\test\test_ccblade\test_gradients.py::TestGradients_RHub_Tip::test_dtheta1 - AssertionError:
FAILED ..\wisdem\test\test_ccblade\test_gradients.py::TestGradients_RHub_Tip::test_dtheta2 - AssertionError:
FAILED ..\wisdem\test\test_examples\test_examples.py::TestExamples::test_all_scripts - AssertionError: '05_tower_monopile/monopile_direct' != 'Success'
FAILED ..\wisdem\test\test_fixed_bottomse\test_monopile.py::TestMonopileSE::testAddedMassForces - numpy.linalg.LinAlgError: 'perf.monopile' <class MonopileFrame>: Error calling compute(), SVD did not converge in Linear Least Squares
FAILED ..\wisdem\test\test_gluecode\test_drivers.py::TestRegression::test_cobyla - sqlite3.OperationalError: table global_iterations already exists
FAILED ..\wisdem\test\test_gluecode\test_drivers.py::TestRegression::test_ld_slsqp - sqlite3.OperationalError: table global_iterations already exists
FAILED ..\wisdem\test\test_gluecode\test_drivers.py::TestRegression::test_nelder - sqlite3.OperationalError: table global_iterations already exists
FAILED ..\wisdem\test\test_optimization_drivers\test_nlopt_driver.py::TestNLoptDriver::test_maxtime - ValueError: actual [6.66666667], desired [50.], rel error 0.8666666666666667, tolerance 1e-06
FAILED ..\wisdem\test\test_pyframe3dd\test_breakdown.py::TestBreakdown::testModal - AssertionError:
============================================ 14 failed, 1638 passed, 7 skipped, 1422888 warnings in 505.35s (0:08:25) =============================================

I am not sure where I went wrong and whether WISDEM is installed properly. Can you provide any information to solve this issue|?

**Comment by gbarter** [comment]
Those unit test you are seeing are quite sensitive to operating system, compiler, etc.  They are turned to pass only on linux and mac.  The failure on Windows is a numerical precision thing.  You are good to use WISDEM.
