### ISSUE TITLE
Warnings in Example 02 and error while using compare_designs outputs

### ISSUE THREAD

**Issue by hishamtariq19** [WISDEM/WISDEM#574]
I ran example 02 using the command "wisdem nrel5mw.yaml modeling_options.yaml analysis_options.yaml". The analysis was completed but it gave warnings. When I tried to compare designs using "compare_designs outputs", it displayed an error. I am not sure what the issue is. I am using WISDEM on Windows 11.

Can you please provide any useful information regarding this?

Warnngs and error messages are below:

(wisdem-env) C:\Windows\System32\WISDEM\examples\02_reference_turbines_executedCopy>wisdem nrel5mw.yaml modeling_options.yaml analysis_options.yaml

=========
wt.wt_rna
=========
←[00m←[00m←[00m←[00mNL: NLBGS 1 ; 4.0637118e+11 1
←[00m←[00m←[00m←[00mNL: NLBGS 2 ; 5128318.63 1.26197892e-05
←[00m←[00m←[00m←[00mNL: NLBGS 3 ; 0 0
NL: NLBGS Converged
←[00mFutureWarning: C:\ProgramData\miniforge3\envs\wisdem-env\Lib\site-packages\wisdem\landbosse\model\FoundationCost.py:668
The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.FutureWarning: C:\ProgramData\miniforge3\envs\wisdem-env\Lib\site-packages\wisdem\landbosse\model\SitePreparationCost.py:362
The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.FutureWarning: C:\ProgramData\miniforge3\envs\wisdem-env\Lib\site-packages\wisdem\landbosse\model\SitePreparationCost.py:362
The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.FutureWarning: C:\ProgramData\miniforge3\envs\wisdem-env\Lib\site-packages\wisdem\landbosse\model\SitePreparationCost.py:653
The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.FutureWarning: C:\ProgramData\miniforge3\envs\wisdem-env\Lib\site-packages\wisdem\landbosse\model\CollectionCost.py:847
The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.FutureWarning: C:\ProgramData\miniforge3\envs\wisdem-env\Lib\site-packages\wisdem\landbosse\model\ErectionCost.py:695
The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.########################################
Objectives
Turbine AEP: 23.9127972556 GWh
Blade Mass:  16419.8666989212 kg
LCOE:        51.6906874361 USD/MWh
Tip Defl.:   4.7295143980 m
########################################
Completed in, 12.049244165420532 seconds

(wisdem-env) C:\Windows\System32\WISDEM\examples\02_reference_turbines_executedCopy>compare_designs outputs/refturb_output.yaml

Loading WISDEM data for outputs/refturb_output.yaml.
C:\ProgramData\miniforge3\envs\wisdem-env\Lib\site-packages\openmdao\core\system.py:4357: OpenMDAOWarning:Calling `list_inputs` before `final_setup` will only display the default values of variables and will not show the result of any `set_val` calls.
C:\ProgramData\miniforge3\envs\wisdem-env\Lib\site-packages\openmdao\core\system.py:4357: OpenMDAOWarning:Calling `list_inputs` before `final_setup` will only display the default values of variables and will not show the result of any `set_val` calls.
+----------------------------------------------------+
| Comparison between WISDEM results from yaml files  |
+----------------------------------------------------+
| Data name       | run_0           | Units          |
+----------------------------------------------------+
Traceback (most recent call last):
  File "C:\ProgramData\miniforge3\envs\wisdem-env\Scripts\compare_designs-script.py", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "C:\ProgramData\miniforge3\envs\wisdem-env\Lib\site-packages\wisdem\postprocessing\compare_designs.py", line 839, in main
    run(list_of_sims, list_of_labels, modeling_options, analysis_options)
  File "C:\ProgramData\miniforge3\envs\wisdem-env\Lib\site-packages\wisdem\postprocessing\compare_designs.py", line 754, in run
    print_results_to_screen(list_of_sims, list_of_labels, values_to_print)
  File "C:\ProgramData\miniforge3\envs\wisdem-env\Lib\site-packages\wisdem\postprocessing\compare_designs.py", line 656, in print_results_to_screen
    size_of_variable = len(value_sizer)
                       ^^^^^^^^^^^^^^^^
TypeError: object of type 'numpy.float64' has no len()

**Comment by gbarter** [comment]
You can ignore the warnings.  On the `compare_designs` call, I think it is just the syntax that is in error.  You can always do `compare_designs --help` to get a reminder.  Try instead:
`compare_designs nrel5mw.yaml --modeling_options modeling_options.yaml --analysis_options analysis_options.yaml`

**Comment by hishamtariq19** [comment]
It worked. Thank you very much
