### ISSUE TITLE
CCBlade development - here or on WISDEM/CCBlade?

### ISSUE THREAD

**Issue by whophil** [WISDEM/WISDEM#60]
I proposed some changes to CCBlade on the `WISDEM/CCBlade` repo here: https://github.com/WISDEM/CCBlade/pull/16

Would those be better off targeting this repo?

**Comment by gbarter** [comment]
Sorry for the long delay in reply here.  There are actually a few CCBlade repos scattered around and we are struggling a little bit with differences between one and another.  The PR you submitted was for the original CCBlade.  Sometime in the future we will deprecate that one and consolidate things here.  A CCBlade alternative in Julia is [here](https://github.com/byuflowlab/CCBlade.jl).  A Matlab version is [here](https://github.com/jgeisler0303/CCBlade-M).  I think there might be a pure python version too, but I don't know the link.

I will take a look at the PR

**Comment by gbarter** [comment]
Final update and then I will close this issue.  We will keep the independent [CCBlade](https://github.com/WISDEM/CCBlade) repo up and treat that as a standalone BEM code.  The version embedded in WISDEM will be 99% the same, with some additional hooks for coupling with other modules.
