### ISSUE TITLE
WISDEM Installation problem

### ISSUE THREAD

**Issue by kevin74ha** [WISDEM/WISDEM#63]
Dear Developers,

I had installation problem of WISDEM. I am currently using ANACONDA (Python 3.7) and using gfortran by mingw64.
Below is warning and error statements
-------------------------------------------------------------------------------
warning: no directories found matching 'src\test'
warning: no previously-included files matching 'openmdao_log.txt' found anywhere in distribution
writing manifest file 'WISDEM.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
running build_ext
No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
customize MSVCCompiler
customize MSVCCompiler using build_ext
No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
customize MSVCCompiler
Missing compiler_cxx fix for MSVCCompiler
customize MSVCCompiler using build_ext
get_default_fcompiler: matching types: '['gnu', 'intelv', 'absoft', 'compaqv', 'intelev', 'gnu95', 'g95', 'intelvem', 'intelem', 'flang']'
customize GnuFCompiler
Could not locate executable g77
Could not locate executable f77
customize IntelVisualFCompiler
Could not locate executable ifort
Could not locate executable ifl
customize AbsoftFCompiler
Could not locate executable f90
customize CompaqVisualFCompiler
Could not locate executable DF
customize IntelItaniumVisualFCompiler
Could not locate executable efl
customize Gnu95FCompiler

py_frame3dd.obj : error LNK2001: free_D3matrix �ܺ� ��ȣ�� Ȯ���� �� �����ϴ�.
py_frame3dd.obj : error LNK2001: free_D3dmatrix �ܺ� ��ȣ�� Ȯ���� �� �����ϴ�.
py_main.obj : error LNK2001: D3matrix �ܺ� ��ȣ�� Ȯ���� �� �����ϴ�.
py_main.obj : error LNK2001: D3dmatrix �ܺ� ��ȣ�� Ȯ���� �� �����ϴ�.
build\lib.win-amd64-3.7\wisdem\pyframe3dd\_pyframe3dd.cp37-win_amd64.pyd : fatal error LNK1120: 4���� Ȯ���� �� ���� �ܺ� �����Դϴ�.

**Comment by gbarter** [comment]
This is an error in the installation for "developer" mode on a windows machine right?  I have updated the README of the install instructions.  Here is a set of commands that should get you up and running from source on a windows machine.  Check against the new README as well.

`conda config --add channels conda-forge`
`conda create -y --name wisdem-env python=3.7`
`conda activate wisdem-env`
`conda install -y wisdem git jupyter`
`conda remove --force wisdem`
`conda install m2w64-toolchain libpython`
`git clone https://github.com/WISDEM/WISDEM.git`
`cd WISDEM`
`python setup.py develop`
