### ISSUE TITLE
NameError: name 'nrelcsm' is not defined.

### ISSUE THREAD

**Issue by hawesdb** [WISDEM/WISDEM#65]
Hi, we are looking to import the bos_csm function from wisdom as such:
`from wisdem.nrelcsm.nrel_csm import bos_csm`

However we receive the error:
`  File "nrel_csm_run.py", line 11, in <module>
    from wisdem.nrelcsm.nrel_csm import bos_csm
  File "C:\Users\hawes\Anaconda3\envs\wisdem-env\lib\site-packages\wisdem\nrelcsm\nrel_csm.py", line 11, in <module>
    from wisdem.nrelcsm.config import *
  File "C:\Users\hawes\Anaconda3\envs\wisdem-env\lib\site-packages\wisdem\nrelcsm\config.py", line 22, in <module>
    ppi = PPI(ref_yr,ref_mon,curr_yr,curr_mon)
  File "C:\Users\hawes\Anaconda3\envs\wisdem-env\lib\site-packages\wisdem\nrelcsm\csmPPI.py", line 129, in __init__
    fullfile = os.path.join(nrelcsm.__path__[0], self.tblfile)
NameError: name 'nrelcsm' is not defined
(wisdem-env)
`

To my understanding it looks like the issue is because on line 129 in nrelcsm/csmPPi.py, there is a reference to nrelcsm, but the import at the top of the file looks like:
` import wisdem.nrelcsm`

**Comment by gbarter** [comment]
This has actually been fixed in one of our development branches, "openmdao2" (see commit: https://github.com/WISDEM/WISDEM/commit/83ce32beb29edb9db5e1a9678e0e6ee948b27c65 PR: #64 )  The easiest thing might be to use that branch.

**Comment by gbarter** [comment]
The development branch has been pushed to master, so this is resolved
