### ISSUE TITLE
some questions about drivese

### ISSUE THREAD

**Issue by timforrest** [WISDEM/WISDEM#87]
Dear Wisdem Team member
 I have some questions about the module of drivese , in the subroutine
" def nacelle_example_5MW_baseline_3pt", you give the rotor moments "prob['Mxyz'] = np.array([330770.0, -16665000.0, 2896300.0])  # Nm",which are "The rotor bending moment about the x axis,y  axis , z axis ,respectively." We used the bladed software to verify the moment results(Power :2Mw, rotor diameter 126m,), we found the rotor bending moment about x axis (hub loads:fixed frame GL coordinates) , is about 0.55 times of the moment about  y axis, but in "5MW_baseline_3pt" example : moment_x/moment_y=0.019(330770.0/16665000.0) ,so I doubt that  the bending moment about the x axis may be incorrect( moment about z axis has the same problem) ,or I have some misunderstandings about the  bending moment ?

**Comment by gbarter** [comment]
Hello Tim,

Thank you for the inquiry and apologies for the delay as I have been traveling all week.

In short, you should trust your Bladed output over the WISDEM numbers.  This is due the fact that WISDEM is a steady state analysis and not a time-domain analysis.  Therefore, it does not represent a turbine controller as there is no time-domain for the controller to operate.  I am not 100% certain where those moment values in the example came from as that file was written many years ago. However, it is likely that they came from a conservative rotor loading scenario that is trying to mimic an extreme loading case where a gust arrives while the rotor is at rated conditions.  In WISDEM this leads to very conservative values while in Bladed you likely have a controller that is pitching the blades and alleviating the torque and moments.  A better approach would be for you to use the values you obtained from Bladed as inputs to DriveSE.  If you want to compare Bladed moments against an equivalent NREL tool, then I would steer you towards using OpenFAST.  Let me know if this answers your question or not.

Cheers,
Garrett

**Comment by timforrest** [comment]
Hi Garrett, thank you for your relply, ok ,I will try to use the results of Bladed software  to check my model, thanks !
